force-app/main/default/objects/EquipmentMasterData__c/EquipmentMasterData__c.object-meta.xml
<CustomObject>
    <description>Coste y características sobre el equipo de la instalación.</description>
    <label>Maestro de Equipo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestros de equipos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EquipmentMasterData__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Coste</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EquipmentMasterData__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <label>Instalación</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EquipmentMasterData__c/fields/IsIndoor__c.field-meta.xml
<CustomField>
    <fullName>IsIndoor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Interior</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EquipmentMasterData__c/fields/SBQQProductCode__c.field-meta.xml
<CustomField>
    <fullName>SBQQProductCode__c</fullName>
    <description>Código de producto</description>
    <label>Product Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GasCost__c/GasCost__c.object-meta.xml
<CustomObject>
    <label>Coste de Gas</label>
    <nameField>
        <displayFormat>GC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costes de Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GasCost__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Coste</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GasCost__c/fields/TransportationCost__c.field-meta.xml
<CustomField>
    <fullName>TransportationCost__c</fullName>
    <label>Coste de Transporte</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GasPriceRange__c/GasPriceRange__c.object-meta.xml
<CustomObject>
    <label>Maestro de Margen de Gas</label>
    <nameField>
        <displayFormat>GPR {00000}</displayFormat>
        <label>Referencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestros de Margen de Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GasPriceRange__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>Provincia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPCAPEXRatio__c/GPCAPEXRatio__c.object-meta.xml
<CustomObject>
    <label>Ratio GP/CAPEX</label>
    <nameField>
        <displayFormat>GCR {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratios GP/CAPEX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPCAPEXRatio__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPCAPEXRatio__c/fields/CountyAverage__c.field-meta.xml
<CustomField>
    <fullName>CountyAverage__c</fullName>
    <label>Media</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Alava/Araba</fullName>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Bizkaia/Vizcaya</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Cáceres</fullName>
            </value>
            <value>
                <fullName>Cádiz</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Lleida/Lérida</fullName>
            </value>
            <value>
                <fullName>Lugo</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dimension1__c.field-meta.xml
<CustomField>
    <fullName>Dimension1__c</fullName>
    <label>Dimensión 1 (Producto)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10-BULK</fullName>
            </value>
            <value>
                <fullName>20-LNG</fullName>
            </value>
            <value>
                <fullName>30-AUTOGAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Spot.recordType-meta.xml
<RecordType>
    <fullName>Spot</fullName>
    <active>false</active>
    <businessProcess>Venta Nueva</businessProcess>
    <description>Oportunidad de venta Spot</description>
    <label>Spot</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <formula>TEXT (SBQQ__Opportunity2__r.County__c)</formula>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceCost__c/ServiceCost__c.object-meta.xml
<CustomObject>
    <label>Coste de Servicio</label>
    <nameField>
        <displayFormat>SC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costes de Servicio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceCost__c/fields/DomesticCost__c.field-meta.xml
<CustomField>
    <fullName>DomesticCost__c</fullName>
    <label>Coste Domésticos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceCost__c/fields/ProfessionalCost__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalCost__c</fullName>
    <label>Coste Profesionales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceCost__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicio</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Costes</relationshipLabel>
    <relationshipName>ServiceCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TankLegalizationCost__c/TankLegalizationCost__c.object-meta.xml
<CustomObject>
    <description>Costes asociados al depósito según la provincia donde se realice.</description>
    <label>Coste de Legalización de Depósito</label>
    <nameField>
        <displayFormat>TLC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costes de Legalización de Depósito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankLegalizationCost__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Coste</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankLegalizationCost__c/fields/Tank__c.field-meta.xml
<CustomField>
    <fullName>Tank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maestro de Depósito</label>
    <referenceTo>TankMasterData__c</referenceTo>
    <relationshipName>TankLegalizationCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TankMaintenanceCost__c/TankMaintenanceCost__c.object-meta.xml
<CustomObject>
    <description>Costes de mantenimiento según la provincia de instalación del depósito.</description>
    <label>Coste de Mantenimiento de Depósito</label>
    <nameField>
        <displayFormat>TMC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coste de Mantenimiento de Depósito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMaintenanceCost__c/fields/Tank__c.field-meta.xml
<CustomField>
    <fullName>Tank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maestro de depósito</label>
    <referenceTo>TankMasterData__c</referenceTo>
    <relationshipName>TankMaintenanceCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/TankMasterData__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los campos con información sobre las opciones y costes de instalación de los depósitos de gas.</description>
    <label>Maestro de Depósito</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestro de Depósitos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMasterData__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description>Capacidad del del depósito de gas</description>
    <label>Capacidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/CivilWorks__c.field-meta.xml
<CustomField>
    <fullName>CivilWorks__c</fullName>
    <description>Coste de la obra</description>
    <label>Obra Civil</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Coste del depósito</description>
    <label>Coste</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/Dismantle__c.field-meta.xml
<CustomField>
    <fullName>Dismantle__c</fullName>
    <description>Coste del desmantelamiento del depósito</description>
    <label>Desmantelamiento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/EarlyTermination__c.field-meta.xml
<CustomField>
    <fullName>EarlyTermination__c</fullName>
    <label>Resolución Anticipada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/Fencing__c.field-meta.xml
<CustomField>
    <fullName>Fencing__c</fullName>
    <description>Coste del vallado de la instalación.</description>
    <label>Vallado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <description>Coste de la instalación exterior</description>
    <label>Instalación</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/IsAerial__c.field-meta.xml
<CustomField>
    <fullName>IsAerial__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicación de si es un depósito al aire.</description>
    <label>Es Aéreo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/ProjectMemory__c.field-meta.xml
<CustomField>
    <fullName>ProjectMemory__c</fullName>
    <label>Proyecto / Memoria</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/Transport__c.field-meta.xml
<CustomField>
    <fullName>Transport__c</fullName>
    <description>Coste del Transporte de depósito</description>
    <label>Transporte</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/County.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A Coruña/La Coruña</fullName>
    </customValue>
    <customValue>
        <fullName>Alava/Araba</fullName>
    </customValue>
    <customValue>
        <fullName>Albacete</fullName>
    </customValue>
    <customValue>
        <fullName>Alicante</fullName>
    </customValue>
    <customValue>
        <fullName>Asturias</fullName>
    </customValue>
    <customValue>
        <fullName>Avila</fullName>
    </customValue>
    <customValue>
        <fullName>Badajoz</fullName>
    </customValue>
    <customValue>
        <fullName>Barcelona</fullName>
    </customValue>
    <customValue>
        <fullName>Bizkaia/Vizcaya</fullName>
    </customValue>
    <customValue>
        <fullName>Burgos</fullName>
    </customValue>
    <customValue>
        <fullName>Cáceres</fullName>
    </customValue>
    <customValue>
        <fullName>Cantabria</fullName>
    </customValue>
    <customValue>
        <fullName>Castellón</fullName>
    </customValue>
    <customValue>
        <fullName>Ciudad Real</fullName>
    </customValue>
    <customValue>
        <fullName>Cuenca</fullName>
    </customValue>
    <customValue>
        <fullName>Gipuzkoa/Guipuzcoa</fullName>
    </customValue>
    <customValue>
        <fullName>Girona/Gerona</fullName>
    </customValue>
    <customValue>
        <fullName>Guadalajara</fullName>
    </customValue>
    <customValue>
        <fullName>Huesca</fullName>
    </customValue>
    <customValue>
        <fullName>La Rioja</fullName>
    </customValue>
    <customValue>
        <fullName>León</fullName>
    </customValue>
    <customValue>
        <fullName>Lleida/Lérida</fullName>
    </customValue>
    <customValue>
        <fullName>Lugo</fullName>
    </customValue>
    <customValue>
        <fullName>Madrid</fullName>
    </customValue>
    <customValue>
        <fullName>Navarra</fullName>
    </customValue>
    <customValue>
        <fullName>Orense/Ourense</fullName>
    </customValue>
    <customValue>
        <fullName>Palencia</fullName>
    </customValue>
    <customValue>
        <fullName>Pontevedra</fullName>
    </customValue>
    <customValue>
        <fullName>Salamanca</fullName>
    </customValue>
    <customValue>
        <fullName>Segovia</fullName>
    </customValue>
    <description>Provincias en las que Primagas trabaja</description>
    <masterLabel>County</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ApprovalTestDataFactory.cls
@isTest
public class ApprovalTestDataFactory {

    private static final String RESOURCE_NAME_PRODUCTS = 'TEST_Products';

    public static final String OPPORTUNITY_STAGE_DEFAULT = 'Identificada';
    public static final String TANK_NAME_DEFAULT = 'CoolTank';
    public static final String COUNTY_DEFAULT = 'Barcelona';
    public static final String DIMENSION_1_DEFAULT = '10-BULK';
    public static final String DIMENSION_3_DEFAULT = '1000-DU';
    public static final Boolean IS_TANK_OWNER_DEFAULT = false;
    public static final String CODE_EQUIPMENT_DEFAULT = 'EQUIPOCONTADOR';
    public static final String CODE_SERVICE_COST_DEFAULT = 'MANTINTERIORES';
    public static final String CODE_GAS_RATE_DEFAULT = 'SPOT';
    public static final Integer ESTIMATED_CONSUMPTION_DEFAULT = 5000;
    public static final Integer CONTRACT_DURATION_DEFAULT = 5;

    public static Map<String, Product2> products {
        get {
            if (products == null) {
                products = new Map<String, Product2>();
                for (Product2 product : ApprovalTestDataFactory.loadProductData()) {
                    products.put(product.ProductCode, product);
                }
                insert ApprovalTestDataFactory.createPricebookEntries(products.values());        
            }
            return products;
        }
        set;
    }

    public static void createSampleMasterData() {
        TankMasterData__c tankMasterData = new TankMasterData__c(
            Name = TANK_NAME_DEFAULT, 
            Capacity__c = 15000,
            IsAerial__c = true,
            Cost__c = 3500,
            CivilWorks__c = 1200,
            Dismantle__c = 1251,
            EarlyTermination__c = 1200,
            Fencing__c = 700,
            Installation__c = 1600,
            ProjectMemory__c = 300,
            Transport__c = 500
        );
        insert tankMasterData;
        EquipmentMasterData__c equipmentMasterData = new EquipmentMasterData__c(
            Name = 'Sample Equipment',
            Cost__c = 1180,
            Installation__c = 300,
            IsIndoor__c = true,
            SBQQProductCode__c = CODE_EQUIPMENT_DEFAULT
        );
        insert equipmentMasterData;
        insert new TankLegalizationCost__c(
            Cost__c = 600,
            Tank__c = tankMasterData.Id,
            County__c = COUNTY_DEFAULT
        );
        insert new TankMaintenanceCost__c(
            Cost__c = 700,
            Tank__c = tankMasterData.Id,
            County__c = COUNTY_DEFAULT
        );
        insert new GasCost__c(
            Cost__c = 0.377,
            TransportationCost__c = 0.036,
            County__c = COUNTY_DEFAULT
        );
        insert new ServiceCost__c(
            ProfessionalCost__c = 300,
            DomesticCost__c = 150,
            County__c = COUNTY_DEFAULT,
            Service__c = products.get(CODE_SERVICE_COST_DEFAULT).Id
        );
        insert new GPCAPEXRatio__c(
            CountyAverage__c = 63,
            County__c = COUNTY_DEFAULT
        );
        insert new RateAssignation__c(
            Dimension1__c = DIMENSION_1_DEFAULT,
            Dimension3__c = DIMENSION_3_DEFAULT,
            IsTankOwner__c = IS_TANK_OWNER_DEFAULT,
            County__c = COUNTY_DEFAULT,
            Product__c = products.get(CODE_GAS_RATE_DEFAULT).Id
        );
        insert new GasPriceRange__c(
            Range__c = 0.477,
            County__c = COUNTY_DEFAULT
        );
    }

    public static List<Product2> loadProductData() {
        return (List<Product2>) Test.loadData(Product2.sObjectType, RESOURCE_NAME_PRODUCTS);
    }

    public static List<PricebookEntry> createPricebookEntries(List<Product2> products) {
        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
        for (Product2 product : products) {
            pricebookEntries.add(new PricebookEntry(
                Product2Id = product.Id,
                IsActive = true,
                Pricebook2Id = Test.getStandardPricebookId(),
                UnitPrice = 100 * Math.random()
            ));
        }
        return pricebookEntries;
    }

    public static SObject createSObject(String sObjectName, Map<String, Object> fieldValuePairs) {
        SObject newSObject = Schema.getGlobalDescribe().get(sObjectName).newSObject();
        setFieldValuePairs(newSObject, fieldValuePairs);
        return newSObject;
    }

    private static void setFieldValuePairs(SObject newSObject, Map<String, Object> optionalFieldValues) {
        if (optionalFieldValues != null && !optionalFieldValues.isEmpty()) {
            for (String fieldName : optionalFieldValues.keySet()) {
                newSObject.put(fieldName, optionalFieldValues.get(fieldName));
            }
        }
    }

    public static Account createAccount(Map<String, Object> optionalFieldValues) {
        Account account = new Account (
            Name = 'Leadclic ' + (Math.random() * 100)            
        );
        setFieldValuePairs(account, optionalFieldValues);
        return account;
    }

    public static Opportunity createOpportunity(Id accountId, Map<String, Object> optionalFieldValues) {
        Opportunity opportunity = new Opportunity(
            AccountId = accountId,
            CloseDate = System.today().addDays(30),
            StageName = OPPORTUNITY_STAGE_DEFAULT,
            Name = 'Test Opportunity ' + (Math.random() * 100),
            Dimension1__c = DIMENSION_1_DEFAULT,
            Dimension3__c = DIMENSION_3_DEFAULT,
            Cliente_propietario_del_tanque__c = IS_TANK_OWNER_DEFAULT,
            County__c = COUNTY_DEFAULT
        );
        setFieldValuePairs(opportunity, optionalFieldValues);
        return opportunity;
    }

    public static SBQQ__Quote__c createQuote(Id opportunityId, Map<String, Object> optionalFieldValues) {
        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = opportunityId,
            EstimatedConsumption__c = ESTIMATED_CONSUMPTION_DEFAULT,
            Duration__c = CONTRACT_DURATION_DEFAULT,
            ClientTank__c = IS_TANK_OWNER_DEFAULT
        );
        setFieldValuePairs(quote, optionalFieldValues);
        return quote;
    }
}