force-app/main/default/objects/EquipmentMasterData__c/EquipmentMasterData__c.object-meta.xml
<CustomObject>
    <description>Coste y características sobre el equipo de la instalación.</description>
    <label>Maestro de Equipo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestros de equipos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EquipmentMasterData__c/fields/IsIndoor__c.field-meta.xml
<CustomField>
    <fullName>IsIndoor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Interior</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EquipmentMasterData__c/fields/IsRecoverable__c.field-meta.xml
<CustomField>
    <fullName>IsRecoverable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Recuperable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EquipmentMasterData__c/fields/SBQQProductCode__c.field-meta.xml
<CustomField>
    <fullName>SBQQProductCode__c</fullName>
    <description>Código de producto</description>
    <label>Product Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPQ_EquipmentMasterData.cls
public without sharing class CPQ_EquipmentMasterData {
    
    public static EquipmentMasterData getForQuoteWrappers(CPQ_Quote.QuoteWrapper quoteWrapper){
        return getForQuoteWrappers(new List<CPQ_Quote.QuoteWrapper>{quoteWrapper});
    }

    public static EquipmentMasterData getForQuoteWrappers(List<CPQ_Quote.QuoteWrapper> quoteWrappers){
        Set<String> productCodes = new Set<String>();

        for(CPQ_Quote.QuoteWrapper w : quoteWrappers){
            for(SBQQ__QuoteLine__c l : w.Lines){
                if(String.isNotBlank(l.SBQQ__ProductCode__c))
                    productCodes.add(l.SBQQ__ProductCode__c);
            }
        }
        return new EquipmentMasterData(CPQ_EquipmentMasterDataSelector.selectByProductCodes(productCodes));
    }

    public class EquipmentMasterData {
        private Map<String, EquipmentMasterData__c> emdByProductCode = new Map<String, EquipmentMasterData__c>();

        public EquipmentMasterData(List<EquipmentMasterData__c> tmds){
            for(EquipmentMasterData__c e : tmds){
                emdByProductCode.put(e.SBQQProductCode__c, e);
            }
        }

        public Set<String> filterProductCodesRecoverable(Set<String> productCodesToFilter){
            Set<String> output = new Set<String>();

            if(productCodesToFilter != null && productCodesToFilter.size() > 0){
                for(String code : productCodesToFilter){
                    if(emdByProductCode.containsKey(code) && emdByProductCode.get(code).IsRecoverable__c){
                        output.add(code);
                    }
                }
            }
            return output;
        }
        
        public List<String> filterProductCodesByIsIndoor(Boolean isIndoor, Set<String> productCodesToFilter){
            List<String> output = new List<String>();

            if(productCodesToFilter != null && productCodesToFilter.size() > 0){
                for(String code : productCodesToFilter){
                    if(emdByProductCode.containsKey(code) && emdByProductCode.get(code).IsIndoor__c == isIndoor){
                        output.add(code);
                    }
                }
            }
            return output;
        }

    }
}