force-app/main/default/objects/EquipmentMasterData__c/EquipmentMasterData__c.object-meta.xml
<CustomObject>
    <description>Coste y características sobre el equipo de la instalación.</description>
    <label>Maestro de Equipo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestros de equipos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EquipmentMasterData__c/fields/IsIndoor__c.field-meta.xml
<CustomField>
    <fullName>IsIndoor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Interior</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EquipmentMasterData__c/fields/IsRecoverable__c.field-meta.xml
<CustomField>
    <fullName>IsRecoverable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Recuperable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EquipmentMasterData__c/fields/SBQQProductCode__c.field-meta.xml
<CustomField>
    <fullName>SBQQProductCode__c</fullName>
    <description>Código de producto</description>
    <label>Product Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPQ_EquipmentMasterDataSelector.cls
public without sharing class CPQ_EquipmentMasterDataSelector {
    public static List<EquipmentMasterData__c> selectByIsIndoor(Boolean isIndoor) {
        return [
            SELECT SBQQProductCode__c
            FROM EquipmentMasterData__c
            WHERE IsIndoor__c = :isIndoor
        ];
    }

    public static List<EquipmentMasterData__c> selectByProductCodes(Set<String> productCodes) {
        return [
            SELECT SBQQProductCode__c, IsRecoverable__c, IsIndoor__c
            FROM EquipmentMasterData__c
            WHERE SBQQProductCode__c IN :productCodes
        ];
    }
}