force-app/main/default/objects/GasPriceRange__c/GasPriceRange__c.object-meta.xml
<CustomObject>
    <label>Maestro de Margen de Gas</label>
    <nameField>
        <displayFormat>GPR {00000}</displayFormat>
        <label>Referencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestros de Margen de Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GasPriceRange__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>Provincia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <formula>TEXT (SBQQ__Opportunity2__r.County__c)</formula>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/GasPriceRange__c.field-meta.xml
<CustomField>
    <fullName>GasPriceRange__c</fullName>
    <label>Margen de Gas</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <label>Inversión Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/NonRecoveryInvestment__c.field-meta.xml
<CustomField>
    <fullName>NonRecoveryInvestment__c</fullName>
    <label>Inversión no recuperable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PBA__c.field-meta.xml
<CustomField>
    <fullName>PBA__c</fullName>
    <label>PBA</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/County.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A Coruña/La Coruña</fullName>
    </customValue>
    <customValue>
        <fullName>Alava/Araba</fullName>
    </customValue>
    <customValue>
        <fullName>Albacete</fullName>
    </customValue>
    <customValue>
        <fullName>Alicante</fullName>
    </customValue>
    <customValue>
        <fullName>Asturias</fullName>
    </customValue>
    <customValue>
        <fullName>Avila</fullName>
    </customValue>
    <customValue>
        <fullName>Badajoz</fullName>
    </customValue>
    <customValue>
        <fullName>Barcelona</fullName>
    </customValue>
    <customValue>
        <fullName>Bizkaia/Vizcaya</fullName>
    </customValue>
    <customValue>
        <fullName>Burgos</fullName>
    </customValue>
    <customValue>
        <fullName>Cáceres</fullName>
    </customValue>
    <customValue>
        <fullName>Cantabria</fullName>
    </customValue>
    <customValue>
        <fullName>Castellón</fullName>
    </customValue>
    <customValue>
        <fullName>Ciudad Real</fullName>
    </customValue>
    <customValue>
        <fullName>Cuenca</fullName>
    </customValue>
    <customValue>
        <fullName>Gipuzkoa/Guipuzcoa</fullName>
    </customValue>
    <customValue>
        <fullName>Girona/Gerona</fullName>
    </customValue>
    <customValue>
        <fullName>Guadalajara</fullName>
    </customValue>
    <customValue>
        <fullName>Huesca</fullName>
    </customValue>
    <customValue>
        <fullName>La Rioja</fullName>
    </customValue>
    <customValue>
        <fullName>León</fullName>
    </customValue>
    <customValue>
        <fullName>Lleida/Lérida</fullName>
    </customValue>
    <customValue>
        <fullName>Lugo</fullName>
    </customValue>
    <customValue>
        <fullName>Madrid</fullName>
    </customValue>
    <customValue>
        <fullName>Navarra</fullName>
    </customValue>
    <customValue>
        <fullName>Orense/Ourense</fullName>
    </customValue>
    <customValue>
        <fullName>Palencia</fullName>
    </customValue>
    <customValue>
        <fullName>Pontevedra</fullName>
    </customValue>
    <customValue>
        <fullName>Salamanca</fullName>
    </customValue>
    <customValue>
        <fullName>Segovia</fullName>
    </customValue>
    <description>Provincias en las que Primagas trabaja</description>
    <masterLabel>County</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CPQ_QuoteRepository.cls
public inherited sharing class CPQ_QuoteRepository {

    public static List<SBQQ__Quote__c> getOpportunityDraftQuotes(Set<Id> opportunityIds) {
        return [
            SELECT
                Id,
                County__c,
                SBQQ__Status__c
            FROM
                SBQQ__Quote__c
            WHERE
                SBQQ__Opportunity2__c IN :opportunityIds
            AND 
                SBQQ__Status__c = :CPQ_QuoteConstants.STATUS_DRAFT
        ];
    }

    public static SBQQ__Quote__c getQuoteById(Id quoteId) {
        return [
            SELECT 
                Id,
                PBA__c,
                GasPriceRange__c,
                Credit__c,
                Investment__c,
                NonRecoveryInvestment__c
            FROM
                SBQQ__Quote__c
            WHERE
                Id = :quoteId
        ][0];
    }

}