force-app/main/default/objects/GasPriceRange__c/GasPriceRange__c.object-meta.xml
<CustomObject>
    <label>Maestro de Margen de Gas</label>
    <nameField>
        <displayFormat>GPR {00000}</displayFormat>
        <label>Referencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestros de Margen de Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GasPriceRange__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>Provincia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GasPriceRange__c/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <label>Margen</label>
    <precision>8</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/County.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A Coruña/La Coruña</fullName>
    </customValue>
    <customValue>
        <fullName>Alava/Araba</fullName>
    </customValue>
    <customValue>
        <fullName>Albacete</fullName>
    </customValue>
    <customValue>
        <fullName>Alicante</fullName>
    </customValue>
    <customValue>
        <fullName>Asturias</fullName>
    </customValue>
    <customValue>
        <fullName>Avila</fullName>
    </customValue>
    <customValue>
        <fullName>Badajoz</fullName>
    </customValue>
    <customValue>
        <fullName>Barcelona</fullName>
    </customValue>
    <customValue>
        <fullName>Bizkaia/Vizcaya</fullName>
    </customValue>
    <customValue>
        <fullName>Burgos</fullName>
    </customValue>
    <customValue>
        <fullName>Cáceres</fullName>
    </customValue>
    <customValue>
        <fullName>Cantabria</fullName>
    </customValue>
    <customValue>
        <fullName>Castellón</fullName>
    </customValue>
    <customValue>
        <fullName>Ciudad Real</fullName>
    </customValue>
    <customValue>
        <fullName>Cuenca</fullName>
    </customValue>
    <customValue>
        <fullName>Gipuzkoa/Guipuzcoa</fullName>
    </customValue>
    <customValue>
        <fullName>Girona/Gerona</fullName>
    </customValue>
    <customValue>
        <fullName>Guadalajara</fullName>
    </customValue>
    <customValue>
        <fullName>Huesca</fullName>
    </customValue>
    <customValue>
        <fullName>La Rioja</fullName>
    </customValue>
    <customValue>
        <fullName>León</fullName>
    </customValue>
    <customValue>
        <fullName>Lleida/Lérida</fullName>
    </customValue>
    <customValue>
        <fullName>Lugo</fullName>
    </customValue>
    <customValue>
        <fullName>Madrid</fullName>
    </customValue>
    <customValue>
        <fullName>Navarra</fullName>
    </customValue>
    <customValue>
        <fullName>Orense/Ourense</fullName>
    </customValue>
    <customValue>
        <fullName>Palencia</fullName>
    </customValue>
    <customValue>
        <fullName>Pontevedra</fullName>
    </customValue>
    <customValue>
        <fullName>Salamanca</fullName>
    </customValue>
    <customValue>
        <fullName>Segovia</fullName>
    </customValue>
    <description>Provincias en las que Primagas trabaja</description>
    <masterLabel>County</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GasPriceRangeService.cls
public inherited sharing class GasPriceRangeService {

    public static Map<String, GasPriceRange__c> getProvincePriceRanges(Set<String> selectedProvinces) {
        Map<String, GasPriceRange__c> gasPriceRangesByProvince = new Map<String, GasPriceRange__c>();
        for (GasPriceRange__c range : getGasPriceRangesByProvince(selectedProvinces)) {
            gasPriceRangesByProvince.put(range.County__c, range);
        }
        return gasPriceRangesByProvince;
    }

    private static List<GasPriceRange__c> getGasPriceRangesByProvince(Set<String> selectedProvinces) {
        return [
            SELECT
                Id, 
                County__c, 
                Range__c
            FROM
                GasPriceRange__c
            WHERE
                County__c IN :selectedProvinces
        ];
    }
}