force-app/main/default/objects/ServiceCost__c/ServiceCost__c.object-meta.xml
<CustomObject>
    <label>Coste de Servicio</label>
    <nameField>
        <displayFormat>SC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costes de Servicio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceCost__c/fields/DomesticCost__c.field-meta.xml
<CustomField>
    <fullName>DomesticCost__c</fullName>
    <label>Coste Domésticos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceCost__c/fields/ProfessionalCost__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalCost__c</fullName>
    <label>Coste Profesionales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceCost__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicio</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Costes</relationshipLabel>
    <relationshipName>ServiceCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CPQ_ServiceCostSelector.cls
public with sharing class CPQ_ServiceCostSelector {
    
    public static List<ServiceCost__c> selectByProvinces(Set<String> provinces){
        CPQ_LogUtil.debug('*SELECTOR* [CPQ_ServiceCostSelector] selectByProvinces');
        return [SELECT  Id,
                        DomesticCost__c,
                        ProfessionalCost__c,
                        County__c,
                        Service__c
                FROM ServiceCost__c
                WHERE County__c IN :provinces];
    }
}