force-app/main/default/objects/TankMasterData__c/TankMasterData__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los campos con información sobre las opciones y costes de instalación de los depósitos de gas.</description>
    <label>Maestro de Depósito</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestro de Depósitos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMasterData__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description>Capacidad del del depósito de gas</description>
    <label>Capacidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/Dismantle__c.field-meta.xml
<CustomField>
    <fullName>Dismantle__c</fullName>
    <description>Coste del desmantelamiento del depósito</description>
    <label>Desmantelamiento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/EarlyTermination__c.field-meta.xml
<CustomField>
    <fullName>EarlyTermination__c</fullName>
    <label>Resolución Anticipada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/IsAerial__c.field-meta.xml
<CustomField>
    <fullName>IsAerial__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicación de si es un depósito al aire.</description>
    <label>Es Aéreo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CPQ_TankMasterDataSelector.cls
public without sharing class CPQ_TankMasterDataSelector {
    
    public static List<TankMasterData__c> selectByName(Set<String> names){
        CPQ_LogUtil.debug('*SELECTOR* [CPQ_TankMasterDataSelector] selectByName');
        return [SELECT  Id,
                        Name,
                        Dismantle__c,
                        EarlyTermination__c,
                        Capacity__c,
                        IsAerial__c
                FROM TankMasterData__c
                WHERE Name IN: names];
    }
}