force-app/main/default/objects/Quote/fields/CLV10__c.field-meta.xml
<CustomField>
    <fullName>CLV10__c</fullName>
    <label>CLV10</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/CLV5__c.field-meta.xml
<CustomField>
    <fullName>CLV5__c</fullName>
    <label>CLV5</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/Stretch__c.object-meta.xml
<CustomObject>
    <label>Tramo</label>
    <nameField>
        <label>Nombre del tramo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tramos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stretch__c/fields/CLV10__c.field-meta.xml
<CustomField>
    <fullName>CLV10__c</fullName>
    <label>CLV10</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/CLV5__c.field-meta.xml
<CustomField>
    <fullName>CLV5__c</fullName>
    <label>CLV5</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/DiscountKG__c.field-meta.xml
<CustomField>
    <fullName>DiscountKG__c</fullName>
    <label>Dto. Kg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/FromConsumptionKG__c.field-meta.xml
<CustomField>
    <fullName>FromConsumptionKG__c</fullName>
    <label>Consumo desde Kg</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/FromPercentage__c.field-meta.xml
<CustomField>
    <fullName>FromPercentage__c</fullName>
    <label>Porcentaje desde</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/PBA__c.field-meta.xml
<CustomField>
    <fullName>PBA__c</fullName>
    <label>PBA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/PriceTodayKG__c.field-meta.xml
<CustomField>
    <fullName>PriceTodayKG__c</fullName>
    <label>Precio HOY Kg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/PrimaServiciosA__c.field-meta.xml
<CustomField>
    <fullName>PrimaServiciosA__c</fullName>
    <label>Primaservicios</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Stretches</relationshipLabel>
    <relationshipName>Stretches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CPQ_Stretch.cls
public without sharing class CPQ_Stretch {

    public static final Decimal DEFAUT_QUOTE_STRETCH_FROM_PERCENTAGE = 80;
    private static final Integer N_ATTEMPTS_FIND_PBA_DISCOUNT = CPQ_Settings.MaxSuggestedDiscountIterations;
    private static final Decimal DISCOUNT_AMOUNT_PER_ITERATION = CPQ_Settings.SuggestedDiscountIterationIncrement;
    
    public static void fillComputedValues(Stretch__c stretch,
                                          CPQ_Quote.QuoteWrapper quoteWrapper,
                                          CPQ_TablesDataWrapper tablesData,
                                          Boolean includePrimaservicios){

        // Desde (l/año) = Consumo anual (campo en quote) * Desde (%) / 100
        stretch.FromConsumptionKG__c = quoteWrapper.Quote.EstimatedConsumption__c * stretch.FromPercentage__c / 100;
        // Precio HOY €/kg = precio de la tarifa seleccionada en el quote
        stretch.PriceTodayKG__c = quoteWrapper.PriceTodayKG;

        if(includePrimaservicios){
            stretch.PrimaServiciosA__c = quoteWrapper.Primaservicios;
        }
    }

    public static void fillMetrics(Stretch__c stretch,
                                          CPQ_Quote.QuoteWrapper quoteWrapper,
                                          CPQ_TablesDataWrapper tablesData){
        
        stretch.PBA__c = CPQ_PBAService.build(quoteWrapper, stretch, tablesData, CPQ_PBAService.FULL_ESTIMATED_CONSUMPTION_COEF).calculateResult();
        stretch.CLV5__c = CPQ_CLVService.calculateResult(5, quoteWrapper, stretch, tablesData, CPQ_PBAService.FULL_ESTIMATED_CONSUMPTION_COEF);
        stretch.CLV10__c = CPQ_CLVService.calculateResult(10, quoteWrapper, stretch, tablesData, CPQ_PBAService.FULL_ESTIMATED_CONSUMPTION_COEF);
    }

    public static void fillSuggestedDiscount(Stretch__c stretch,
                                            CPQ_Quote.QuoteWrapper quoteWrapper,
                                            CPQ_TablesDataWrapper tablesData){
        
        stretch.DiscountKG__c = calculateSuggestedDiscount(stretch, quoteWrapper, tablesData);
    }

    /**
     * Finds the discount that results in a PBA value close to the 80% stretch and returns it.
     * The process is not the most performant as it iterates for a max number of
     * times or until the target value is reached, but it's the quickest to implement.
     * @param stretch 
     * @param quoteWrapper 
     * @param tablesData 
     */
    public static Decimal calculateSuggestedDiscount(Stretch__c stretch,
                                            CPQ_Quote.QuoteWrapper quoteWrapper,
                                            CPQ_TablesDataWrapper tablesData){
        
        Decimal originalDiscount = stretch.DiscountKG__c;
        Decimal REFERENCE_FROM_PERCENTAGE = 80;
                                                
        Stretch__c stretch100 = CPQ_StretchService.buildNewStretch(REFERENCE_FROM_PERCENTAGE, quoteWrapper);
        CPQ_Stretch.fillComputedValues(stretch100, quoteWrapper, tablesData, false);
        // Set the reference stretch100 PrimaserviciosA with the value in the provided stretch (to calculate the PBA taking it into account):
        stretch100.PrimaServiciosA__c = stretch.PrimaServiciosA__c;

        Decimal pba100 = CPQ_PBAService.build(quoteWrapper, stretch100, tablesData, CPQ_PBAService.FULL_ESTIMATED_CONSUMPTION_COEF).calculateResult();

        CPQ_LogUtil.debug('[CPQ_PBAService] calculateSuggestedDiscount Target PBA: '+pba100);

        Decimal discountOperationSign = (stretch.FromPercentage__c > REFERENCE_FROM_PERCENTAGE) ? 1 : -1;

        for(Integer i=0;i<N_ATTEMPTS_FIND_PBA_DISCOUNT;i++){
            Decimal foundPBA = CPQ_PBAService.build(quoteWrapper, stretch, tablesData, CPQ_PBAService.FULL_ESTIMATED_CONSUMPTION_COEF).calculateResult();
            if(foundPBA == null){
                // If PBA is null it means it cannot be calculated:
                CPQ_LogUtil.debug('[CPQ_PBASErvice] calculateSuggestedDiscount: PBA is null, skipping calculation.');
                break;
            }
            CPQ_LogUtil.debug('[CPQ_PBASErvice] calculateSuggestedDiscount: ('+foundPBA+' vs ' + pba100+') Discount: '+stretch.DiscountKG__c+ ' - '+stretch.FromPercentage__c);
            
            if(discountOperationSign > 0 && foundPBA >= pba100
            || discountOperationSign < 0 && foundPBA <= pba100){
                CPQ_LogUtil.debug('[CPQ_PBASErvice] calculateSuggestedDiscount: discount found for target PBA.');
                break;
            }
            stretch.DiscountKG__c += DISCOUNT_AMOUNT_PER_ITERATION * discountOperationSign;
        }
        Decimal calculatedDiscount = stretch.DiscountKG__c;
        stretch.DiscountKG__c = originalDiscount;
        return calculatedDiscount;
    }

    public static void deleteQuotesStretches(List<Id> quotesId){
        delete [SELECT Id FROM Stretch__c WHERE Quote__c IN :quotesId];
    }
}