force-app/main/default/objects/Pricebook2/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <label>Id Navision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Pendiente_de_confirmar__c.field-meta.xml
<CustomField>
    <fullName>Pendiente_de_confirmar__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se marca cuando está actualizado en Salesforce y falta por enviar confirmación a Navision</description>
    <label>Pendiente de confirmar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TEST_Nav2sfdc_Tarifas_Confirmacion.cls
@isTest
public class TEST_Nav2sfdc_Tarifas_Confirmacion {
	
	static testMethod void testPeticionWSConfirmarClientes()
	{
		Pricebook2 pb1 = new Pricebook2();
		pb1.Name = 'Desc1';
		pb1.Id_Navision__c = 'IdNav1';
		pb1.Description = 'Desc1';
		pb1.Pendiente_de_confirmar__c = true;
		insert pb1;
		
		Test.startTest();
		//En esta ocasión le pasamos los Ids de salesforce tanto de las direcciones como de las cuentas - Actualicación
        Test.setMock(HttpCalloutMock.class, new NTLMHttpCalloutMockImpl());
		Nav2sfdc_Tarifas_Confirmacion batchTarifas = new Nav2sfdc_Tarifas_Confirmacion();
    	batchTarifas.execute(null);
    	Test.stopTest();  
    	
    	//Comprobamos que se ha puesto el campo a false
    	List<Pricebook2> listaTarifas = [select Pendiente_de_confirmar__c from Pricebook2 where Id =: pb1.Id];
		for(Pricebook2 tarifa : listaTarifas)
		{
			System.assertEquals(tarifa.Pendiente_de_confirmar__c,false);
		}
		
		System.assertEquals(listaTarifas.size(),1);
	}


}