force-app/main/default/objects/TankMaintenanceCost__c/TankMaintenanceCost__c.object-meta.xml
<CustomObject>
    <description>Costes de mantenimiento según la provincia de instalación del depósito.</description>
    <label>Coste de Mantenimiento de Depósito</label>
    <nameField>
        <displayFormat>TMC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coste de Mantenimiento de Depósito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMaintenanceCost__c/fields/Tank__c.field-meta.xml
<CustomField>
    <fullName>Tank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maestro de depósito</label>
    <referenceTo>TankMasterData__c</referenceTo>
    <relationshipName>TankMaintenanceCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/TankMasterData__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los campos con información sobre las opciones y costes de instalación de los depósitos de gas.</description>
    <label>Maestro de Depósito</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestro de Depósitos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMasterData__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Coste del depósito</description>
    <label>Coste</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CPQ_TankMaintenanceCostSelector.cls
public with sharing class CPQ_TankMaintenanceCostSelector {
   
    public static List<TankMaintenanceCost__c> selectByCountyAndName(Set<String> counties, Set<String> names){
        CPQ_LogUtil.debug('*SELECTOR* [CPQ_TankMaintenanceCostSelector] selectByCountyAndName');
        return [SELECT Id,
                       Cost__c,
                       County__c,
                       Tank__r.Name
                FROM TankMaintenanceCost__c
                WHERE County__c IN : counties
                  AND Tank__r.Name IN : names];
    }
}