force-app/main/default/objects/Energia_Actual__c/Energia_Actual__c.object-meta.xml
<CustomObject>
    <description>Representa la información acerca de las energías actuales de un candidato.</description>
    <label>Energía Actual - Usos del Gas</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energías Actuales - Usos del Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Energia_Actual__c/fields/Consumo__c.field-meta.xml
<CustomField>
    <fullName>Consumo__c</fullName>
    <label>Consumo</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Energia_Actual__c/fields/Consumo_Kg_Primagas__c.field-meta.xml
<CustomField>
    <fullName>Consumo_Kg_Primagas__c</fullName>
    <label>Consumo Kg Primagas</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Energia_Actual__c/fields/Consumo_KgCO2__c.field-meta.xml
<CustomField>
    <fullName>Consumo_KgCO2__c</fullName>
    <label>Consumo KgCO2</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Energia_Actual__c/fields/Consumo_KgCO2_Primagas__c.field-meta.xml
<CustomField>
    <fullName>Consumo_KgCO2_Primagas__c</fullName>
    <label>Consumo KgCO2 Primagas</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Energia_Actual__c/fields/Consumo_KWH__c.field-meta.xml
<CustomField>
    <fullName>Consumo_KWH__c</fullName>
    <label>Consumo KWH</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Energia_Actual__c/fields/Consumo_KWH_Primagas__c.field-meta.xml
<CustomField>
    <fullName>Consumo_KWH_Primagas__c</fullName>
    <label>Consumo KWH Primagas</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Energia_Actual__c/fields/Consumo_L_Primagas__c.field-meta.xml
<CustomField>
    <fullName>Consumo_L_Primagas__c</fullName>
    <label>Consumo L Primagas</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Energia_Actual__c/fields/Tipo_energia__c.field-meta.xml
<CustomField>
    <fullName>Tipo_energia__c</fullName>
    <label>Tipo energía</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Biomasa</fullName>
            </value>
            <value>
                <fullName>Butano</fullName>
            </value>
            <value>
                <fullName>Carbón</fullName>
            </value>
            <value>
                <fullName>Electricidad</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Gas Natural</fullName>
            </value>
            <value>
                <fullName>Gasóleo</fullName>
            </value>
            <value>
                <fullName>GNL</fullName>
            </value>
            <value>
                <fullName>Madera / Leña</fullName>
            </value>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>Otra</fullName>
            </value>
            <value>
                <fullName>Propano Botellas</fullName>
            </value>
            <value>
                <fullName>Propano Granel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpcionesOfertaSTD__c/OpcionesOfertaSTD__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>OpcionesOfertaSTD</label>
</CustomObject>

force-app/main/default/objects/OpcionesOfertaSTD__c/fields/Resolucion_anticipada__c.field-meta.xml
<CustomField>
    <fullName>Resolucion_anticipada__c</fullName>
    <description>Resolución anticipada</description>
    <label>Resolución anticipada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Consumo_contratado_kg__c.field-meta.xml
<CustomField>
    <fullName>Consumo_contratado_kg__c</fullName>
    <label>Consumo contratado kg</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Consumo_contratado_L__c.field-meta.xml
<CustomField>
    <fullName>Consumo_contratado_L__c</fullName>
    <label>Consumo contratado L</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Diferencia_importes_totales__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_importes_totales__c</fullName>
    <label>Diferencia importes totales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Diferencia_kgCO2__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_kgCO2__c</fullName>
    <label>Diferencia kgCO2</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Diferencia_kWh__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_kWh__c</fullName>
    <label>Diferencia kWh</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Dto_Estandar__c.field-meta.xml
<CustomField>
    <fullName>Dto_Estandar__c</fullName>
    <label>Dto Estándar</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Duracion_contratado__c.field-meta.xml
<CustomField>
    <fullName>Duracion_contratado__c</fullName>
    <label>Duración contratado</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Duracion_descuento__c.field-meta.xml
<CustomField>
    <fullName>Duracion_descuento__c</fullName>
    <label>Duración descuento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Enviar_email__c.field-meta.xml
<CustomField>
    <fullName>Enviar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Exterior_estandar__c.field-meta.xml
<CustomField>
    <fullName>Exterior_estandar__c</fullName>
    <label>Exterior estándar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fecha_vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia__c</fullName>
    <label>Fecha vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Importe_total__c.field-meta.xml
<CustomField>
    <fullName>Importe_total__c</fullName>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Importe_total_primagas__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_primagas__c</fullName>
    <label>Importe total Primagas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Interior_estandar__c.field-meta.xml
<CustomField>
    <fullName>Interior_estandar__c</fullName>
    <label>Interior estándar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Kg__c.field-meta.xml
<CustomField>
    <fullName>Kg__c</fullName>
    <label>Kg</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/KgCO2__c.field-meta.xml
<CustomField>
    <fullName>KgCO2__c</fullName>
    <label>KgCO2</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/KgCO2_Primagas__c.field-meta.xml
<CustomField>
    <fullName>KgCO2_Primagas__c</fullName>
    <label>KgCO2 Primagas</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/KWh__c.field-meta.xml
<CustomField>
    <fullName>KWh__c</fullName>
    <label>KWh</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/KWh_Primagas__c.field-meta.xml
<CustomField>
    <fullName>KWh_Primagas__c</fullName>
    <label>KWh Primagas</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Litros__c.field-meta.xml
<CustomField>
    <fullName>Litros__c</fullName>
    <label>Litros</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Pago_inicial__c.field-meta.xml
<CustomField>
    <fullName>Pago_inicial__c</fullName>
    <label>Pago inicial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Precio_fecha__c.field-meta.xml
<CustomField>
    <fullName>Precio_fecha__c</fullName>
    <label>Precio fecha</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Precio_Kg__c.field-meta.xml
<CustomField>
    <fullName>Precio_Kg__c</fullName>
    <label>Precio Kg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Precio_L__c.field-meta.xml
<CustomField>
    <fullName>Precio_L__c</fullName>
    <label>Precio L</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_ahorro_anual__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_ahorro_anual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades ahorro anual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_comodidad__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_comodidad__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades comodidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_despreocuparse__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_despreocuparse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades despreocuparse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_enterrado__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_enterrado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades enterrado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_impacto__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_impacto__c</fullName>
    <label>Prioridades impacto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Impacto alto</fullName>
            </value>
            <value>
                <fullName>Impacto bajo</fullName>
            </value>
            <value>
                <fullName>Impacto medio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_pagar_consumo__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_pagar_consumo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades pagar consumo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_precio_fijo__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_precio_fijo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades precio fijo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_precio_regulado__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_precio_regulado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades precio regulado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_tarifa_plana__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_tarifa_plana__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades tarifa plana</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Resolucion_anticipada__c.field-meta.xml
<CustomField>
    <fullName>Resolucion_anticipada__c</fullName>
    <label>Resolución anticipada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Servicio_estandar__c.field-meta.xml
<CustomField>
    <fullName>Servicio_estandar__c</fullName>
    <label>Servicio estándar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Tarifa_estandar__c.field-meta.xml
<CustomField>
    <fullName>Tarifa_estandar__c</fullName>
    <label>Tarifa estándar</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Texto_servicio_estandar__c.field-meta.xml
<CustomField>
    <fullName>Texto_servicio_estandar__c</fullName>
    <label>Texto servicio estándar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Valor_del_servicio_estandar__c.field-meta.xml
<CustomField>
    <fullName>Valor_del_servicio_estandar__c</fullName>
    <label>Valor del servicio estándar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Oferta_estandar.recordType-meta.xml
<RecordType>
    <fullName>Oferta_estandar</fullName>
    <active>true</active>
    <label>Oferta estándar</label>
</RecordType>

force-app/main/default/classes/TEST_OfertaEstandarPDFController.cls
@isTest
private class TEST_OfertaEstandarPDFController
{
	//Método para dar cobertura
        @isTest
	static void TEST_OfertaEstandarPDFController()
	{
		Account a = new Account();
                a.Name = 'EMPRESA';
                a.ShippingCity = 'Test';
                a.ShippingState = 'Test';
                insert a;

		Opportunity op = new Opportunity();
                op.Name ='OpTest';
                op.StageName = 'Identificada';
                op.CloseDate = Date.today();
                op.AccountId = a.Id;
                insert op;

		Quote qE = new Quote();
                qE.Name = 'OfETest';
                qE.Status = 'Preparando';
                qE.RecordTypeId = Util.objectsRecordTypesMap.get('Quote').get('Oferta_estandar').Id;
                qE.OpportunityId = op.Id;
                qE.Fecha_vigencia__c = Date.today().addYears(1);
                qE.Observaciones__c = 'ObservacionesQE';
                qE.Enviar_email__c = true;
                qE.Resolucion_anticipada__c = 1202;
                qE.Prioridades_comodidad__c = true;
                qE.Prioridades_despreocuparse__c = false;
                qE.Prioridades_enterrado__c = true;
                qE.Prioridades_ahorro_anual__c = false;
                qE.Prioridades_precio_regulado__c = true;
                qE.Prioridades_pagar_consumo__c = false;
                qE.Prioridades_precio_fijo__c = true;
                qE.Prioridades_tarifa_plana__c = false;
                qE.Prioridades_impacto__c = 'Impacto bajo';
                qE.Kg__c = 1;
                qE.KWh__c = 2;
                qE.Litros__c = 3;
                qE.KgCO2__c = 4;
                qE.KgCO2_Primagas__c = 5;
                qE.KWh_Primagas__c = 11;
                qE.Diferencia_kgCO2__c = 12;
                qE.Diferencia_kWh__c = 13;
                qE.Interior_estandar__c = 'IntEstandarTest';
                qE.Exterior_estandar__c = 'ExtEstandarTest';
                qE.Servicio_estandar__c = 'ServEstandarTest';
                qE.Tarifa_estandar__c = 'TARIFA_TEST';
                qE.Precio_L__c = 7;
                qE.Precio_Kg__c = 8;
                qE.Valor_del_servicio_estandar__c = 9;
                qE.Importe_total_primagas__c = 14;
                qE.Importe_total__c = 15;
                qE.Diferencia_importes_totales__c = 16;
                qE.Pago_inicial__c = 17;
                qE.Duracion_descuento__c = '18 AÑOS';
                qE.Consumo_contratado_kg__c = 19;
                qE.Consumo_contratado_L__c = 20;
                qE.Duracion_contratado__c = '21 AÑOS';
                qE.Dto_Estandar__c = 22;
                qE.Texto_servicio_estandar__c = 'Texto opción servicio seleccionado';
                qE.Precio_fecha__c = 'Precio SEP';
                insert qE;

                Energia_Actual__c energia = new Energia_Actual__c();
                energia.Consumo__c = 100;
                energia.Consumo_KgCO2__c = 300;
                energia.Consumo_KgCO2_Primagas__c = 400;
                energia.Consumo_Kg_Primagas__c = 100;
                energia.Consumo_KWH__c = 100;
                energia.Consumo_KWH_Primagas__c = 200;
                energia.Consumo_L_Primagas__c = 100;
                energia.Tipo_energia__c = 'Butano';
                energia.Unidad_consumo__c = 'Kg/año';
                energia.Presupuesto__c = qE.Id;
                insert energia;

                EnergiaUnidades__c energiaUnidad = new EnergiaUnidades__c();
                energiaUnidad.Name ='energiaUnidadKgAnio';
                energiaUnidad.UnidadConsumo__c = 'Kg/año';
                energiaUnidad.Abreviatura_unidad_consumo__c = 'kg';
                insert energiaUnidad;



                Test.startTest();

                PageReference pagePDF = Page.OfertaEstandarPDF;
		pagePDF.getParameters().put('idOferta', qE.Id);
		Test.setCurrentPage(pagePDF);

		OfertaEstandarPDFController controller = new OfertaEstandarPDFController();
		system.assertEquals(1, controller.numTotalEnergias);

		Test.stopTest();
	}

        @isTest
        static void TEST_OfertaEstandarPDFController2()
        {
                Account a = new Account();
                a.Name = 'EMPRESA';
                insert a;

                Opportunity op = new Opportunity();
                op.Name ='OpTest';
                op.StageName = 'Identificada';
                op.CloseDate = Date.today();
                op.AccountId = a.Id;
                insert op;

                Quote qE = new Quote();
                qE.Name = 'OfETest';
                qE.Status = 'Preparando';
                qE.RecordTypeId = Util.objectsRecordTypesMap.get('Quote').get('Oferta_estandar').Id;
                qE.OpportunityId = op.Id;
                qE.Fecha_vigencia__c = Date.today().addYears(1);
                qE.Observaciones__c = '';
                qE.Enviar_email__c = true;
                qE.Resolucion_anticipada__c = 1202;
                qE.Prioridades_comodidad__c = true;
                qE.Prioridades_despreocuparse__c = false;
                qE.Prioridades_enterrado__c = true;
                qE.Prioridades_ahorro_anual__c = false;
                qE.Prioridades_precio_regulado__c = true;
                qE.Prioridades_pagar_consumo__c = false;
                qE.Prioridades_precio_fijo__c = true;
                qE.Prioridades_tarifa_plana__c = false;
                qE.Prioridades_impacto__c = 'Impacto bajo';
                qE.Kg__c = 1;
                qE.KWh__c = 2;
                qE.Litros__c = 3;
                qE.KgCO2__c = 4;
                qE.KgCO2_Primagas__c = 5;
                qE.KWh_Primagas__c = 11;
                qE.Diferencia_kgCO2__c = 12;
                qE.Diferencia_kWh__c = 13;
                qE.Interior_estandar__c = 'IntEstandarTest';
                qE.Exterior_estandar__c = 'ExtEstandarTest';
                qE.Servicio_estandar__c = 'ServEstandarTest';
                qE.Tarifa_estandar__c = 'TARIFA_TEST';
                qE.Precio_L__c = 7;
                qE.Precio_Kg__c = 8;
                qE.Valor_del_servicio_estandar__c = 9;
                qE.Importe_total_primagas__c = 14;
                qE.Importe_total__c = 15;
                qE.Diferencia_importes_totales__c = 16;
                qE.Pago_inicial__c = 17;
                qE.Duracion_descuento__c = '18 AÑOS';
                qE.Consumo_contratado_kg__c = 19;
                qE.Consumo_contratado_L__c = 20;
                qE.Duracion_contratado__c = '21 AÑOS';
                qE.Dto_Estandar__c = 22;
                qE.Texto_servicio_estandar__c = 'Texto opción servicio seleccionado';
                qE.Precio_fecha__c = 'Precio SEP';
                insert qE;

                Energia_Actual__c energia = new Energia_Actual__c();
                energia.Consumo__c = 100;
                energia.Consumo_KgCO2__c = 100;
                energia.Consumo_KgCO2_Primagas__c = 100;
                energia.Consumo_Kg_Primagas__c = 100;
                energia.Consumo_KWH__c = 100;
                energia.Consumo_KWH_Primagas__c = 100;
                energia.Consumo_L_Primagas__c = 100;
                energia.Tipo_energia__c = 'Butano';
                energia.Unidad_consumo__c = 'Kg/año';
                energia.Presupuesto__c = qE.Id;
                insert energia;

                EnergiaUnidades__c energiaUnidad = new EnergiaUnidades__c();
                energiaUnidad.Name ='energiaUnidadKgAnio';
                energiaUnidad.UnidadConsumo__c = 'Kg/año';
                energiaUnidad.Abreviatura_unidad_consumo__c = 'kg';
                insert energiaUnidad;

                

                Test.startTest();

                PageReference pagePDF = Page.OfertaEstandarPDF;
                pagePDF.getParameters().put('idOferta', qE.Id);
                Test.setCurrentPage(pagePDF);

                OfertaEstandarPDFController controller = new OfertaEstandarPDFController();
                system.assertEquals(1, controller.numTotalEnergias);

                Test.stopTest();
        }

        @isTest
        static void TEST_OfertaEstandarPDFController3()
        {
                Account a = new Account();
                a.Name = 'EMPRESA';
                insert a;

                Opportunity op = new Opportunity();
                op.Name ='OpTest';
                op.StageName = 'Identificada';
                op.CloseDate = Date.today();
                op.AccountId = a.Id;
                insert op;

                Quote qE = new Quote();
                qE.Name = 'OfETest';
                qE.Status = 'Preparando';
                qE.RecordTypeId = Util.objectsRecordTypesMap.get('Quote').get('Oferta_estandar').Id;
                qE.OpportunityId = op.Id;
                qE.Fecha_vigencia__c = Date.today().addYears(1);
                qE.Observaciones__c = '';
                qE.Enviar_email__c = true;
                qE.Resolucion_anticipada__c = 1202;
                qE.Prioridades_comodidad__c = true;
                qE.Prioridades_despreocuparse__c = false;
                qE.Prioridades_enterrado__c = true;
                qE.Prioridades_ahorro_anual__c = false;
                qE.Prioridades_precio_regulado__c = true;
                qE.Prioridades_pagar_consumo__c = false;
                qE.Prioridades_precio_fijo__c = true;
                qE.Prioridades_tarifa_plana__c = false;
                qE.Prioridades_impacto__c = 'Impacto bajo';
                qE.Kg__c = 1;
                qE.KWh__c = 2;
                qE.Litros__c = 3;
                qE.KgCO2__c = 4;
                qE.KgCO2_Primagas__c = 5;
                qE.KWh_Primagas__c = 11;
                qE.Diferencia_kgCO2__c = 12;
                qE.Diferencia_kWh__c = 13;
                qE.Interior_estandar__c = 'IntEstandarTest';
                qE.Exterior_estandar__c = 'ExtEstandarTest';
                qE.Servicio_estandar__c = 'ServEstandarTest';
                qE.Tarifa_estandar__c = 'TARIFA_TEST';
                qE.Precio_L__c = 7;
                qE.Precio_Kg__c = 8;
                qE.Valor_del_servicio_estandar__c = 9;
                qE.Importe_total_primagas__c = 14;
                qE.Importe_total__c = 15;
                qE.Diferencia_importes_totales__c = 16;
                qE.Pago_inicial__c = 17;
                qE.Duracion_descuento__c = '18 AÑOS';
                qE.Consumo_contratado_kg__c = 19;
                qE.Consumo_contratado_L__c = 20;
                qE.Duracion_contratado__c = '21 AÑOS';
                qE.Dto_Estandar__c = 22;
                qE.Texto_servicio_estandar__c = 'Texto opción servicio seleccionado';
                qE.Precio_fecha__c = 'Precio SEP';
                insert qE;

                insert new OpcionesOfertaSTD__c(Name = 'OfertaSTD112', Oferta__c = 'OfertaSTD112',OpcInterior__c = 'No incluido', OpcExterior__c = 'Depósito Aéreo', OpcServicio__c = 'Telemedida');


                Test.startTest();

                PageReference pagePDF = Page.OfertaEstandarPDF;
                pagePDF.getParameters().put('idOferta', qE.Id);
                Test.setCurrentPage(pagePDF);

                OfertaEstandarPDFController controller = new OfertaEstandarPDFController();
                system.assertEquals(0, controller.numTotalEnergias);

                Test.stopTest();
        }

        @isTest
        static void TEST_OfertaEstandarPDFController4()
        {
                Account a = new Account();
                a.Name = 'EMPRESA';
                insert a;

                Opportunity op = new Opportunity();
                op.Name ='OpTest';
                op.StageName = 'Identificada';
                op.CloseDate = Date.today();
                op.AccountId = a.Id;
                insert op;

                Quote qE = new Quote();
                qE.Name = 'OfETest';
                qE.Status = 'Preparando';
                qE.RecordTypeId = Util.objectsRecordTypesMap.get('Quote').get('Oferta_estandar').Id;
                qE.OpportunityId = op.Id;
                qE.Fecha_vigencia__c = Date.today().addYears(1);
                qE.Observaciones__c = '';
                qE.Enviar_email__c = true;
                qE.Resolucion_anticipada__c = 1202;
                qE.Prioridades_comodidad__c = true;
                qE.Prioridades_despreocuparse__c = false;
                qE.Prioridades_enterrado__c = true;
                qE.Prioridades_ahorro_anual__c = false;
                qE.Prioridades_precio_regulado__c = true;
                qE.Prioridades_pagar_consumo__c = false;
                qE.Prioridades_precio_fijo__c = true;
                qE.Prioridades_tarifa_plana__c = false;
                qE.Prioridades_impacto__c = 'Impacto bajo';
                qE.Kg__c = 1;
                qE.KWh__c = 2;
                qE.Litros__c = 3;
                qE.KgCO2__c = 4;
                qE.KgCO2_Primagas__c = 5;
                qE.KWh_Primagas__c = 11;
                qE.Diferencia_kgCO2__c = 12;
                qE.Diferencia_kWh__c = 13;
                qE.Interior_estandar__c = 'IntEstandarTest';
                qE.Exterior_estandar__c = 'ExtEstandarTest';
                qE.Servicio_estandar__c = 'ServEstandarTest';
                qE.Tarifa_estandar__c = 'TARIFA_TEST';
                qE.Precio_L__c = 7;
                qE.Precio_Kg__c = 8;
                qE.Valor_del_servicio_estandar__c = 9;
                qE.Importe_total_primagas__c = 0;
                qE.Importe_total__c = 0;
                qE.Diferencia_importes_totales__c = 16;
                qE.Pago_inicial__c = 0;
                qE.Duracion_descuento__c = '18 AÑOS';
                qE.Consumo_contratado_kg__c = 19;
                qE.Consumo_contratado_L__c = 20;
                qE.Duracion_contratado__c = '21 AÑOS';
                qE.Dto_Estandar__c = 22;
                qE.Texto_servicio_estandar__c = 'Texto opción servicio seleccionado';
                qE.Precio_fecha__c = 'Precio SEP';
                insert qE;

                insert new OpcionesOfertaSTD__c(Name = 'OfertaSTD112', Oferta__c = 'OfertaSTD112',OpcInterior__c = 'No incluido', OpcExterior__c = 'Depósito Aéreo', OpcServicio__c = 'Telemedida');


                Test.startTest();

                PageReference pagePDF = Page.OfertaEstandarPDF;
                pagePDF.getParameters().put('idOferta', qE.Id);
                Test.setCurrentPage(pagePDF);

                OfertaEstandarPDFController controller = new OfertaEstandarPDFController();
                system.assertEquals(0, controller.numTotalEnergias);

                Test.stopTest();
        }
}