force-app/main/default/objects/SBQQ__QuoteLine__c/fields/TankName__c.field-meta.xml
<CustomField>
    <fullName>TankName__c</fullName>
    <description>Modelo</description>
    <label>Modelo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TankMaintenanceCost__c/TankMaintenanceCost__c.object-meta.xml
<CustomObject>
    <description>Costes de mantenimiento según la provincia de instalación del depósito.</description>
    <label>Coste de Mantenimiento de Depósito</label>
    <nameField>
        <displayFormat>TMC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coste de Mantenimiento de Depósito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMaintenanceCost__c/fields/Tank__c.field-meta.xml
<CustomField>
    <fullName>Tank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maestro de depósito</label>
    <referenceTo>TankMasterData__c</referenceTo>
    <relationshipName>TankMaintenanceCosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/TankMasterData__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los campos con información sobre las opciones y costes de instalación de los depósitos de gas.</description>
    <label>Maestro de Depósito</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestro de Depósitos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMasterData__c/fields/TankName__c.field-meta.xml
<CustomField>
    <fullName>TankName__c</fullName>
    <description>Modelo de depósito</description>
    <label>Tank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPQ_TankMaintenanceCost.cls
public with sharing class CPQ_TankMaintenanceCost {
    
    public static TMCByCounty getTMCForQuoteWrappers(CPQ_Quote.QuoteWrapper quoteWrappers){
        return getTMCForQuoteWrappers(new List<CPQ_Quote.QuoteWrapper>{quoteWrappers});
    }

    public static TMCByCounty getTMCForQuoteWrappers(List<CPQ_Quote.QuoteWrapper> quoteWrappers){
        // 1.- Find gas cost records related to the quotes:
        Set<String> counties = new Set<String>();
        Set<String> tankNames = new Set<String>();

        for(CPQ_Quote.QuoteWrapper w : quoteWrappers){
            counties.add(w.Quote.County__c);
            for(SBQQ__QuoteLine__c l : w.getLinesByProductCode(CPQ_ProductCodes.DEPOSITO)){
                if(string.isNotBlank(l.TankName__c)){
                    tankNames.add(l.TankName__c);
                }
            }
        }

        return new TMCByCounty(CPQ_TankMaintenanceCostSelector.selectByCountyAndName(counties, tankNames));
    }

    public class TMCByCounty {
        //      Map<County, Map<Name, List<TankMaintenanceCost__c>>
        private Map<String, Map<String, List<TankMaintenanceCost__c>>> tmcByCountyAndName = new Map<String, Map<String, List<TankMaintenanceCost__c>>>();

        public TMCByCounty(List<TankMaintenanceCost__c> tmcs){
            for(TankMaintenanceCost__c t : tmcs){
                if(!tmcByCountyAndName.containsKey(t.County__c)){
                    tmcByCountyAndName.put(t.County__c, new Map<String, List<TankMaintenanceCost__c>>());
                }
                if(!tmcByCountyAndName.get(t.County__c).containsKey(t.Tank__r.Name)){
                    tmcByCountyAndName.get(t.County__c).put(t.Tank__r.Name, new List<TankMaintenanceCost__c>());
                }
                tmcByCountyAndName.get(t.County__c).get(t.Tank__r.Name).add(t);
            }
        }

        public TankMaintenanceCost__c getFirstForCountyAndTankName(String county, String name){
            if(tmcByCountyAndName.containsKey(county) && tmcByCountyAndName.get(county).containsKey(name)){
                return tmcByCountyAndName.get(county).get(name)[0];
            }
            return null;
        }

    }

}