force-app/main/default/objects/Contract/fields/Contrato_anterior__c.field-meta.xml
<CustomField>
    <fullName>Contrato_anterior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato anterior</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Direccion_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Direccion_de_entrega__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dirección de entrega</label>
    <referenceTo>Direcci_n_de_entrega__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Servicios__c.field-meta.xml
<CustomField>
    <fullName>Servicios__c</fullName>
    <label>Servicios</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALQUILER</fullName>
            </value>
            <value>
                <fullName>MANTENIMIENTO</fullName>
            </value>
            <value>
                <fullName>MTO TELEMEDIDA</fullName>
            </value>
            <value>
                <fullName>NIVELDIST</fullName>
            </value>
            <value>
                <fullName>NIVELDISTINST</fullName>
            </value>
            <value>
                <fullName>NIVELDISTMANT</fullName>
            </value>
            <value>
                <fullName>PRIMACONFORT</fullName>
            </value>
            <value>
                <fullName>PRIMAFACIL</fullName>
            </value>
            <value>
                <fullName>PS CONFORT DOM</fullName>
            </value>
            <value>
                <fullName>PS CONFORT PROF</fullName>
            </value>
            <value>
                <fullName>PS OPTIMO</fullName>
            </value>
            <value>
                <fullName>PZ REV INT</fullName>
            </value>
            <value>
                <fullName>TELEMEDIDA - EQUIPO</fullName>
            </value>
            <value>
                <fullName>TELEMEDIDA - SERVTOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/Direcci_n_de_entrega__c.object-meta.xml
<CustomObject>
    <description>Ship to address</description>
    <label>Dirección de entrega</label>
    <nameField>
        <displayFormat>STA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones de entrega</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/cuenta__c.field-meta.xml
<CustomField>
    <fullName>cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Direcciones de entrega</relationshipLabel>
    <relationshipName>Direcciones_de_entrega</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TEST_RenovarContratoScheduler.cls
@isTest
public class TEST_RenovarContratoScheduler {
	
	static testMethod void RenovarContratoSchedulerTest(){
		System.Debug('## before RenovarContratoSchedulerTest');

		Account cuenta = new Account();
		cuenta.Name = 'Test';
		insert cuenta;

		Direcci_n_de_Entrega__c direccion = new Direcci_n_de_Entrega__c();
		direccion.cuenta__c = cuenta.Id;
		insert direccion;	

		Datetime fechaInicioContrato = System.now();
		fechaInicioContrato = fechaInicioContrato.addDays(-32);

		Contract contrato = new Contract();
		contrato.AccountId = cuenta.Id;
		contrato.StartDate = date.newinstance(fechaInicioContrato.year(), fechaInicioContrato.month(), fechaInicioContrato.day());
		contrato.ContractTerm = 1;
		contrato.Servicios__c = 'Prueba;Test';
		contrato.Direccion_de_entrega__c = direccion.Id;
		insert contrato;

		Test.startTest();
		
		SchedulableContext SC;
		RenovarContratoScheduler j = new RenovarContratoScheduler();
		j.execute(SC);

		Test.stopTest();

		List<Contract> contratos = new List<Contract>([Select Id, Status, Contrato_anterior__c from Contract]);

		System.assertEquals(2, contratos.size());

		Contract contratoNuevo;

		for (Contract c:contratos)
		{
			if (c.Id == contrato.Id)
			{
				contrato = c;
			}
			else
			{
				contratoNuevo = c;
			}
		}

		System.assertEquals(false, contratoNuevo == null);
		System.assertEquals('Anulado', contrato.Status);
		System.assertEquals(contrato.Id, contratoNuevo.Contrato_anterior__c);
		System.assertEquals('Pendiente de registrar', contratoNuevo.Status);

		/*List<Contrato_de_servicio__c> contratosServicio = new List<Contrato_de_servicio__c>([Select Id from Contrato_de_servicio__c]);
		System.assertEquals(4, contratosServicio.size());*/

		update direccion;
		delete contratos;
		delete direccion;

		System.Debug('## after RenovarContratoSchedulerTest');
	}

}