force-app/main/default/objects/Stretch__c/Stretch__c.object-meta.xml
<CustomObject>
    <label>Tramo</label>
    <nameField>
        <label>Nombre del tramo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tramos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stretch__c/fields/CLV10__c.field-meta.xml
<CustomField>
    <fullName>CLV10__c</fullName>
    <label>CLV10</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/CLV5__c.field-meta.xml
<CustomField>
    <fullName>CLV5__c</fullName>
    <label>CLV5</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/DiscountKG__c.field-meta.xml
<CustomField>
    <fullName>DiscountKG__c</fullName>
    <label>Dto. Kg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/DiscountL__c.field-meta.xml
<CustomField>
    <fullName>DiscountL__c</fullName>
    <label>Dto. L</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/FromConsumptionKG__c.field-meta.xml
<CustomField>
    <fullName>FromConsumptionKG__c</fullName>
    <label>Consumo desde Kg</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/FromPercentage__c.field-meta.xml
<CustomField>
    <fullName>FromPercentage__c</fullName>
    <label>Porcentaje desde</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/PBA__c.field-meta.xml
<CustomField>
    <fullName>PBA__c</fullName>
    <label>PBA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/PriceTodayKG__c.field-meta.xml
<CustomField>
    <fullName>PriceTodayKG__c</fullName>
    <label>Precio HOY Kg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/PriceTodayL__c.field-meta.xml
<CustomField>
    <fullName>PriceTodayL__c</fullName>
    <label>Precio HOY L</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/PrimaServiciosA__c.field-meta.xml
<CustomField>
    <fullName>PrimaServiciosA__c</fullName>
    <label>Primaservicios</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Stretches</relationshipLabel>
    <relationshipName>Stretches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CPQ_StretchSelector.cls
public with sharing class CPQ_StretchSelector {
    
    public static List<Stretch__c> selectByQuotesId(Set<Id> quotesId){
        CPQ_LogUtil.debug('*SELECTOR* [CPQ_StretchSelector] selectByQuotesId');
        return [SELECT  Id,
                        Name,
                        Quote__c,
                        FromPercentage__c,
                        FromConsumptionKG__c,
                        DiscountL__c,
                        DiscountKG__c,
                        PriceTodayL__c,
                        PriceTodayKG__c,
                        PrimaServiciosA__c,
                        PBA__c,
                        CLV5__c,
                        CLV10__c
                FROM Stretch__c
                WHERE Quote__c =: quotesId
                ORDER BY FromPercentage__c DESC];
    }
}