force-app/main/default/objects/Stretch__c/Stretch__c.object-meta.xml
<CustomObject>
    <label>Tramo</label>
    <nameField>
        <label>Nombre del tramo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tramos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stretch__c/fields/DiscountKG__c.field-meta.xml
<CustomField>
    <fullName>DiscountKG__c</fullName>
    <label>Dto. Kg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/FromConsumptionKG__c.field-meta.xml
<CustomField>
    <fullName>FromConsumptionKG__c</fullName>
    <label>Consumo desde Kg</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/FromPercentage__c.field-meta.xml
<CustomField>
    <fullName>FromPercentage__c</fullName>
    <label>Porcentaje desde</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/PriceTodayKG__c.field-meta.xml
<CustomField>
    <fullName>PriceTodayKG__c</fullName>
    <label>Precio HOY Kg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/PrimaServiciosA__c.field-meta.xml
<CustomField>
    <fullName>PrimaServiciosA__c</fullName>
    <label>Primaservicios</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Stretches</relationshipLabel>
    <relationshipName>Stretches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CPQ_StretchService.cls
public without sharing class CPQ_StretchService {
 /*
    public static List<Stretch__c> insertDefaultStretchesForQuote(Id quoteId){
        System.debug('[CPQ_StretchService] insertDefaultStretchesForQuote '+quoteId);
        CPQ_Quote.QuoteWrapper quoteWrapper = CPQ_QuoteService.buildWrappersFromQuotesWithQuoteLineItems(
                                                CPQ_QuoteSelector.selectByIdWithQuoteLineItems(new Set<Id>{quoteId}))[0];

        List<Stretch__c> defaultStretches = buildDefaultStretchesForQuote(quoteWrapper, CPQ_TablesDataWrapper.generate(quoteWrapper));
        insert defaultStretches;

        return defaultStretches;
    }*/
    
    public static void deleteStretchesForQuote(Id quoteId){
        delete [SELECT Id FROM Stretch__c WHERE Quote__c =: quoteId];
    }

    public static Map<Id, List<Stretch__c>> getStretchesByQuoteId(Set<Id> quotesId){
        Map<Id, List<Stretch__c>> output = new Map<Id, List<Stretch__c>>();

        for(Stretch__c stretch : CPQ_StretchSelector.selectByQuotesId(quotesId)){
            if(!output.containsKey(stretch.Quote__c)){
                output.put(stretch.Quote__c, new List<Stretch__c>());
            }
            output.get(stretch.Quote__c).add(stretch);
        }
        return output;
    }
    
    public static Stretch__c buildNewStretch(Decimal fromPerc, CPQ_Quote.QuoteWrapper quoteWrapper){
        return new Stretch__c(Quote__c = quoteWrapper.Quote.Id,
                              FromPercentage__c = fromPerc,
                              PriceTodayKG__c = quoteWrapper.PriceTodayKG,
                              FromConsumptionKG__c = quoteWrapper.EstimatedConsumption,
                              DiscountKG__c = quoteWrapper.DiscountEuroKG,
                              PrimaServiciosA__c = quoteWrapper.Primaservicios);
    }

    public static List<Stretch__c> buildDefaultStretchesForQuote(CPQ_Quote.QuoteWrapper quoteWrapper,
                                                                CPQ_TablesDataWrapper tablesData){

        Decimal discount = CPQ_AggregateUtil.convertToZeroIfNull(quoteWrapper.getFirstLineByProductCode(CPQ_ProductCodes.DESCTARIFA)?.SBQQ__NetPrice__c);
        Decimal primaservicios = quoteWrapper.Primaservicios;

        List<Stretch__c> tramos = new List<Stretch__c>{
            buildNewStretch(120, quoteWrapper),
            buildNewStretch(80, quoteWrapper),
            buildNewStretch(50, quoteWrapper)
        }; 

        for(Stretch__c t : tramos){
            CPQ_Stretch.fillComputedValues(t, quoteWrapper, tablesData, true);
            //CPQ_Stretch.fillSuggestedDiscount(t, quoteWrapper, tablesData);
            CPQ_Stretch.fillMetrics(t, quoteWrapper, tablesData);
        }

        return tramos;
    }

/*
    public static void RefreshStretchFields(StretchWrapper stretch){
        stretch.PBA = CPQ_PBAService.calculate();
        stretch.CLV5 = ((Decimal)Math.round(Math.random() * 1000000))/100;
        stretch.CLV10 = ((Decimal)Math.round(Math.random() * 1000000))/100;
    }*/

}