force-app/main/default/objects/Deposito__c/Deposito__c.object-meta.xml
<CustomObject>
    <label>Depósito</label>
    <nameField>
        <label>Nombre del depósito</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depósitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposito__c/fields/Instalacion_exterior__c.field-meta.xml
<CustomField>
    <fullName>Instalacion_exterior__c</fullName>
    <label>Instalación exterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deposito__c/fields/Proyectos__c.field-meta.xml
<CustomField>
    <fullName>Proyectos__c</fullName>
    <label>Proyectos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Energia_Actual__c/Energia_Actual__c.object-meta.xml
<CustomObject>
    <description>Representa la información acerca de las energías actuales de un candidato.</description>
    <label>Energía Actual - Usos del Gas</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energías Actuales - Usos del Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Energia_Actual__c/fields/Consumo__c.field-meta.xml
<CustomField>
    <fullName>Consumo__c</fullName>
    <label>Consumo</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipo_Ajuste__c/Equipo_Ajuste__c.object-meta.xml
<CustomObject>
    <label>Equipo Ajuste</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipos Ajuste</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipo_Ajuste__c/fields/Equipos_exterior__c.field-meta.xml
<CustomField>
    <fullName>Equipos_exterior__c</fullName>
    <label>Equipos exterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Cuota_inversion__c.field-meta.xml
<CustomField>
    <fullName>Cuota_inversion__c</fullName>
    <label>Cuota inversión</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Diferencia_importes_totales__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_importes_totales__c</fullName>
    <label>Diferencia importes totales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Diferencia_kgCO2__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_kgCO2__c</fullName>
    <label>Diferencia kgCO2</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Diferencia_kWh__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_kWh__c</fullName>
    <label>Diferencia kWh</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Dto_1_Llenado_inversion__c.field-meta.xml
<CustomField>
    <fullName>Dto_1_Llenado_inversion__c</fullName>
    <label>Dto. 1 Llenado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Dto_Producto_gas__c.field-meta.xml
<CustomField>
    <fullName>Dto_Producto_gas__c</fullName>
    <label>Dto. Producto gas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Duracion_cuota_inversion__c.field-meta.xml
<CustomField>
    <fullName>Duracion_cuota_inversion__c</fullName>
    <label>Duración cuota inversión</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Duracion_descuento__c.field-meta.xml
<CustomField>
    <fullName>Duracion_descuento__c</fullName>
    <label>Duración descuento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Enviar_email__c.field-meta.xml
<CustomField>
    <fullName>Enviar_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviar email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fecha_vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia__c</fullName>
    <label>Fecha vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Importe_total__c.field-meta.xml
<CustomField>
    <fullName>Importe_total__c</fullName>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Importe_total_primagas__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_primagas__c</fullName>
    <label>Importe total Primagas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Inspeccion_interior_primaservicios__c.field-meta.xml
<CustomField>
    <fullName>Inspeccion_interior_primaservicios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspección interior</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Kg__c.field-meta.xml
<CustomField>
    <fullName>Kg__c</fullName>
    <label>Kg</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/KgCO2__c.field-meta.xml
<CustomField>
    <fullName>KgCO2__c</fullName>
    <label>KgCO2</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/KgCO2_Primagas__c.field-meta.xml
<CustomField>
    <fullName>KgCO2_Primagas__c</fullName>
    <label>KgCO2 Primagas</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/KWh__c.field-meta.xml
<CustomField>
    <fullName>KWh__c</fullName>
    <label>KWh</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/KWh_Primagas__c.field-meta.xml
<CustomField>
    <fullName>KWh_Primagas__c</fullName>
    <label>KWh Primagas</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Litros__c.field-meta.xml
<CustomField>
    <fullName>Litros__c</fullName>
    <label>Litros</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Mantenimiento_primaservicios__c.field-meta.xml
<CustomField>
    <fullName>Mantenimiento_primaservicios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mantenimiento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Pago_inicial_inversion__c.field-meta.xml
<CustomField>
    <fullName>Pago_inicial_inversion__c</fullName>
    <label>Pago inicial inversión</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Precio_Primaservicios__c.field-meta.xml
<CustomField>
    <fullName>Precio_Primaservicios__c</fullName>
    <label>Precio Primaservicios</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Precio_producto_gas__c.field-meta.xml
<CustomField>
    <fullName>Precio_producto_gas__c</fullName>
    <label>Precio producto gas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_ahorro_anual__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_ahorro_anual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades ahorro anual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_comodidad__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_comodidad__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades comodidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_despreocuparse__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_despreocuparse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades despreocuparse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_enterrado__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_enterrado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades enterrado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_impacto__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_impacto__c</fullName>
    <label>Prioridades impacto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Impacto alto</fullName>
            </value>
            <value>
                <fullName>Impacto bajo</fullName>
            </value>
            <value>
                <fullName>Impacto medio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_pagar_consumo__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_pagar_consumo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades pagar consumo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_precio_fijo__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_precio_fijo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades precio fijo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_precio_regulado__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_precio_regulado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades precio regulado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prioridades_tarifa_plana__c.field-meta.xml
<CustomField>
    <fullName>Prioridades_tarifa_plana__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prioridades tarifa plana</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Proyectos__c.field-meta.xml
<CustomField>
    <fullName>Proyectos__c</fullName>
    <label>Proyectos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Resolucion_anticipada__c.field-meta.xml
<CustomField>
    <fullName>Resolucion_anticipada__c</fullName>
    <label>Resolución anticipada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Revision_interior_primaservicios__c.field-meta.xml
<CustomField>
    <fullName>Revision_interior_primaservicios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Revisión interior</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Tipo_de_pago_inversion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pago_inversion__c</fullName>
    <label>Tipo de pago inversión</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Tipo_de_tarifa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_tarifa__c</fullName>
    <label>Tipo de tarifa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Tipo_Primaservicios__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Primaservicios__c</fullName>
    <label>Tipo Primaservicios</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Tipo_producto_gas__c.field-meta.xml
<CustomField>
    <fullName>Tipo_producto_gas__c</fullName>
    <label>Tipo de producto gas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Oferta_personalizada.recordType-meta.xml
<RecordType>
    <fullName>Oferta_personalizada</fullName>
    <active>true</active>
    <label>Oferta personalizada</label>
</RecordType>

force-app/main/default/classes/TEST_OfertaPersonalizadaPDFController.cls
@isTest
private class TEST_OfertaPersonalizadaPDFController
{
	//Método para dar cobertura
        @isTest
	static void TEST_OfertaPersonalizadaPDFController()
	{
		Account a = new Account();
                a.Name = 'EMPRESA';
                insert a;

        	Opportunity op = new Opportunity();
                op.Name ='OpTest';
                op.StageName = 'Identificada';
                op.CloseDate = Date.today();
                op.AccountId = a.Id;
                insert op;

        	Quote qP = new Quote();
                qP.Name = 'OfPTest';
                qP.Status = 'Preparando';
                qP.RecordTypeId = Util.objectsRecordTypesMap.get('Quote').get('Oferta_personalizada').Id;
                qP.OpportunityId = op.Id;
                qP.Fecha_vigencia__c = Date.today().addYears(1);
                qP.Observaciones__c = 'ObservacionesQP';
                qP.Enviar_email__c = false;
                qP.Resolucion_anticipada__c = 1200;
                qP.Prioridades_comodidad__c = true;
                qP.Prioridades_despreocuparse__c = false;
                qP.Prioridades_enterrado__c = true;
                qP.Prioridades_ahorro_anual__c = false;
                qP.Prioridades_precio_regulado__c = true;
                qP.Prioridades_pagar_consumo__c = false;
                qP.Prioridades_precio_fijo__c = true;
                qP.Prioridades_tarifa_plana__c = false;
                qP.Prioridades_impacto__c = 'Impacto medio';
                qP.Kg__c = 21;
                qP.KWh__c = 22;
                qP.Litros__c = 23;
                qP.KgCO2__c = 24;
                qP.KgCO2_Primagas__c = 25;
                qP.KWh_Primagas__c = 20;
                qP.Diferencia_kgCO2__c = 19;
                qP.Diferencia_kWh__c = 18;
                qP.Tipo_de_tarifa__c = 'TipoTarifaQP';
                qP.Pago_inicial_inversion__c = 41;
                qP.Cuota_inversion__c = 34;
                qP.Duracion_cuota_inversion__c = 35;
                qP.Dto_1_Llenado_inversion__c = 36;
                qP.Importe_total_primagas__c = 14;
                qP.Importe_total__c = 15;
                qP.Diferencia_importes_totales__c = 16;
                qP.Tipo_de_pago_inversion__c = 'Pagotest';
                qP.Tipo_producto_gas__c = 'ProdGasTest';
                qP.Duracion_descuento__c = '50 AÑOS';
                qP.Dto_Producto_gas__c = 51;
                qP.Precio_producto_gas__c = 52;
                qP.Tipo_Primaservicios__c = 'PrimaservTest';
                qP.Mantenimiento_primaservicios__c = true;
                qP.Inspeccion_interior_primaservicios__c = false;
                qP.Revision_interior_primaservicios__c = true;
                qP.Precio_Primaservicios__c = 60;
                insert qP;

                Deposito__c d1P = new Deposito__c();
                d1P.Name = 'DepoTestP1';
                d1P.Cantidad__c = 110;
                d1P.Equipos_exterior__c = 111;
                d1P.Instalacion_exterior__c = 115;
                d1P.Proyectos__c = 113;
                d1P.Obra_civil_vallado__c = 114;
                d1P.Presupuesto__c = qP.Id;
                insert d1P;

                Equipo_ajuste__c eA1P = new Equipo_ajuste__c();
                eA1P.Name = 'EATestP1';
                ea1P.Cantidad__c = 9;
                eA1P.Equipos_interior__c = 11;
                eA1P.Equipos_exterior__c = 12;
                eA1P.Instalacion_exterior__c = 14;
                eA1P.Instalacion_interior__c = 13;
                eA1P.Presupuesto__c = qP.Id;
                insert eA1P;

                Pack__c p = new Pack__c();
                p.Name = 'PackTest1';
                p.Numero_de_pack__c = 1;
                p.Nombre__c = 'Pack test 1';
                p.ConsumoMax__c = 10;
                p.Activo__c = true;
                p.ImporteMensual__c = 11;
                insert p;

                ServiciosPacks__c sp = new ServiciosPacks__c();
                sp.Name = 'ServPackTest1';
                sp.Incluido__c = true;
                sp.Nombre__c = 'Servicio Test 1';
                sp.Numero_de_pack__c = 1;
                insert sp;

                Pack_de_servicio__c ps = new Pack_de_servicio__c();
                ps.Consumo_maximo__c = 10;
                ps.Importe_mensual__c = 11;
                ps.Numero_de_pack__c = 1;
                ps.Name_Pack_maestros__c = p.Name;
                ps.Presupuesto__c = qP.Id;
                ps.Total_importe__c = 12;
                insert ps;

                Servicio__c s = new Servicio__c();
                s.Incluido__c = true;
                s.Name_Servicio_pack_maestro__c = sp.Name;
                s.Pack_de_servicio__c = ps.Id;
                insert s;

                Energia_Actual__c energia = new Energia_Actual__c();
                energia.Consumo__c = 100;
                energia.Consumo_KgCO2__c = 100;
                energia.Consumo_KgCO2_Primagas__c = 100;
                energia.Consumo_Kg_Primagas__c = 100;
                energia.Consumo_KWH__c = 100;
                energia.Consumo_KWH_Primagas__c = 100;
                energia.Consumo_L_Primagas__c = 100;
                energia.Tipo_energia__c = 'Butano';
                energia.Unidad_consumo__c = 'Kg/año';
                energia.Presupuesto__c = qP.Id;
                insert energia;

                EnergiaUnidades__c energiaUnidad = new EnergiaUnidades__c();
                energiaUnidad.Name ='energiaUnidadKgAnio';
                energiaUnidad.UnidadConsumo__c = 'Kg/año';
                energiaUnidad.Abreviatura_unidad_consumo__c = 'kg';
                insert energiaUnidad;

                Test.startTest();

                PageReference pagePDF = Page.OfertaPersonalizadaPDF;
		pagePDF.getParameters().put('idOferta', qP.Id);
		Test.setCurrentPage(pagePDF);

		OfertaPersonalizadaPDFController controller = new OfertaPersonalizadaPDFController();
		system.assertEquals(1, controller.numTotalEnergias);

		Test.stopTest();
	}
}