force-app/main/default/objects/CPQ_Settings__mdt/CPQ_Settings__mdt.object-meta.xml
<CustomObject>
    <label>CPQ Setting</label>
    <pluralLabel>CPQ Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DefaultPBAEstimatedConsPerc__c.field-meta.xml
<CustomField>
    <fullName>DefaultPBAEstimatedConsPerc__c</fullName>
    <label>% cons. estimado PBA por defecto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DepRate10Years__c.field-meta.xml
<CustomField>
    <fullName>DepRate10Years__c</fullName>
    <label>Factor Dep. 10años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DepRate5Years__c.field-meta.xml
<CustomField>
    <fullName>DepRate5Years__c</fullName>
    <label>Factor Dep. 5años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DepYears__c.field-meta.xml
<CustomField>
    <fullName>DepYears__c</fullName>
    <label>Años Dep.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DiscountRatePercentage__c.field-meta.xml
<CustomField>
    <fullName>DiscountRatePercentage__c</fullName>
    <label>% tasa descuento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/LogsEnabled__c.field-meta.xml
<CustomField>
    <fullName>LogsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, extended logs information is shown for the metrics calculations.</description>
    <inlineHelpText>If true, extended logs information is shown for the metrics calculations.</inlineHelpText>
    <label>LogsEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/MaxSuggestedDiscountIterations__c.field-meta.xml
<CustomField>
    <fullName>MaxSuggestedDiscountIterations__c</fullName>
    <label>Núm. máximo iter. cálc. descuento</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Sandbox__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Sandbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/SuggestDiscountOnOpenStretchManager__c.field-meta.xml
<CustomField>
    <fullName>SuggestDiscountOnOpenStretchManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sugerir descuento al abrir tramos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/SuggestedDiscountIterationIncrement__c.field-meta.xml
<CustomField>
    <fullName>SuggestedDiscountIterationIncrement__c</fullName>
    <defaultValue>0.05</defaultValue>
    <label>Increm. iteración desc. recomendado</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CPQ_Settings.cls
public without sharing class CPQ_Settings {
    private static CPQ_Settings__mdt setting;

    private static CPQ_Settings__mdt settings {
        get {
            if (setting == null) {
                try {
                    setting = [
                        SELECT
                            Id,
                            DiscountRatePercentage__c,
                            DepRate5Years__c,
                            DepRate10Years__c,
                            DepYears__c,
                            DefaultPBAEstimatedConsPerc__c,
                            LogsEnabled__c,
                            SuggestDiscountOnOpenStretchManager__c,
                            MaxSuggestedDiscountIterations__c,
                            SuggestedDiscountIterationIncrement__c
                        FROM CPQ_Settings__mdt
                        WHERE Sandbox__c = :runningInASandbox
                    ];
                } catch (QueryException e) {
                    if (e.getMessage().startsWith('List has no rows')) {
                        throw new SettingsNotFoundException(e.getMessage());
                    } else {
                        throw e;
                    }
                }
            }

            return setting;
        }
    }

    public static void setTestSetting(CPQ_Settings__mdt s){
        setting = s;
    }

    public static Boolean runningInASandbox {
        get {
            if (runningInASandbox == null) {
                System.Domain domain = System.DomainParser.parse(URL.getOrgDomainUrl());
                runningInASandbox = domain.getSandboxName() == null ? false : true;
            }
            return runningInASandbox;
        }
        set;
    }

    public static Integer MaxSuggestedDiscountIterations {
        get {
            return (Integer)settings.MaxSuggestedDiscountIterations__c;
        }
    }

    public static Decimal SuggestedDiscountIterationIncrement {
        get {
            return settings.SuggestedDiscountIterationIncrement__c;
        }
    }

    public static Boolean SuggestDiscountOnOpenStretchManager {
        get {
            return settings.SuggestDiscountOnOpenStretchManager__c;
        }
    }

    public static Decimal DefaultPBAEstimatedConsCoef {
        get {
            return settings.DefaultPBAEstimatedConsPerc__c / 100;
        }
    }

    public static Decimal DiscountRateCoef {
        get {
            // Value is '11', returned as '0.11':
            return (Decimal) settings.DiscountRatePercentage__c / 100;
        }
    }

    public static Integer DiscountRate {
        get {
            return (Integer) settings.DiscountRatePercentage__c;
        }
    }

    public static Integer DepYears {
        get {
            return (Integer) settings.DepYears__c;
        }
    }

    public static Decimal DepRate5Years {
        get {
            return settings.DepRate5Years__c;
        }
    }

    public static Decimal DepRate10Years {
        get {
            return settings.DepRate10Years__c;
        }
    }

    public static Boolean AreLogsEnabled {
        get {
            return settings.LogsEnabled__c;
        }
    }

    public class SettingsNotFoundException extends Exception {
    }

    public static Boolean isDMLExceptionSettingNotFound(DMLException e) {
        return e.getMessage().contains('CPQ_Settings.SettingsNotFoundException');
    }
}