force-app/main/default/objects/CPQ_Settings__mdt/CPQ_Settings__mdt.object-meta.xml
<CustomObject>
    <label>CPQ Setting</label>
    <pluralLabel>CPQ Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DefaultPBAEstimatedConsPerc__c.field-meta.xml
<CustomField>
    <fullName>DefaultPBAEstimatedConsPerc__c</fullName>
    <label>% cons. estimado PBA por defecto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DepRate10Years__c.field-meta.xml
<CustomField>
    <fullName>DepRate10Years__c</fullName>
    <label>Factor Dep. 10años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DepRate5Years__c.field-meta.xml
<CustomField>
    <fullName>DepRate5Years__c</fullName>
    <label>Factor Dep. 5años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DepYears__c.field-meta.xml
<CustomField>
    <fullName>DepYears__c</fullName>
    <label>Años Dep.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DiscountRatePercentage__c.field-meta.xml
<CustomField>
    <fullName>DiscountRatePercentage__c</fullName>
    <label>% tasa descuento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/LogsEnabled__c.field-meta.xml
<CustomField>
    <fullName>LogsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, extended logs information is shown for the metrics calculations.</description>
    <inlineHelpText>If true, extended logs information is shown for the metrics calculations.</inlineHelpText>
    <label>LogsEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EquipmentMasterData__c/EquipmentMasterData__c.object-meta.xml
<CustomObject>
    <description>Coste y características sobre el equipo de la instalación.</description>
    <label>Maestro de Equipo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestros de equipos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EquipmentMasterData__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Coste</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GasCost__c/GasCost__c.object-meta.xml
<CustomObject>
    <label>Coste de Gas</label>
    <nameField>
        <displayFormat>GC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costes de Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GasCost__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Coste</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Alava/Araba</fullName>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Bizkaia/Vizcaya</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Cáceres</fullName>
            </value>
            <value>
                <fullName>Cádiz</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Lleida/Lérida</fullName>
            </value>
            <value>
                <fullName>Lugo</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dimension3__c.field-meta.xml
<CustomField>
    <fullName>Dimension3__c</fullName>
    <label>Dimensión 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1000-DU</fullName>
            </value>
            <value>
                <fullName>1100-CV</fullName>
            </value>
            <value>
                <fullName>1200-AGRI</fullName>
            </value>
            <value>
                <fullName>1300-IND</fullName>
            </value>
            <value>
                <fullName>1400-HRO</fullName>
            </value>
            <value>
                <fullName>1500-COL</fullName>
            </value>
            <value>
                <fullName>1800-PC</fullName>
            </value>
            <value>
                <fullName>1850-PM</fullName>
            </value>
            <value>
                <fullName>1900-FLT</fullName>
            </value>
            <value>
                <fullName>2000-OP</fullName>
            </value>
            <value>
                <fullName>2100-DIGR</fullName>
            </value>
            <value>
                <fullName>2200-DIPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Spot.recordType-meta.xml
<RecordType>
    <fullName>Spot</fullName>
    <active>false</active>
    <businessProcess>Venta Nueva</businessProcess>
    <description>Oportunidad de venta Spot</description>
    <label>Spot</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/fields/ClientTank__c.field-meta.xml
<CustomField>
    <fullName>ClientTank__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tanque Propio del Cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <formula>TEXT (SBQQ__Opportunity2__r.County__c)</formula>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Dimension3__c.field-meta.xml
<CustomField>
    <fullName>Dimension3__c</fullName>
    <formula>TEXT (SBQQ__Opportunity2__r.Dimension3__c)</formula>
    <label>Dimensión 3</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Duración Contrato (Años)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/EstimatedConsumption__c.field-meta.xml
<CustomField>
    <fullName>EstimatedConsumption__c</fullName>
    <inlineHelpText>Consumo estimado anual</inlineHelpText>
    <label>Consumo anual estimado (KG)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/HasStretches__c.field-meta.xml
<CustomField>
    <fullName>HasStretches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tiene tramos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DiscountDuration__c.field-meta.xml
<CustomField>
    <fullName>DiscountDuration__c</fullName>
    <description>Duración del descuento de tarifa de gas</description>
    <label>Duración del descuento (Años)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/TankName__c.field-meta.xml
<CustomField>
    <fullName>TankName__c</fullName>
    <description>Modelo</description>
    <label>Modelo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceCost__c/ServiceCost__c.object-meta.xml
<CustomObject>
    <label>Coste de Servicio</label>
    <nameField>
        <displayFormat>SC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costes de Servicio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMaintenanceCost__c/TankMaintenanceCost__c.object-meta.xml
<CustomObject>
    <description>Costes de mantenimiento según la provincia de instalación del depósito.</description>
    <label>Coste de Mantenimiento de Depósito</label>
    <nameField>
        <displayFormat>TMC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coste de Mantenimiento de Depósito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMasterData__c/TankMasterData__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los campos con información sobre las opciones y costes de instalación de los depósitos de gas.</description>
    <label>Maestro de Depósito</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestro de Depósitos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TankMasterData__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Coste del depósito</description>
    <label>Coste</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TankMasterData__c/fields/TankName__c.field-meta.xml
<CustomField>
    <fullName>TankName__c</fullName>
    <description>Modelo de depósito</description>
    <label>Tank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPQ_TestDataFactory.cls
@isTest
public without sharing class CPQ_TestDataFactory {

    public static void LoadAllCSVTestDatasets(){
        LoadGasCosts();
        LoadProducts();
        LoadEquipmentMasterData();
        LoadTankMasterData();
        LoadTankMaintenanceCosts();
        LoadServiceCosts();
    }
    
    public static void LoadGasCosts(){
        Test.loadData(GasCost__c.sObjectType, 'CPQ_TEST_GasCostsCSV');
    }
    public static void LoadProducts(){
        Test.loadData(Product2.sObjectType, 'CPQ_TEST_ProductsCSV');
    }
    public static void LoadTankMaintenanceCosts(){
        Test.loadData(TankMaintenanceCost__c.sObjectType, 'CPQ_TEST_TankMaintenanceCostCSV');
    }
    public static void LoadTankMasterData(){
        Test.loadData(TankMasterData__c.sObjectType, 'CPQ_TEST_TankMasterDataCSV');
    }
    public static void LoadServiceCosts(){
        Test.loadData(ServiceCost__c.sObjectType, 'CPQ_TEST_ServiceCostsCSV');
    }
    public static void LoadEquipmentMasterData(){
        Test.loadData(EquipmentMasterData__c.sObjectType, 'CPQ_TEST_EquipmentMasterDataCSV');
    }
    public static void setDefaultSettings(){
        CPQ_Settings.setTestSetting(new CPQ_Settings__mdt(DiscountRatePercentage__c = 11,
                                                            DepRate5Years__c = 11,
                                                            DepRate10Years__c = 6,
                                                            DepYears__c = 15,
                                                            DefaultPBAEstimatedConsPerc__c = 80,
                                                            LogsEnabled__c = false));
    }

    public static void buildTestQuoteA(Id accountId){

        Opportunity opp1 = new CPQ_TestDataFactory.OpportunityBuilder('Opp1')
            .withCounty('Barcelona')
            .withCloseDate(Date.today())
            .withDimension3(CPQ_Opportunity.DIMENSION3_1000_DU)
            .withStageName('Closed')
            .build();
        insert opp1;

        SBQQ__Quote__c quote1 = new CPQ_TestDataFactory.QuoteBuilder()
            .withOpportunity(opp1.Id)
            .withContractDuration(5)
            .withAccount(accountId)
            .withEstimatedConsumption(10000)
            .build();
        insert quote1;

        List<SBQQ__QuoteLine__c> qlis = new List<SBQQ__QuoteLine__c>{
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.DEPOSITO).Id)
                .withNetPrice(2250)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.TRANSDEPOSITO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.LEGALIZACION).Id)
                .withNetPrice(225)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.INSTALACION).Id)
                .withNetPrice(1100)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.PROYECTOMEMORIA).Id)
                .withNetPrice(300)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.OBRACIVIL).Id)
                .withNetPrice(750)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.VALLADO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),

            // OTHER EQUIPMENT 
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode('CALDERA36KW').Id)
                .withNetPrice(3000)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.INSTALACION).Id)
                .withNetPrice(500)
                .withQuantity(1)
                .build(),

            // PRIMASERVICIOS 
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.PRIMASERVICIOS).Id)
                .withNetPrice(9.95)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.PUESTAAPUNTO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.MANTDEPOSITO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.ATENCION24).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.SEGURO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.INSPOBLIGATORIA).Id)
                .withNetPrice(2.95)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.MANTINTERIORES).Id)
                .withNetPrice(6.95)
                .withQuantity(1)
                .build(),
                
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.CUOTASINVERSION).Id)
                .withNetPrice(30)
                .withQuantity(15)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.PAGOINICIAL).Id)
                .withNetPrice(400)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.DESC1LLENADO).Id)
                .withNetPrice(500)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.CUOTASALQUILER).Id)
                .withNetPrice(20)
                .withQuantity(24)
                .build(),
            // RATE
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.TARIFA).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.SPOT).Id)
                .withNetPrice(0.79)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.DESCTARIFA).Id)
                .withNetPrice(0.05)
                .withDiscountDuration(3)
                .build()
        };

        insert qlis;
    }

    public static void buildTestQuoteB(Id accountId){

        Opportunity opp1 = new CPQ_TestDataFactory.OpportunityBuilder('Opp2')
            .withCounty('Barcelona')
            .withCloseDate(Date.today())
            .withDimension3(CPQ_Opportunity.DIMENSION3_1000_DU)
            .withStageName('Closed')
            .build();
        insert opp1;

        SBQQ__Quote__c quote1 = new CPQ_TestDataFactory.QuoteBuilder()
            .withOpportunity(opp1.Id)
            .withContractDuration(5)
            .withAccount(accountId)
            .withEstimatedConsumption(10000)
            .build();
        insert quote1;

        List<SBQQ__QuoteLine__c> qlis = new List<SBQQ__QuoteLine__c>{
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.DEPOSITO).Id)
                .withNetPrice(2250)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.TRANSDEPOSITO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.LEGALIZACION).Id)
                .withNetPrice(225)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.INSTALACION).Id)
                .withNetPrice(1100)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.PROYECTOMEMORIA).Id)
                .withNetPrice(300)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.OBRACIVIL).Id)
                .withNetPrice(750)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.VALLADO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .withTankName('ETERNELLA')
                .build(),

            // OTHER EQUIPMENT 
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode('CALDERA36KW').Id)
                .withNetPrice(3000)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.INSTALACION).Id)
                .withNetPrice(500)
                .withQuantity(1)
                .build(),

            // PRIMASERVICIOS 
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.PRIMASERVICIOS).Id)
                .withNetPrice(9.95)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.PUESTAAPUNTO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.MANTDEPOSITO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.ATENCION24).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.SEGURO).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.INSPOBLIGATORIA).Id)
                .withNetPrice(2.95)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.MANTINTERIORES).Id)
                .withNetPrice(6.95)
                .withQuantity(1)
                .build(),
                
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.CUOTASINVERSION).Id)
                .withNetPrice(30)
                .withQuantity(15)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.PAGOINICIAL).Id)
                .withNetPrice(400)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.DESC1LLENADO).Id)
                .withNetPrice(500)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.CUOTASALQUILER).Id)
                .withNetPrice(20)
                .withQuantity(24)
                .build(),
            // RATE
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.TARIFA).Id)
                .withNetPrice(0)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.SPOT).Id)
                .withNetPrice(0.79)
                .withQuantity(1)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.DESCTARIFA).Id)
                .withNetPrice(0.05)
                .withDiscountDuration(3)
                .build(),
            new CPQ_TestDataFactory.QuoteLineItemBuilder(quote1.Id)
                .withProduct(CPQ_TestDataFactory.getProductByCode(CPQ_ProductCodes.VAPORIZADOR).Id)
                .withNetPrice(800)
                .withQuantity(1)
                .build()
        };

        insert qlis;
    }

    private static Map<String, Product2> productsByProductCode = new Map<String, Product2>();
    private static Map<String, TankMaintenanceCost__c> tankMaintenanceCostByName = new Map<String, TankMaintenanceCost__c>();
    private static Map<String, TankMasterData__c> tankMasterDataByName = new Map<String, TankMasterData__c>();

    public static void FetchProductsByProductCode(){
        for(Product2 p : [SELECT Id, ProductCode FROM Product2 WHERE IsActive = true]){
            productsByProductCode.put(p.ProductCode, p);
        }
    }
    public static void FetchTankMaintenanceCostByTankName(){
        for(TankMaintenanceCost__c t : [SELECT Id, Name, Cost__c FROM TankMaintenanceCost__c]){
            tankMaintenanceCostByName.put(t.Name, t);
        }
    }
    public static void FetchTankMasterDataByTankName(){
        for(TankMasterData__c t : [SELECT Id, Name, Cost__c FROM TankMasterData__c]){
            tankMasterDataByName.put(t.Name, t);
        }
    }

    public static Product2 getProductByCode(String code){
        return productsByProductCode.get(code);
    }

    public class AccountBuilder {
        private Account obj = new Account();

        public AccountBuilder(String name){
            obj.Name = name;
        }

        public Account build() {
            return obj;
        }
    }

    public class OpportunityBuilder {
        private Opportunity obj = new Opportunity();

        public OpportunityBuilder(String name){
            obj.Name = name;
        }

        public OpportunityBuilder withCounty(String value) {
            obj.County__c = value;
            return this;
        }
        public OpportunityBuilder withStageName(String value) {
            obj.StageName = value;
            return this;
        }
        public OpportunityBuilder withCloseDate(Date value) {
            obj.CloseDate = value;
            return this;
        }
        public OpportunityBuilder withDimension3(String value) {
            obj.Dimension3__c = value;
            return this;
        }

        public Opportunity build() {
            return obj;
        }
    }


    public class QuoteBuilder {
        private SBQQ__Quote__c obj = new SBQQ__Quote__c();

        public QuoteBuilder withAccount(Id value) {
            obj.SBQQ__Account__c = value;
            return this;
        }
        
        public QuoteBuilder withContractDuration(Decimal value) {
            obj.Duration__c = value;
            return this;
        }

        public QuoteBuilder withEstimatedConsumption(Decimal value) {
            obj.EstimatedConsumption__c = value;
            return this;
        }

        public QuoteBuilder withOpportunity(Id value) {
            obj.SBQQ__Opportunity2__c = value;
            return this;
        }

        public QuoteBuilder withStatus(String value) {
            obj.SBQQ__Status__c = value;
            return this;
        }

        public QuoteBuilder withClientTank(Boolean value) {
            obj.ClientTank__c = value;
            return this;
        }
        public QuoteBuilder withHasStretches(Boolean value) {
            obj.HasStretches__c = value;
            return this;
        }

        public SBQQ__Quote__c build() {
            return obj;
        }
    }

    public class QuoteLineItemBuilder {
        private SBQQ__QuoteLine__c obj = new SBQQ__QuoteLine__c();

        public QuoteLineItemBuilder(Id quoteId){
            obj.SBQQ__Quote__c = quoteId;
        }

        public QuoteLineItemBuilder withProduct(Id value) {
            obj.SBQQ__Product__c = value;
            return this;
        }
        public QuoteLineItemBuilder withNetPrice(Decimal value) {
            obj.SBQQ__NetPrice__c = value;
            return this;
        }
        public QuoteLineItemBuilder withQuantity(Decimal value) {
            obj.SBQQ__Quantity__c = value;
            return this;
        }
        public QuoteLineItemBuilder withDiscountDuration(Decimal value) {
            obj.DiscountDuration__c = value;
            return this;
        }
        public QuoteLineItemBuilder withTankName(String value) {
            obj.TankName__c = value;
            return this;
        }
        public SBQQ__QuoteLine__c build() {
            return obj;
        }
    }


}