force-app/main/default/objects/CPQ_Settings__mdt/CPQ_Settings__mdt.object-meta.xml
<CustomObject>
    <label>CPQ Setting</label>
    <pluralLabel>CPQ Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DefaultPBAEstimatedConsPerc__c.field-meta.xml
<CustomField>
    <fullName>DefaultPBAEstimatedConsPerc__c</fullName>
    <label>% cons. estimado PBA por defecto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DepRate10Years__c.field-meta.xml
<CustomField>
    <fullName>DepRate10Years__c</fullName>
    <label>Factor Dep. 10años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DepRate5Years__c.field-meta.xml
<CustomField>
    <fullName>DepRate5Years__c</fullName>
    <label>Factor Dep. 5años</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DepYears__c.field-meta.xml
<CustomField>
    <fullName>DepYears__c</fullName>
    <label>Años Dep.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/DiscountRatePercentage__c.field-meta.xml
<CustomField>
    <fullName>DiscountRatePercentage__c</fullName>
    <label>% tasa descuento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__mdt/fields/LogsEnabled__c.field-meta.xml
<CustomField>
    <fullName>LogsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, extended logs information is shown for the metrics calculations.</description>
    <inlineHelpText>If true, extended logs information is shown for the metrics calculations.</inlineHelpText>
    <label>LogsEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/EstimatedConsumption__c.field-meta.xml
<CustomField>
    <fullName>EstimatedConsumption__c</fullName>
    <inlineHelpText>Consumo estimado anual</inlineHelpText>
    <label>Consumo anual estimado (KG)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CPQ_CLVServiceTest.cls
@isTest
public class CPQ_CLVServiceTest {
    
    @TestSetup
    static void setup() {
        CPQ_TestDataFactory.LoadAllCSVTestDatasets();
        CPQ_TestDataFactory.FetchProductsByProductCode();

        Account account = new CPQ_TestDataFactory.AccountBuilder('TestAccount1').build();
        insert account;

        CPQ_TestDataFactory.buildTestQuoteA(account.Id);
    }

    @IsTest
    static void testCLV() {
        CPQ_TestDataFactory.setDefaultSettings();

        SBQQ__Quote__c quote1 = [SELECT Id, EstimatedConsumption__c FROM SBQQ__Quote__c LIMIT 1];

        CPQ_Quote.QuoteWrapper quoteWrapper = CPQ_QuoteService.buildWrappersFromQuotesId(new Set<Id>{ quote1.Id })[0];
        CPQ_TablesDataWrapper tablesData = CPQ_TablesDataWrapper.generate(quoteWrapper);

        // Test CLV5
        System.assertEquals(3393.3, (Decimal)Math.round(CPQ_CLVService.calculateResult(5, quoteWrapper, null, tablesData, CPQ_Settings.DefaultPBAEstimatedConsCoef)*10)/(Decimal)10);
        // Test CLV10
        System.assertEquals(9369.3, (Decimal)Math.round(CPQ_CLVService.calculateResult(10, quoteWrapper, null, tablesData, CPQ_Settings.DefaultPBAEstimatedConsCoef)*10)/(Decimal)10);
    }

    @IsTest
    static void testCLVWithDifferentSettings() {

        CPQ_Settings.setTestSetting(new CPQ_Settings__mdt(DiscountRatePercentage__c = 8,
                                                            DepRate5Years__c = 10,
                                                            DepRate10Years__c = 5,
                                                            DepYears__c = 15,
                                                            DefaultPBAEstimatedConsPerc__c = 80,
                                                            LogsEnabled__c = true));

        SBQQ__Quote__c quote1 = [SELECT Id, EstimatedConsumption__c FROM SBQQ__Quote__c LIMIT 1];

        CPQ_Quote.QuoteWrapper quoteWrapper = CPQ_QuoteService.buildWrappersFromQuotesId(new Set<Id>{ quote1.Id })[0];
        CPQ_TablesDataWrapper tablesData = CPQ_TablesDataWrapper.generate(quoteWrapper);

        // Test CLV5
        System.assertEquals(4219.5, (Decimal)Math.round(CPQ_CLVService.calculateResult(5, quoteWrapper, null, tablesData, CPQ_Settings.DefaultPBAEstimatedConsCoef)*10)/(Decimal)10);
        // Test CLV10
        System.assertEquals(11717.0, (Decimal)Math.round(CPQ_CLVService.calculateResult(10, quoteWrapper, null, tablesData, CPQ_Settings.DefaultPBAEstimatedConsCoef)*10)/(Decimal)10);
    }
}