force-app/main/default/objects/Account/fields/Alerta_Bloqueo__c.field-meta.xml
<CustomField>
    <fullName>Alerta_Bloqueo__c</fullName>
    <label>Alerta bloqueo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consumo_ltimos_12_meses__c.field-meta.xml
<CustomField>
    <fullName>Consumo_ltimos_12_meses__c</fullName>
    <label>Consumo últimos 12 meses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente Navision</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Alava/Araba</fullName>
                <label>Álava/Araba</label>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Bizkaia/Vizcaya</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Caceres</fullName>
                <label>Cáceres</label>
            </value>
            <value>
                <fullName>Cadiz</fullName>
                <label>Cádiz</label>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ceuta</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>Las Palmas</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Saldo_pendiente__c.field-meta.xml
<CustomField>
    <fullName>Saldo_pendiente__c</fullName>
    <inlineHelpText>Saldo vencido</inlineHelpText>
    <label>Saldo pendiente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Saldo_vivo__c.field-meta.xml
<CustomField>
    <fullName>Saldo_vivo__c</fullName>
    <label>Saldo vivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ultima_sync_detalle_clientes__c.field-meta.xml
<CustomField>
    <fullName>Ultima_sync_detalle_clientes__c</fullName>
    <description>Indica la ultima fecha en la que el cliente o algúna dirección de entrega ha sido modificada mediante Nav2sfdc_ActualizacionDiariaClientes</description>
    <label>Última sync. detalle clientes</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deposito__c/Deposito__c.object-meta.xml
<CustomObject>
    <label>Depósito</label>
    <nameField>
        <label>Nombre del depósito</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depósitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcci_n_de_entrega__c/Direcci_n_de_entrega__c.object-meta.xml
<CustomObject>
    <description>Ship to address</description>
    <label>Dirección de entrega</label>
    <nameField>
        <displayFormat>STA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones de entrega</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Boca_de_carga__c.field-meta.xml
<CustomField>
    <fullName>Boca_de_carga__c</fullName>
    <label>Boca de carga</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Consumo_ltimos_12_meses__c.field-meta.xml
<CustomField>
    <fullName>Consumo_ltimos_12_meses__c</fullName>
    <label>Consumo últimos 12 meses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Consumo_previsto_Kgs__c.field-meta.xml
<CustomField>
    <fullName>Consumo_previsto_Kgs__c</fullName>
    <inlineHelpText>Consumo prevista Kgs. (del contrato)</inlineHelpText>
    <label>Consumo previsto Kgs.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Consumo_promedio_ltimos_3_a_os__c.field-meta.xml
<CustomField>
    <fullName>Consumo_promedio_ltimos_3_a_os__c</fullName>
    <label>Consumo promedio últimos 3 años</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/cuenta__c.field-meta.xml
<CustomField>
    <fullName>cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Direcciones de entrega</relationshipLabel>
    <relationshipName>Direcciones_de_entrega</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Deposito__c.field-meta.xml
<CustomField>
    <fullName>Deposito__c</fullName>
    <label>Depósito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <inlineHelpText>dto(€/Kg)</inlineHelpText>
    <label>Descuento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Estado_boca_de_carga__c.field-meta.xml
<CustomField>
    <fullName>Estado_boca_de_carga__c</fullName>
    <label>Estado boca de carga</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Estado_deposito__c.field-meta.xml
<CustomField>
    <fullName>Estado_deposito__c</fullName>
    <label>Estado depósito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Estado_telemedida__c.field-meta.xml
<CustomField>
    <fullName>Estado_telemedida__c</fullName>
    <label>Estado telemedida</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <label>Id Navision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Precio_actual__c.field-meta.xml
<CustomField>
    <fullName>Precio_actual__c</fullName>
    <label>Precio actual</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Propiedad_del_tanque__c.field-meta.xml
<CustomField>
    <fullName>Propiedad_del_tanque__c</fullName>
    <label>Propiedad del tanque</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alava/Araba</fullName>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Cáceres</fullName>
            </value>
            <value>
                <fullName>Cádiz</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ceuta</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Lleida/Lérida</fullName>
            </value>
            <value>
                <fullName>Lugo</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Bizkaia/Vizcaya</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Telemedida__c.field-meta.xml
<CustomField>
    <fullName>Telemedida__c</fullName>
    <label>Telemedida</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Se registran errors generados en código y el historial de sincronización con Navision</description>
    <label>Log</label>
    <nameField>
        <label>Nombre de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TEST_Nav2sfdcActualizacionDiariaClientes.cls
@isTest
private class TEST_Nav2sfdcActualizacionDiariaClientes 
{
	private static final Integer NUM_CUENTAS_EMPRESA		= 1;         // Numero de cuentas a crear
	private static final Integer NUM_CUENTAS_PARTICULARES	= 1;         // Numero de cuentas a crear
	private static final Integer NUM_DIRECCIONES 			= 1;         // Numero de direcciones de entrega 

	@TestSetup 
	static void generateEnvironment()
	{	
		RecordType clienteExistente = Util.objectsRecordTypesMap.get('Account').get('Cliente_existente');


		List<Account> cuentasList = Util.generarCuentas(NUM_CUENTAS_PARTICULARES, 0, Util.objectsRecordTypesMap.get('Account').get('Cliente_existente').Id);
		List<Direcci_n_de_entrega__c> direccionesList = new List<Direcci_n_de_entrega__c>();

		/*CUENTAS EMPRESA*/
		for(Integer i = 0 ; i < cuentasList.size() ; i++)
		{
			cuentasList[i].Id_Navision__c = String.valueOf(NUM_CUENTAS_EMPRESA+i);
		}

		AccountUtil.semaforoUpdate = false;
		insert cuentasList;
		AccountUtil.semaforoUpdate = true;

		/*DIRECCIONES DE ENTREGA*/
		for(Account cuenta : cuentasList)
		{
			Direcci_n_de_entrega__c direccion = new Direcci_n_de_entrega__c(
				Cuenta__c = cuenta.Id,
				Provincia__c = 'Bizkaia/Vizcaya',
				Id_Navision__c	= String.valueOf(NUM_DIRECCIONES)
			);
			direccionesList.add(direccion);
		}
		

		DireccionEnvioUtil.semaforoUpdate = false;
		insert direccionesList;
		DireccionEnvioUtil.semaforoUpdate = true;

	}
	
	//Metodo encargado de comprobar que se ha actualizado correctamente una cuenta y direccion concretas 
	//(las que vienen en el MockUp que se han identificado como la cuenta 1 y direccion 1)
	//En este caso cada cuenta tiene solo una direccion de entrega
	@isTest 
	static void actualizacionCorrecta() 
	{
		Test.startTest();

        Test.setMock(HttpCalloutMock.class, new NTLMHttpCalloutMockImpl(0));
		Nav2sfdc_ActualizacionDiariaClientes detalleClientes = new Nav2sfdc_ActualizacionDiariaClientes(0);
    	detalleClientes.execute(null);

    	Test.stopTest();
		/*
		Se quita del select de abajo los campos Saldo_vivo__c, Saldo_pendiente__c,Descuento__c, Consumo_promedio_ltimos_3_a_os__c, Consumo_ltimos_12_meses__c,; para poder cambio el tipo de campo.
		 */
    	for(Account cuenta: [SELECT Id, Id_Navision__c,  Alerta_Bloqueo__c, Ultima_sync_detalle_clientes__c,
								(SELECT Id, Id_Navision__c, Consumo_previsto_Kgs__c, 
								Precio_actual__c, Boca_de_carga__c, Estado_boca_de_carga__c, Deposito__c, Estado_deposito__c, Telemedida__c,
								Estado_telemedida__c, Propiedad_del_tanque__c
								 FROM Direcciones_de_entrega__r) 
							FROM Account])
		{  
			if(cuenta.Id_Navision__c.equals('1'))
			{
				//System.assertEquals(cuenta.Saldo_vivo__c, 9.95);
				//System.assertEquals(cuenta.Saldo_pendiente__c, 9.95);
				//System.assertEquals(cuenta.Alerta_Bloqueo__c, 'TestAlertaBloqueo');
				System.assertEquals(Date.newinstance(cuenta.Ultima_sync_detalle_clientes__c.year(), cuenta.Ultima_sync_detalle_clientes__c.month(), cuenta.Ultima_sync_detalle_clientes__c.day()), System.today());
			}else{
				//System.assertEquals(cuenta.Saldo_vivo__c, null);
				//System.assertEquals(cuenta.Saldo_pendiente__c, null);
				//System.assertEquals(cuenta.Alerta_Bloqueo__c, null);
				System.assertEquals(cuenta.Ultima_sync_detalle_clientes__c, null);
			}
			for(Direcci_n_de_entrega__c direccion : cuenta.Direcciones_de_entrega__r)
		    {
		    	if(cuenta.Id_Navision__c.equals('1'))
				{
					System.assertEquals(direccion.Consumo_previsto_Kgs__c, 1000);
					//System.assertEquals(direccion.Consumo_promedio_ltimos_3_a_os__c, 526);
					//System.assertEquals(direccion.Consumo_ltimos_12_meses__c, 526);
					//System.assertEquals(direccion.Precio_actual__c, '1,012');
					//System.assertEquals(direccion.Descuento__c, 0);
					System.assertEquals(direccion.Boca_de_carga__c, 'TestBocaCarga');
					System.assertEquals(direccion.Estado_boca_de_carga__c, 'TestBocaCarga');
					System.assertEquals(direccion.Deposito__c, 'DEP010199--245490729');
					System.assertEquals(direccion.Estado_deposito__c, 'Installed');
					System.assertEquals(direccion.Telemedida__c, 'TELM001058--4962748');
					System.assertEquals(direccion.Estado_telemedida__c, 'Installed');
					System.assertEquals(direccion.Propiedad_del_tanque__c, 'Own');
				}else{
					System.assertEquals(direccion.Consumo_previsto_Kgs__c, null);
					//System.assertEquals(direccion.Consumo_promedio_ltimos_3_a_os__c, null);
					//System.assertEquals(direccion.Consumo_ltimos_12_meses__c, null);
					System.assertEquals(direccion.Precio_actual__c, null);
					//System.assertEquals(direccion.Descuento__c, null);
					System.assertEquals(direccion.Boca_de_carga__c, null);
					System.assertEquals(direccion.Estado_boca_de_carga__c, null);
					System.assertEquals(direccion.Deposito__c, null);
					System.assertEquals(direccion.Estado_deposito__c, null);
					System.assertEquals(direccion.Telemedida__c, null);
					System.assertEquals(direccion.Estado_telemedida__c, null);
					System.assertEquals(direccion.Propiedad_del_tanque__c, null);
				}
		    }
		}
	}

	//Metodo encargado de comprobar que se no se actualiza ningun registro cuando no recibe nada 
	@isTest 
	static void actualizacionConRespuestaVacia() 
	{
		Test.startTest();

        Test.setMock(HttpCalloutMock.class, new NTLMHttpCalloutMockImpl(2));
		Nav2sfdc_ActualizacionDiariaClientes detalleClientes = new Nav2sfdc_ActualizacionDiariaClientes(0);
    	detalleClientes.execute(null);

    	Test.stopTest();
		/*
		Se quita del select de abajo los campos Saldo_vivo__c, Saldo_pendiente__c,Descuento__c, Consumo_promedio_ltimos_3_a_os__c, Consumo_ltimos_12_meses__c,; para poder cambio el tipo de campo.
		 */
    	for(Account cuenta: [SELECT Id, Id_Navision__c, Alerta_Bloqueo__c, Ultima_sync_detalle_clientes__c,
								(SELECT Id, Id_Navision__c, Consumo_previsto_Kgs__c,
								Precio_actual__c, Boca_de_carga__c, Estado_boca_de_carga__c, Deposito__c, Estado_deposito__c, Telemedida__c,
								Estado_telemedida__c, Propiedad_del_tanque__c
								 FROM Direcciones_de_entrega__r) 
							FROM Account])
		{  
			//System.assertEquals(cuenta.Saldo_vivo__c, null);
			//System.assertEquals(cuenta.Saldo_pendiente__c, null);
			//System.assertEquals(cuenta.Alerta_Bloqueo__c, null);
			System.assertEquals(cuenta.Ultima_sync_detalle_clientes__c, null);

			for(Direcci_n_de_entrega__c direccion : cuenta.Direcciones_de_entrega__r)
		    {
				System.assertEquals(direccion.Consumo_previsto_Kgs__c, null);
				//System.assertEquals(direccion.Consumo_promedio_ltimos_3_a_os__c, null);
				//System.assertEquals(direccion.Consumo_ltimos_12_meses__c, null);
				System.assertEquals(direccion.Precio_actual__c, null);
				//System.assertEquals(direccion.Descuento__c, null);
				System.assertEquals(direccion.Boca_de_carga__c, null);
				System.assertEquals(direccion.Estado_boca_de_carga__c, null);
				System.assertEquals(direccion.Deposito__c, null);
				System.assertEquals(direccion.Estado_deposito__c, null);
				System.assertEquals(direccion.Telemedida__c, null);
				System.assertEquals(direccion.Estado_telemedida__c, null);
				System.assertEquals(direccion.Propiedad_del_tanque__c, null);
		    }
		}
	}
	
	//Metodo encargado de comprobar que se ha actualizado correctamente una cuenta y sus direcciones
	//(las que vienen en el MockUp que se han identificado como la cuenta 1 y direccion 1)
	//En este caso cada cuenta tiene solo una direccion de entrega
	@isTest 
	static void actualizacionCorrectaVariasDirecciones() 
	{
		List<Account> cuentasInsertadasList = [SELECT Id FROM Account];
		List<Direcci_n_de_entrega__c> nuevasDireccionesList = new List<Direcci_n_de_entrega__c>();

		for(Account cuenta : cuentasInsertadasList)
		{
			Direcci_n_de_entrega__c direccion = new Direcci_n_de_entrega__c(
				Cuenta__c = cuenta.Id,
				Provincia__c = 'Bizkaia/Vizcaya',
				Id_Navision__c	= String.valueOf(NUM_DIRECCIONES+1)
			);
			nuevasDireccionesList.add(direccion);
		}
		DireccionEnvioUtil.semaforoUpdate = false;
		insert nuevasDireccionesList;
		DireccionEnvioUtil.semaforoUpdate = true;

		Test.startTest();

        Test.setMock(HttpCalloutMock.class, new NTLMHttpCalloutMockImpl(1));
		Nav2sfdc_ActualizacionDiariaClientes detalleClientes = new Nav2sfdc_ActualizacionDiariaClientes(0);
    	detalleClientes.execute(null);

    	Test.stopTest();
		/*
		Se quita del select de abajo los campos Saldo_vivo__c, Saldo_pendiente__c,Descuento__c, Consumo_promedio_ltimos_3_a_os__c, Consumo_ltimos_12_meses__c,; para poder cambio el tipo de campo.
		 */
    	for(Account cuenta: [SELECT Id, Id_Navision__c, Alerta_Bloqueo__c, Ultima_sync_detalle_clientes__c,
								(SELECT Id, Id_Navision__c, Consumo_previsto_Kgs__c,
								Precio_actual__c, Boca_de_carga__c, Estado_boca_de_carga__c, Deposito__c, Estado_deposito__c, Telemedida__c,
								Estado_telemedida__c, Propiedad_del_tanque__c
								 FROM Direcciones_de_entrega__r) 
							FROM Account])
		{  
			if(cuenta.Id_Navision__c.equals('1'))
			{
				//System.assertEquals(cuenta.Saldo_vivo__c, 9.95);
				//System.assertEquals(cuenta.Saldo_pendiente__c, 9.95);
				//System.assertEquals(cuenta.Alerta_Bloqueo__c, 'TestAlertaBloqueo');
				System.assertEquals(Date.newinstance(cuenta.Ultima_sync_detalle_clientes__c.year(), cuenta.Ultima_sync_detalle_clientes__c.month(), cuenta.Ultima_sync_detalle_clientes__c.day()), System.today());
			}else{
				//System.assertEquals(cuenta.Saldo_vivo__c, null);
				//System.assertEquals(cuenta.Saldo_pendiente__c, null);
				//System.assertEquals(cuenta.Alerta_Bloqueo__c, null);
				System.assertEquals(cuenta.Ultima_sync_detalle_clientes__c, null);
			}
			for(Direcci_n_de_entrega__c direccion : cuenta.Direcciones_de_entrega__r)
		    {
		    	if(cuenta.Id_Navision__c.equals('1'))
				{
					System.assertEquals(direccion.Consumo_previsto_Kgs__c, 1000);
					//System.assertEquals(direccion.Consumo_promedio_ltimos_3_a_os__c, 526);
					//System.assertEquals(direccion.Consumo_ltimos_12_meses__c, 526);
					//System.assertEquals(direccion.Precio_actual__c, '1,012');
					//System.assertEquals(direccion.Descuento__c, 0);
					System.assertEquals(direccion.Boca_de_carga__c, 'TestBocaCarga');
					System.assertEquals(direccion.Estado_boca_de_carga__c, 'TestBocaCarga');
					System.assertEquals(direccion.Deposito__c, 'DEP010199--245490729');
					System.assertEquals(direccion.Estado_deposito__c, 'Installed');
					System.assertEquals(direccion.Telemedida__c, 'TELM001058--4962748');
					System.assertEquals(direccion.Estado_telemedida__c, 'Installed');
					System.assertEquals(direccion.Propiedad_del_tanque__c, 'Own');
				}else{
					System.assertEquals(direccion.Consumo_previsto_Kgs__c, null);
					//System.assertEquals(direccion.Consumo_promedio_ltimos_3_a_os__c, null);
					//System.assertEquals(direccion.Consumo_ltimos_12_meses__c, null);
					System.assertEquals(direccion.Precio_actual__c, null);
					//System.assertEquals(direccion.Descuento__c, null);
					System.assertEquals(direccion.Boca_de_carga__c, null);
					System.assertEquals(direccion.Estado_boca_de_carga__c, null);
					System.assertEquals(direccion.Deposito__c, null);
					System.assertEquals(direccion.Estado_deposito__c, null);
					System.assertEquals(direccion.Telemedida__c, null);
					System.assertEquals(direccion.Estado_telemedida__c, null);
					System.assertEquals(direccion.Propiedad_del_tanque__c, null);
				}
		    }
		}
	}

	/*
		Cubre la llamada a la clase programable. Las validaciones se hacen directamente sobre la encolable
		Cubre una llamada al constructor
	*/
	@isTest 
	static void scheduler()
	{
		Test.startTest();

        Test.setMock(HttpCalloutMock.class, new NTLMHttpCalloutMockImpl(0));
		Nav2sfdc_DetalleClientesScheduler detalleClientesScheduler = new Nav2sfdc_DetalleClientesScheduler(0);
    	detalleClientesScheduler.execute(null);

    	Test.stopTest();
    }

    @isTest 
	static void gestionErrores() 
	{
		Test.startTest();

		Nav2sfdc_ActualizacionDiariaClientes detalleClientes = new Nav2sfdc_ActualizacionDiariaClientes(0);
    	detalleClientes.execute(null);

    	Test.stopTest();

    	List<Log__c> logsList = [SELECT Id FROM Log__c];
    	System.assertEquals(1, logsList.size());
    }
}