force-app/main/default/objects/Account/fields/C_digo_tarifa__c.field-meta.xml
<CustomField>
    <fullName>C_digo_tarifa__c</fullName>
    <label>Código tarifa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>91001064</fullName>
            </value>
            <value>
                <fullName>91001632</fullName>
            </value>
            <value>
                <fullName>91001753</fullName>
            </value>
            <value>
                <fullName>91002027</fullName>
            </value>
            <value>
                <fullName>91002348</fullName>
            </value>
            <value>
                <fullName>91002421</fullName>
            </value>
            <value>
                <fullName>91002692</fullName>
            </value>
            <value>
                <fullName>91002949</fullName>
            </value>
            <value>
                <fullName>92000600</fullName>
            </value>
            <value>
                <fullName>92000635</fullName>
            </value>
            <value>
                <fullName>92000947</fullName>
            </value>
            <value>
                <fullName>92001811</fullName>
            </value>
            <value>
                <fullName>92001811.</fullName>
            </value>
            <value>
                <fullName>93000067</fullName>
            </value>
            <value>
                <fullName>93000070</fullName>
            </value>
            <value>
                <fullName>93000074</fullName>
            </value>
            <value>
                <fullName>93000080</fullName>
            </value>
            <value>
                <fullName>93000107</fullName>
            </value>
            <value>
                <fullName>93000217</fullName>
            </value>
            <value>
                <fullName>93000227</fullName>
            </value>
            <value>
                <fullName>93000249</fullName>
            </value>
            <value>
                <fullName>93000249.</fullName>
            </value>
            <value>
                <fullName>93000250</fullName>
            </value>
            <value>
                <fullName>93000250.</fullName>
            </value>
            <value>
                <fullName>93000278</fullName>
            </value>
            <value>
                <fullName>93000344</fullName>
            </value>
            <value>
                <fullName>93000353</fullName>
            </value>
            <value>
                <fullName>93000359</fullName>
            </value>
            <value>
                <fullName>93000405</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <description>Código postal facturación</description>
    <label>Código Postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_ltima_Sync__c.field-meta.xml
<CustomField>
    <fullName>Fecha_ltima_Sync__c</fullName>
    <label>Fecha última Sync</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente Navision</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Alava/Araba</fullName>
                <label>Álava/Araba</label>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Bizkaia/Vizcaya</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Caceres</fullName>
                <label>Cáceres</label>
            </value>
            <value>
                <fullName>Cadiz</fullName>
                <label>Cádiz</label>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ceuta</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>Las Palmas</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <label>Id Navision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/Direcci_n_de_entrega__c.object-meta.xml
<CustomObject>
    <description>Ship to address</description>
    <label>Dirección de entrega</label>
    <nameField>
        <displayFormat>STA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones de entrega</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/C_digo_tarifa__c.field-meta.xml
<CustomField>
    <fullName>C_digo_tarifa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Código tarifa</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Direcciones de entrega</relationshipLabel>
    <relationshipName>Direcciones_de_entrega</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/cuenta__c.field-meta.xml
<CustomField>
    <fullName>cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Direcciones de entrega</relationshipLabel>
    <relationshipName>Direcciones_de_entrega</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Direccion_2__c.field-meta.xml
<CustomField>
    <fullName>Direccion_2__c</fullName>
    <label>Dirección 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Fecha_ultima_Sync__c.field-meta.xml
<CustomField>
    <fullName>Fecha_ultima_Sync__c</fullName>
    <label>Fecha última Sync</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <label>Id Navision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Poblacion__c.field-meta.xml
<CustomField>
    <fullName>Poblacion__c</fullName>
    <label>Población</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alava/Araba</fullName>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Cáceres</fullName>
            </value>
            <value>
                <fullName>Cádiz</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ceuta</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Lleida/Lérida</fullName>
            </value>
            <value>
                <fullName>Lugo</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Fecha_ltima_Sync__c.field-meta.xml
<CustomField>
    <fullName>Fecha_ltima_Sync__c</fullName>
    <label>Fecha última Sync</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <label>Id Navision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TEST_DireccionEnvioUtil.cls
@isTest
public class TEST_DireccionEnvioUtil {
	
	// Método de prueba para probar la actualización de una Dirección de envío
	static testMethod void testProbarMetodosUpdateDireccionEntregaTrigger()
	{
		System.Debug('## before testProbarMetodosUpdateAccountTrigger');
		
		RecordType tiposRegistro = Util.objectsRecordTypesMap.get('Account').get('Cliente_existente');

		Account cuenta = new Account();
		cuenta.Name = 'Test';
		cuenta.RecordTypeId = tiposRegistro.Id;
		cuenta.Id_Navision__c = 'idNav';
		insert cuenta;
		
		Direcci_n_de_entrega__c direccionEntrega = new Direcci_n_de_entrega__c();
		direccionEntrega.Direccion__c = 'C/Tivoli nº28 4ºB';
		direccionEntrega.Direccion_2__c = 'C/Tivoli nº28 4ºB';
		direccionEntrega.Codigo_Postal__c = '48007';
		direccionEntrega.Poblacion__c = 'Bilbao';
		direccionEntrega.Provincia__c = 'Vizcaya';
		
		//Hay que mirarlo
		//direccionEntrega.C_digo_tarifa__r.Id_Navision__c = dirNav.ADCodePriceDiscount;
		//direccionEntrega.Id_Navision__c = '900000002'; 
		direccionEntrega.cuenta__c = cuenta.Id;
		insert direccionEntrega;
		
		//Creamos un contacto con estado Activado para que el cliente pase a ser de tipo Cliente Existente
		//Se comprueba que sea cliente existente
		/*Contract contrato = new Contract();
		contrato.AccountId = cuenta.Id;
		insert contrato;
		
		contrato.Status = 'Activado';
		
		//Desactivamos AccountUtil y ContractUtil
		ContractUtil.semaforoUpdate = false;
		AccountUtil.semaforoUpdate = false;
		update contrato;
		AccountUtil.semaforoUpdate = true;
		ContractUtil.semaforoUpdate = true;*/
		
		/*List<Account> listaCuentas = [select Id_Navision__c from Account where Id=:cuenta.Id];
		System.assertEquals(listaCuentas.size(),1);
		System.assert(String.IsEmpty(listaCuentas[0].Id_Navision__c));*/
		
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new NTLMHttpCalloutMockImpl(direccionEntrega.Id, cuenta.Id));
		direccionEntrega.Poblacion__c = 'Llodio';
		update direccionEntrega;
		Test.stopTest();
		
		List<Account> listaCuentas = [select Fecha_ltima_Sync__c from Account where Id=:cuenta.Id];
		System.assertEquals(listaCuentas.size(),1);
		System.assert(listaCuentas[0].Fecha_ltima_Sync__c!=null);

		System.Debug('## after testProbarMetodosUpdateAccountTrigger');
		
		List<Direcci_n_de_entrega__c> listaDireccionesEntrega = [select Fecha_ultima_Sync__c from Direcci_n_de_entrega__c where Id=:direccionEntrega.Id];
		
		//Comprobamos que se ha actualizado con el Id de Nav
		System.assert(listaDireccionesEntrega[0].Fecha_ultima_Sync__c!=null);
	}

}