force-app/main/default/objects/Account/fields/Calle_2__c.field-meta.xml
<CustomField>
    <fullName>Calle_2__c</fullName>
    <label>Calle 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Calle_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Calle_Facturacion__c</fullName>
    <label>Calle</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cod_forma_pago__c.field-meta.xml
<CustomField>
    <fullName>Cod_forma_pago__c</fullName>
    <label>Cód. forma pago</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12 BONOS</fullName>
            </value>
            <value>
                <fullName>ANTICIPAR</fullName>
            </value>
            <value>
                <fullName>APLAZAM</fullName>
            </value>
            <value>
                <fullName>BANKINTER</fullName>
            </value>
            <value>
                <fullName>CHEQUE</fullName>
            </value>
            <value>
                <fullName>CONF CHEQ</fullName>
            </value>
            <value>
                <fullName>CONF TRANS</fullName>
            </value>
            <value>
                <fullName>CUOTA</fullName>
            </value>
            <value>
                <fullName>DEVOLUCION</fullName>
            </value>
            <value>
                <fullName>DIA 20</fullName>
            </value>
            <value>
                <fullName>DOMI</fullName>
            </value>
            <value>
                <fullName>EFECTIVO</fullName>
            </value>
            <value>
                <fullName>GASTOS</fullName>
            </value>
            <value>
                <fullName>LA CAIXA</fullName>
            </value>
            <value>
                <fullName>PAGARÉ</fullName>
            </value>
            <value>
                <fullName>PAGO CERTI</fullName>
            </value>
            <value>
                <fullName>RECIBO</fullName>
            </value>
            <value>
                <fullName>SANTANDER</fullName>
            </value>
            <value>
                <fullName>TRANSF-DIV</fullName>
            </value>
            <value>
                <fullName>TRANSFER</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>PRIMAFACIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Cod_periodo_no_pago__c.field-meta.xml
<CustomField>
    <fullName>Cod_periodo_no_pago__c</fullName>
    <label>Cód. período no pago</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>¿?</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Cod_terminos_pago__c.field-meta.xml
<CustomField>
    <fullName>Cod_terminos_pago__c</fullName>
    <label>Cód, términos pago</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>000</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>007</fullName>
            </value>
            <value>
                <fullName>010</fullName>
            </value>
            <value>
                <fullName>015</fullName>
            </value>
            <value>
                <fullName>0X47</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>1050</fullName>
            </value>
            <value>
                <fullName>10X30</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>1110</fullName>
            </value>
            <value>
                <fullName>11X30</fullName>
            </value>
            <value>
                <fullName>12 BONOS</fullName>
            </value>
            <value>
                <fullName>1200</fullName>
            </value>
            <value>
                <fullName>12X30</fullName>
            </value>
            <value>
                <fullName>140</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>150</fullName>
            </value>
            <value>
                <fullName>15X30</fullName>
            </value>
            <value>
                <fullName>170</fullName>
            </value>
            <value>
                <fullName>1800</fullName>
            </value>
            <value>
                <fullName>18MENS</fullName>
            </value>
            <value>
                <fullName>20+15</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>20X30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <description>Código postal facturación</description>
    <label>Código Postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/D_as_pago__c.field-meta.xml
<CustomField>
    <fullName>D_as_pago__c</fullName>
    <label>Días pago</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email3__c.field-meta.xml
<CustomField>
    <fullName>Email3__c</fullName>
    <description>Correo electrónico principal de la cuenta, es el primero que se inserta.</description>
    <label>Email3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>IBAN de la cuenta</description>
    <label>IBAN</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_Fiscal__c.field-meta.xml
<CustomField>
    <fullName>Id_Fiscal__c</fullName>
    <inlineHelpText>DNI/NIE/CIF</inlineHelpText>
    <label>ID Fiscal</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente Navision</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile_Phone_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone_No__c</fullName>
    <label>Teléfono secundario</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <description>Códigos de los países a enviar a Navisio</description>
    <label>Pais</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
                <default>true</default>
                <label>AE</label>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>DZ</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>EE</fullName>
            </value>
            <value>
                <fullName>EL</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>ET</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>FJ</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Poblacion_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Poblacion_Facturacion__c</fullName>
    <label>Población</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Procede_de_conversion__c.field-meta.xml
<CustomField>
    <fullName>Procede_de_conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox para comprobar en el trigger de oportunidad desde donde se ha creado</description>
    <label>Procede de conversión</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Alava/Araba</fullName>
                <label>Álava/Araba</label>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Bizkaia/Vizcaya</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Caceres</fullName>
                <label>Cáceres</label>
            </value>
            <value>
                <fullName>Cadiz</fullName>
                <label>Cádiz</label>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ceuta</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>Las Palmas</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Recibir_factura_por_mail__c.field-meta.xml
<CustomField>
    <fullName>Recibir_factura_por_mail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recibir factura por mail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Usuario_Web_Clientes__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Web_Clientes__c</fullName>
    <description>Nuevo campo utilizado para el login en webClientes</description>
    <label>Usuario Web Clientes</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Individual/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Identifica el correo electrónico del individuo</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/AccountUtil.cls
public with sharing class AccountUtil 
{
    private static Map<Id, Individual> personasMap
    {
        get
        {
            if(personasMap == null)
            {
                personasMap = new Map<Id, Individual>();
            }
            return personasMap;
        }
        set;
    }

    private static Map<Id, List<Contact>> contactosMap
    {
        get
        {
            if(contactosMap == null)
            {
                contactosMap = new Map<Id, List<Contact>>();
            }
            return contactosMap;
        }
        set;
    }

    private static Map<Id, Individual> personasToUpdate
    {
        get
        {
            if(personasToUpdate == null)
            {
                personasToUpdate = new Map<Id, Individual>();
            }
            return personasToUpdate;
        }
        set;
    }

    // La variable semáforo evitará que al actualizar un registro y sincronizarlo con Navision, al volver a actualizar la fecha
    // de última actualización o ID de Navision, se vuelva a tratar de sincronizar (bucle infinito)
    public static Boolean semaforoUpdate = true;

    // Método para mandar a sincronizar a Navision los clientes cuando han sido actualizados/insertados
    // y son del tipo de registro cliente existente o tienen ID de Navision
    //@rcastanos (05/06/2019) Modificación para obtener el tipo de registro mediante la propiedad objectsRecordTypesMap
    public static void SincronizarCliente(list<Account> newList, Map<Id,Account> oldMap)
    {
        //System.debug('## before SincronizarCliente semaforoUpdate: ' + semaforoUpdate);
        if (semaforoUpdate) 
        {         
            // Recuperamos el tipo de registro "Cliente existente"
            RecordType rts = Util.objectsRecordTypesMap.get('Account').get('Cliente_existente');

            if (newList != null)
            {
                List<String> clientesSync = new List<String>();
                
                for (Account cliente:newList)
                {
                    // Si son del tipo de registro Cliente existente o tienen un ID de Navision los mandamos a sincronizar
                    // Se hace doble validación, se comprueba que sea de tipo de registro Cliente existente y que tenga algún contrato Activado
                    // Validamos que se haya producido algun cambio en los campos a enviar para enviarlos
                    //System.debug('$$ - sincronizarCliente cliente.IBAN__c : '+cliente.IBAN__c);
                    //System.debug('$$ - sincronizarCliente oldMap.IBAN__c : '+oldMap.get(cliente.Id).IBAN__c);
                    if( 
                        (cliente.RecordTypeId == rts.Id) && 
                        !String.IsEmpty(cliente.Id_Navision__c) && 
                        (
                            cliente.Id_Navision__c              != oldMap.get(cliente.Id).Id_Navision__c || 
                            cliente.Calle_Facturacion__c        != oldMap.get(cliente.Id).Calle_Facturacion__c || 
                            cliente.Calle_2__c                  != oldMap.get(cliente.Id).Calle_2__c || 
                            cliente.Recibir_factura_por_mail__c != oldMap.get(cliente.Id).Recibir_factura_por_mail__c || 
                            cliente.Poblacion_Facturacion__c    != oldMap.get(cliente.Id).Poblacion_Facturacion__c || 
                            cliente.Codigo_Postal__c            != oldMap.get(cliente.Id).Codigo_Postal__c || 
                            cliente.Provincia__c                != oldMap.get(cliente.Id).Provincia__c || 
                            cliente.Pais__c                     != oldMap.get(cliente.Id).Pais__c || 
                            cliente.Phone                       != oldMap.get(cliente.Id).Phone || 
                            cliente.Mobile_Phone_No__c          != oldMap.get(cliente.Id).Mobile_Phone_No__c || 
                            cliente.Fax                         != oldMap.get(cliente.Id).Fax || 
                            cliente.Id_Fiscal__c                != oldMap.get(cliente.Id).Id_Fiscal__c || 

                            //gserrano 28/01/2019 se dejan de sincronizar estos campos a petición de Sandra
                            /*cliente.Cod_terminos_pago__c        != oldMap.get(cliente.Id).Cod_terminos_pago__c || 
                            cliente.Cod_forma_pago__c           != oldMap.get(cliente.Id).Cod_forma_pago__c || 
                            cliente.Cod_terminos_pago__c        != oldMap.get(cliente.Id).Cod_terminos_pago__c ||
                            cliente.Cod_terminos_pago__c        != oldMap.get(cliente.Id).Cod_terminos_pago__c || 
                            cliente.Cod_terminos_pago__c        != oldMap.get(cliente.Id).Cod_terminos_pago__c ||*/
                            (cliente.IsPersonAccount &&  (cliente.FirstName  != oldMap.get(cliente.Id).FirstName || cliente.LastName != oldMap.get(cliente.Id).LastName))|| 
                            (!cliente.IsPersonAccount && cliente.Name       != oldMap.get(cliente.Id).Name)||
                            cliente.E_mail__c                   != oldMap.get(cliente.Id).E_mail__c || 
                            cliente.Email2__c                   != oldMap.get(cliente.Id).Email2__c || 
                            cliente.Email3__c                   != oldMap.get(cliente.Id).Email3__c || 
                            //gserrano 28/01/2019 se dejan de sincronizar estos campos a petición de Sandra
                            /*cliente.D_as_pago__c              != oldMap.get(cliente.Id).D_as_pago__c || 
                            cliente.Cod_periodo_no_pago__c      != oldMap.get(cliente.Id).Cod_periodo_no_pago__c ||*/
                            cliente.OwnerId                     != oldMap.get(cliente.Id).OwnerId ||
                            //pmartin 01/04/2020 se añade el campo IBAN__c
                            cliente.IBAN__c                     != oldMap.get(cliente.Id).IBAN__c
                        )
                    )
                    {
                        clientesSync.add(cliente.Id);
                    }
                }
                // Enviamos los clientes correspondientes a sincronizar
                if(clientesSync.size() > 0) 
                    SyncNav.SincronizarClientesFuture(clientesSync);
            }
        }
        //System.debug('## after SincronizarCliente semaforoUpdate: ' + semaforoUpdate);
    }


    /**
    * Metodo encargado de marcar la variable de clase de oportunidad para saber que no hay que crear funciones de contacto cuando procede de conversion
    * @author rfernandez (16/02/2017)
    * @modificaciones 
    */
    public static void comprobarProcedenciaDeConversion(List<Account> listaCuentas)
    {
        for(Account cuenta: listaCuentas)
        {
            if(cuenta.Procede_de_conversion__c == true)
            {
                OpportunityUtil.semaforoCreacionFuncionesDeContacto = false;
                cuenta.Procede_de_conversion__c = false;
            }
        }
    }


    /**
    * Metodo encargado de actualizar el campo Usuario_Web_Clientes__c con el valor del campo Id_Fiscal__c
    * @author rfernandez (31/05/2017)
    * @modificaciones 
    */
    public static void actualizarUsuarioWebClientes(List<Account> listaCuentas)
    {
        for(Account cuenta: listaCuentas)
        {
            if(String.isNotBlank(cuenta.Id_Fiscal__c) && String.isEmpty(cuenta.Usuario_Web_Clientes__c))//Si hay algun valor en el id fiscal lo pasamos a Usuario_Web_Clientes__c
            {
                cuenta.Usuario_Web_Clientes__c = cuenta.Id_Fiscal__c;
            }
        }
    }


    /**
    *   Recupera los contactos asociados a cuentas de empresa
    **
    *  @author rfernandez
    *  @date 25/07/2018
    *  @param list<Account> accountList - Lista de cuentas
    *  @where Bulk after 
    *  @change rcastanos (05/06/2016) Modificación para obtener el tipo de registro mediante la propiedad objectsRecordTypesMap
    */
    public static void recuperarContactos(List<Account> accountList, Map<Id, Account> oldMap)
    {
        
        Set<Id> cuentasEmpresaList = new Set<Id>();

        for(Account cuenta : accountList)
        {
            RecordType clienteExistente = Util.objectsRecordTypesMap.get('Account').get('Cliente_existente');
            RecordType clientePotencial = Util.objectsRecordTypesMap.get('Account').get('Cliente');

            if(cuenta.RecordTypeId == clienteExistente.Id && oldMap.get(cuenta.Id).RecordTypeId == clientePotencial.Id)
            {
                cuentasEmpresaList.add(cuenta.Id);
            }
        }

        for(Contact contacto : [SELECT Id, IndividualId, AccountId FROM Contact WHERE AccountId IN: cuentasEmpresaList])
        {
            if(!contactosMap.containsKey(contacto.AccountId))
            {
                if (!contactosMap.containsKey(contacto.AccountId))
                {
                    contactosMap.put(contacto.AccountId, new List<Contact>());
                }
                contactosMap.get(contacto.AccountId).add(contacto);
            }
        }
    }

    /**
    *   Recupera los registros Persona a los que estan asociados los contactos de cuentas de empresa
    **
    *  @author rfernandez
    *  @date 25/07/2018
    *  @param list<Account> accountList - Lista de cuentas
    *  @where Bulk after 
    */
    public static void recuperarPersonasDeContactos(List<Account> accountList, Map<Id, Account> oldMap)
    {
        if(!contactosMap.isEmpty())
        {
            Set<Id> personasIdsList = new Set<Id>();
            for(Id idCuenta : contactosMap.keySet())
            {
                for(Contact contacto : contactosMap.get(idCuenta))
                {
                    personasIdsList.add(contacto.IndividualId);
                }
            }

            for(Individual persona : [SELECT Id, Email__c, FirstName, LastName FROM Individual WHERE Id IN: personasIdsList])
            {
                personasMap.put(persona.Id, persona);
            }    
        }
    }

    /**
    *   Si una cuenta pasa a ser cliente existente se deben marcar los checks de preferencias de su individual relacionado
    *       - Si es empresa, se marcarán los individuals a los que estan asociados los contactos
    *  @author rfernandez
    *  @date 25/07/2018
    *  @param list<Account> accountList - Lista de cuentas
    *  @where After update 
    *  @change rcastanos (05/06/2019) Se modifica para recuperar los tipos de registro a través de la nueva propiedad. Se elimina toda referencia a cuentas personales
    */
    public static void aceptarPreferenciasPorClienteExistente(List<Account> accountList, Map<Id, Account> oldMap)
    {
        Map<Id, Account> cuentasEmpresaMap     = new Map<Id, Account>();

        //Recuperamos las cuentas a tratar
        for(Account cuenta : accountList)
        {
            RecordType clienteExistente = Util.objectsRecordTypesMap.get('Account').get('Cliente_existente');
            RecordType clientePotencial = Util.objectsRecordTypesMap.get('Account').get('Cliente');
            
            if(cuenta.RecordTypeId == clienteExistente.Id && oldMap.get(cuenta.Id).RecordTypeId == clientePotencial.Id)
            {
                cuentasEmpresaMap.put(cuenta.Id, cuenta);
            }
        }

        //Gestionamos las cuentas empresariales
        if(!cuentasEmpresaMap.isEmpty())
        {
            for(Account cuenta : cuentasEmpresaMap.values())
            {
                if(!contactosMap.isEmpty() && contactosMap.containsKey(cuenta.Id))
                {
                    for(Contact contacto : contactosMap.get(cuenta.Id))
                    {
                        if(contacto.IndividualId != null && personasMap.containsKey(contacto.IndividualId))
                        {
                            aceptarPreferenciasPorClienteExistente2(contacto.IndividualId);
                        }
                    }
                }
            }
        }
    }
    
    public static void aceptarPreferenciasPorClienteExistente2(Id recordId)
    {
        Individual persona;
        if(personasToUpdate.containsKey(recordId))
        {
            persona =  personasToUpdate.get(recordId);
        }else{
            persona =  personasMap.get(recordId);
        }
        persona.Fecha_promociones__c        = System.now();
        persona.Promociones__c              = true;
        persona.Fecha_encuestas__c          = System.now();
        persona.Encuestas_satisfaccion__c   = true;

        personasToUpdate.put(persona.Id, persona);
    }

    /**
    *   Execute DMLs after data process
    **
    *  @author rfernandez
    *  @date 17/05/2018    
    *  @where andFinally
    *  @change rcastanos (05/06/2019) Se elimina personasToDelete
    */
    public static void insertUpdateDeleteRecords()
    {
        
        if(!personasToUpdate.isEmpty())
        {   
            update personasToUpdate.values();
        }

        personasToUpdate.clear();
    }

    /**
     * Comprobación de IBAN de cuenta a través de la validación de los dígitos de control
     * 
     * @author pmartin
     * @date 18/02/2020
     * @where before insert / before update
     */
    public static void validarIBAN( Account acc, String oldIBAN)
    {
        System.debug('$$ - validarIBAN accountIBAN : '+acc.IBAN__c);
        if(!String.isEmpty(acc.IBAN__c))
        {
            if(acc.IBAN__c.length() == 24)
            {
                String entidad = acc.IBAN__c.substring(4,8);
                String sucursal = acc.IBAN__c.substring(8,12);
                String digitosDeControl = acc.IBAN__c.substring(12,14);
                String numCC = acc.IBAN__c.substring(14,acc.IBAN__c.length());
                
                try
                {   
                    
                    if (entidad.length()!=4 && sucursal.length()!=4)
                    {
                        Log__c log = new Log__c (Name ='AccountUtil', Descripcion__c ='Validación de IBAN '+acc.IBAN__c+' incorrecta para la cuenta '+acc.Name+': La longitud del código de entidad y sucursal son incorrectos (diferente a 4). IBAN ANTERIOR : '+oldIBAN);
                        insert log;
                        if(String.isEmpty(oldIBAN))
                        {
                            acc.IBAN__c = '';
                            //System.debug('$$ - validarIBAN vacío por fallo de IBAN (entidad)');
                        }
                        else
                        {
                            acc.IBAN__c = oldIBAN;
                            //System.debug('$$ - validarIBAN valor previo por fallo (entidad) : '+acc.IBAN__c);
                        }
                    }
                    else
                    {                           
                        Integer digcontrol1 = 0;
                        Integer digcontrol2 = 0;
                        
                        digcontrol1 =   Integer.valueOf(entidad.substring(0, 1)) * 4 + 
                                        Integer.valueOf(entidad.substring(1, 2))* 8 + 
                                        Integer.valueOf(entidad.substring(2, 3))* 5 + 
                                        Integer.valueOf(entidad.substring(3, 4)) * 10;
                        
                        digcontrol1 =   digcontrol1 + 
                                        Integer.valueOf(sucursal.substring(0, 1))* 9 + 
                                        Integer.valueOf(sucursal.substring(1, 2))* (8 - 1) + 
                                        Integer.valueOf(sucursal.substring(2, 3))* 3 + 
                                        Integer.valueOf(sucursal.substring(3, 4)) * (5 + 1);
                                        
                        digcontrol1 = math.mod(digcontrol1,(10 + 1));
                        
                        if (digcontrol1 != 0) {
                            digcontrol1 = (10 + 1) - digcontrol1;
                        }
                        
                        if (digcontrol1 == 10) {
                            digcontrol1 = 1;
                        }
                        
                        digcontrol2 =   Integer.valueOf(numCC.substring(0, 1))* 1 + 
                                        Integer.valueOf(numCC.substring(1, 2))* 2 + 
                                        Integer.valueOf(numCC.substring(2, 3))* 4 + 
                                        Integer.valueOf(numCC.substring(3, 4))* 8 + 
                                        Integer.valueOf(numCC.substring(4, 5))* 5 + 
                                        Integer.valueOf(numCC.substring(5, 5 + 1))* 10 + 
                                        Integer.valueOf(numCC.substring((5 + 1), 5 + 2))* 9 + 
                                        Integer.valueOf(numCC.substring((5 + 2), 8))* (5 + 2) + 
                                        Integer.valueOf(numCC.substring(8, 9))* 3 + 
                                        Integer.valueOf(numCC.substring(9, 10)) * (5 + 1);
                
                        digcontrol2 = math.mod(digcontrol2,(10 + 1));
                        
                        if (digcontrol2 != 0) {
                            digcontrol2 = (10 + 1) - digcontrol2;
                        }
                        
                        if (digcontrol2 == 10) {
                            digcontrol2 = 1;
                        }
    
                        String digControl = String.valueOf(digcontrol1) + String.valueOf(digcontrol2);
                        //System.debug(digControl);
                        if( !(digControl == digitosDeControl))
                        {
                            Log__c log = new Log__c(Name ='AccountUtil', Descripcion__c='Validación de IBAN '+acc.IBAN__c+' incorrecta para la cuenta '+ acc.Id +': No ha pasado la validación del Dígito de Control: '+ acc.IBAN__c+' -- '+digitosDeControl+' : '+digControl+'. IBAN ANTERIOR : '+oldIBAN);
                            insert log;
                            if(String.isEmpty(oldIBAN))
                            {
                                acc.IBAN__c = '';
                                //System.debug('$$ - validarIBAN vacío por fallo de IBAN (digitos de control)');
                            }
                            else
                            {
                                acc.IBAN__c = oldIBAN;
                                //System.debug('$$ - validarIBAN valor previo por fallo (digitos de control): '+acc.IBAN__c);
                            }
                        }
                    }          
                }
                catch (Exception ex)
                {
                    if(ex.getMessage().contains('out of bounds'))
                    {
                        Log__c log = new Log__c(Name ='AccountUtil', Descripcion__c='Validación de IBAN '+acc.IBAN__c+' incorrecta para la cuenta '+ acc.Name +': Entidad u Oficina incorrectas. IBAN ANTERIOR : '+oldIBAN);
                        insert log;
                        if(String.isEmpty(oldIBAN))
                        {
                            acc.IBAN__c = '';
                            //System.debug('$$ - validarIBAN vacío por fallo (excepcion): '+acc.IBAN__c);
                        }
                        else
                        {
                            acc.IBAN__c = oldIBAN;
                            //System.debug('$$ - validarIBAN valor previo por fallo (excepcion) : '+acc.IBAN__c);
                        }
                    }
                    else
                    {
                        Log__c log = new Log__c (Name ='AccountUtil', Descripcion__c ='Validación de IBAN '+acc.IBAN__c+' incorrecta para la cuenta '+acc.Name+': '+ex.getMessage()+'. IBAN ANTERIOR : '+oldIBAN);
                        insert log;
                        if(String.isEmpty(oldIBAN))
                        {
                            acc.IBAN__c = '';
                            //System.debug('$$ - validarIBAN valor previo por fallo (otros): '+acc.IBAN__c);
                        }
                        else
                        {
                            acc.IBAN__c = oldIBAN;
                            //System.debug('$$ - validarIBAN valor previo por fallo (otros): '+acc.IBAN__c);
                        }
                    }     
                }
            }else
            {
                Log__c log = new Log__c(Name='AccountUtil', Descripcion__c ='Validación de IBAN '+acc.IBAN__c+' incorrecta para la cuenta '+ acc.Name +': Longitud del IBAN incorrecta (diferente a 24). IBAN ANTERIOR : '+oldIBAN);    
                insert log;
                if(String.isEmpty(oldIBAN))
                {
                    acc.IBAN__c = '';
                    //System.debug('$$ - validarIBAN valor previo por fallo (longitud iban): '+acc.IBAN__c);
                }
                else
                {
                    acc.IBAN__c = oldIBAN;
                    //System.debug('$$ - validarIBAN valor previo por fallo (longitud iban): '+acc.IBAN__c);
                }
            }  
        }
    }

    /**
     * Ejecuta validación de IBAN para cada cuenta de la lista del trigger
     * 
     * @author pmartin
     * @date 18/02/2020
     * @where before insert / before update
     */

    public static void procesarCuentasTriggerParaValidarIBAN(List<Account> cuentas, Map<Id, Account> oldMap)
    {
        for(Account acc : cuentas)
        {
            String iban = '';
            //si existe un mapa de registros anteriores (caso update)
            if(oldMap != null)
            {
                Account mapAccount = oldMap.get(acc.Id);
                if(acc.IBAN__c != mapAccount.IBAN__c)
                {
                    // asignamos el iban antiguo a una variable 
                    iban = mapAccount.IBAN__c;  
                }
            }
            System.debug('$$ - procesarCuentavalidarIBAN : '+acc.IBAN__c);
            System.debug('$$ - procesarCuentavalidarIBAN from oldMap : '+iban);
            //si no (caso insert), pasa vacío
            validarIBAN(acc, iban);
        }
    }

    /**
     * modifica el valor del campo Cuenta_bloqueada_cambio__c cuando el cambio va a ocurrir desde el código
     * 
     * @author pmartin
     * @date 05/03/2020
     * @event before
     */

    /*public static void bloquearActualizacionCuenta(List<Account> cuentas)
    {
        if(cuentas.size() > 0 )
       {
            List<Account> cuentasUpdate = new List<Account>();

            for(Account cuenta : cuentas)
            {
                cuenta.Cuenta_bloqueada_cambio__c = true;
            }
        }
    }*/

    /**
     * establece el valor del campo Origen_de_modificacion__c en función de si el cambio procede de la interfaz o del código
     * 
     * @author pmartin
     * @date 05/03/2020
     * @event after
     */

     public static void definirOrigenDeModificacion(List<Account> cuentasTrigger, map<Id,Account> oldMap)
     {
      
        System.debug('en el trigger de definir '+cuentasTrigger[0].Cuenta_actualizada_desde_codigo__c);
        if(cuentasTrigger.size() > 0)
        {
            //List<Account> cuentas = [select Id, Cuenta_actualizada_desde_codigo__c, Origen_de_modificacion__c from Account where Id in: cuentasTrigger];
            List<Account> cuentas = cuentasTrigger;
            if(cuentas.size() > 0)
            {
                //List<Account> cuentasUpdate = new List<Account>();
                // for(Account c : cuentas)
                // {
                //     // se borran las cuentas que no estén en el trigger
                //     for(Account a : cuentasTrigger)
                //     {
                //         if(c.Id == a.Id)
                //         {
                //             cuentasUpdate.add(c);
                //         }
                //     }
                // }

                // tras filtrar las cuentas y dejar sólo las que están en el trigger se continúa con la ejecución
                for(Account c : cuentas)
                {
                    //System.debug(c.Cuenta_bloqueada_cambio__c);
                    System.debug(c.Cuenta_actualizada_desde_codigo__c);

                    if(c.IBAN__c != oldMap.get(c.Id).IBAN__c)
                    {

                        if(c.Cuenta_actualizada_desde_codigo__c)
                        {
                            c.Origen_de_modificacion__c = 'Salesforce';
                            
                        }
                        else
                        {
                            c.Origen_de_modificacion__c = 'Web';
                            c.Cuenta_actualizada_desde_codigo__c = true;
                        }
                    }
                    else
                    {
                        c.Origen_de_modificacion__c = oldMap.get(c.Id).Origen_de_modificacion__c;
                    }   
                }
            }
        }
     }

}