force-app/main/default/objects/Account/fields/Campa_a_relacionada__c.field-meta.xml
<CustomField>
    <fullName>Campa_a_relacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña relacionada</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Entrega_de_producto__c.field-meta.xml
<CustomField>
    <fullName>Entrega_de_producto__c</fullName>
    <label>Entrega de producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automática</fullName>
            </value>
            <value>
                <fullName>Semi-automática</fullName>
            </value>
            <value>
                <fullName>Bajo pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>IBAN de la cuenta</description>
    <label>IBAN</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/N_mero_cliente_anterior__c.field-meta.xml
<CustomField>
    <fullName>N_mero_cliente_anterior__c</fullName>
    <label>Número cliente anterior</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Switch__mdt/Configuration_Switch__mdt.object-meta.xml
<CustomObject>
    <description>Metadatos para controlar la ejecución de los triggers</description>
    <label>Configuration Switch</label>
    <pluralLabel>Configuration Switch</pluralLabel>
</CustomObject>

force-app/main/default/objects/Configuration_Switch__mdt/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indica si el trigger está activo o no</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Switch__mdt/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Descripción del trigger</description>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Switch__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Nombre del trigger</description>
    <label>Nombre de Trigger Setup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Constantes_NewSales__mdt/Constantes_NewSales__mdt.object-meta.xml
<CustomObject>
    <description>Constantes referentes a NewSales</description>
    <label>Constantes NewSales</label>
    <pluralLabel>Constantes NewSales</pluralLabel>
</CustomObject>

force-app/main/default/objects/Constantes_NewSales__mdt/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Constantes_WebClientes__mdt/Constantes_WebClientes__mdt.object-meta.xml
<CustomObject>
    <description>Constantes referentes a WebClientes</description>
    <label>Constantes WebClientes</label>
    <pluralLabel>Constantes WebClientes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Contacto_principal__c.field-meta.xml
<CustomField>
    <fullName>Contacto_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contacto principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Campa_a_relacionada__c.field-meta.xml
<CustomField>
    <fullName>Campa_a_relacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaña relacionada</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Consumo_previsto_tons__c.field-meta.xml
<CustomField>
    <fullName>Consumo_previsto_tons__c</fullName>
    <label>Consumo contratado</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Direccion_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Direccion_de_entrega__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dirección de entrega</label>
    <referenceTo>Direcci_n_de_entrega__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/e_mail__c.field-meta.xml
<CustomField>
    <fullName>e_mail__c</fullName>
    <label>e-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Entrega_de_producto__c.field-meta.xml
<CustomField>
    <fullName>Entrega_de_producto__c</fullName>
    <label>Entrega de producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automática</fullName>
            </value>
            <value>
                <fullName>Semi-automática</fullName>
            </value>
            <value>
                <fullName>Bajo pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/Direcci_n_de_entrega__c.object-meta.xml
<CustomObject>
    <description>Ship to address</description>
    <label>Dirección de entrega</label>
    <nameField>
        <displayFormat>STA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones de entrega</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Identifica el correo electrónico del individuo</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Integracion_Navision__mdt/Integracion_Navision__mdt.object-meta.xml
<CustomObject>
    <description>Parámetros de configuración de la integración con Navision</description>
    <label>Integración Navision</label>
    <pluralLabel>Integraciones Navision</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integracion_Navision__mdt/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <description>Valor de la propiedad</description>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Campo creado para poder hacer el mapeo en la conversión de candidato a oportunidad (por defecto el campo estándar Descrption va a la cuenta).</description>
    <label>Descripción</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>Este campo se usa para los leads que vienen del formulario de cambio de titualar.</description>
    <label>IBAN</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/N_mero_cliente_anterior__c.field-meta.xml
<CustomField>
    <fullName>N_mero_cliente_anterior__c</fullName>
    <description>Número cliente anterior</description>
    <label>Número cliente anterior</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogNavision__mdt/LogNavision__mdt.object-meta.xml
<CustomObject>
    <label>LogNavision</label>
    <pluralLabel>LogsNavision</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogNavision__mdt/fields/Activado__c.field-meta.xml
<CustomField>
    <fullName>Activado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parametros__mdt/Parametros__mdt.object-meta.xml
<CustomObject>
    <description>Parámetros de configuración general</description>
    <label>Parámetros</label>
    <pluralLabel>Parametros</pluralLabel>
</CustomObject>

force-app/main/default/objects/Solicitud_de_revision__mdt/Solicitud_de_revision__mdt.object-meta.xml
<CustomObject>
    <description>Metadato relacionado con la acción &apos;Solicitud de revisión</description>
    <label>Solicitud de revision</label>
    <pluralLabel>Solicitudes de revision</pluralLabel>
</CustomObject>

force-app/main/default/objects/Solicitud_de_revision__mdt/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <description>Asunto de la tarea</description>
    <label>Asunto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_revision__mdt/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Descripción de la tarea</description>
    <label>Descripción</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_revision__mdt/fields/Persona_asignada__c.field-meta.xml
<CustomField>
    <fullName>Persona_asignada__c</fullName>
    <description>ID de Salesforce de la persona asignada a la tarea</description>
    <label>Persona asignada</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_revision__mdt/fields/Tipo_de_la_tarea__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_la_tarea__c</fullName>
    <label>Tipo de la tarea</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Otros</fullName>
                <default>true</default>
                <label>Otros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Util.cls
public with sharing class Util 
{
	public class customException extends Exception {}

    //gserrano 10-1-2019
    /*Recupera el valor para activar logs de metadatos personalizados*/
    public static Boolean LogsNavisionActivados 
    {
        get
        {
            if(LogsNavisionActivados == null)
            {
                LogsNavisionActivados = Boolean.valueOf([SELECT Activado__c FROM LogNavision__mdt LIMIT 1].Activado__c);
            }
            return LogsNavisionActivados;
        }
        set;
    } 

   	/*Recupera el hash id de metadatos personalizados*/
    public static String hashID
    {
        get
        {
            if(hashID == null)
            {
                hashID = String.valueOf([SELECT Valor__c FROM Parametros__mdt WHERE DeveloperName = 'Hash_Id' LIMIT 1]);
            }
            return hashID;
        }
        set;
    }

    //Propiedad para la obtención de valores para la integración con Navision
    //@rcastanos (04/06/2019)
    public static Map<String, String> valoresIntegracionNavision
    {
        get
        {   
            //Si no hemos recuperado todavía los valores lo hacemos y preparamos el mapa
            if(valoresIntegracionNavision == null)
            {
                valoresIntegracionNavision = new Map<String, String>();

                //Recuperamos todos los metadatos
                List<Integracion_Navision__mdt> integracionNavisionMetadatos = [SELECT MasterLabel, Valor__c FROM Integracion_Navision__mdt];

                //Recorremos todos los metadatos que hemos recuperado para generar el mapa
                for(Integracion_Navision__mdt registro : integracionNavisionMetadatos)
                {
                    valoresIntegracionNavision.put(registro.MasterLabel, registro.Valor__c);
                }
            }

            return valoresIntegracionNavision; 
        }

        set;
    }

    //Propiedad para saber si estamos en una sandbox o no
    //@rcastanos (05/06/2019)
    public static Boolean runningInASandbox
    {
        get
        {
            if(runningInASandbox == null)
            {
                runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
            }
            return runningInASandbox;
        }
        set;
    }

    //Propiedad para la obtención de valores para la activación/desactivación de los triggers
    //@rcastanos (04/06/2019)
    public static Map<String, Configuration_Switch__mdt> configurationSwitchMap
    {
        get
        {   
            //Si no hemos recuperado todavía los valores lo hacemos y preparamos el mapa
            if(configurationSwitchMap == null)
            {
                configurationSwitchMap = new Map<String, Configuration_Switch__mdt>();

                //Recuperamos todos los metadatos
                List<Configuration_Switch__mdt> triggersMetadatos = [SELECT DeveloperName, Name__c, Activo__c FROM Configuration_Switch__mdt];

                //Recorremos todos los metadatos que hemos recuperado para generar el mapa
                for(Configuration_Switch__mdt registro : triggersMetadatos)
                {
                    configurationSwitchMap.put(registro.Name__c, registro);
                }
            }

            return configurationSwitchMap; 
        }

        set;
    }

    //Propiedad para la obtención de un mapa que contiene todos los RecordTypes
    //@rcastanos (05/06/2019)
    public static Map<String, Map<String, RecordType>> objectsRecordTypesMap
    {
        get
        {   
            if(objectsRecordTypesMap == null)
            {    
                objectsRecordTypesMap = new Map<String, Map<String, RecordType>>();
                for(RecordType rType : [Select Id, DeveloperName, SObjectType From RecordType Order By CreatedDate ASC])
                {
                    if(!objectsRecordTypesMap.containsKey(rType.SObjectType))
                    {
                        objectsRecordTypesMap.put(rType.SObjectType, new Map<String, RecordType>());
                    }

                    if(!objectsRecordTypesMap.get(rType.SObjectType).containsKey(rType.DeveloperName))
                    {
                        objectsRecordTypesMap.get(rType.SObjectType).put(rType.DeveloperName, rType);
                    }
                }
            }

            return objectsRecordTypesMap;
        }
        set;
    }

    //Propiedad para la obtención del id de la cuenta TELPER
    //@rcastanos (05/06/2019)
    public static Id idClienteTelperWeb
    {
        get
        {   
            if(idClienteTelperWeb == null)
            {    
                List<Account> telper = [SELECT Id FROM Account WHERE Name = 'TELPER' LIMIT 1];

                if(telper != null && !telper.isEmpty())
                {
                    idClienteTelperWeb = telper[0].Id;
                }
                
            }

            return idClienteTelperWeb;
        }
        set;
    }

    //Propiedad para la obtención del id del usuario Gemma Montejano
    //@rcastanos (05/06/2019)
    public static Id idUserSolicitudDuplicadoFactura
    {
        get
        {   
            if(idUserSolicitudDuplicadoFactura == null)
            {    
                User usuario = [SELECT Id FROM User WHERE Name = 'Gemma Montejano' LIMIT 1];
                idUserSolicitudDuplicadoFactura = usuario.Id;
            }

            return idUserSolicitudDuplicadoFactura;
        }
        set;
    }

    //Propiedad para la obtención del id del usuario Eva Calabuig
    //@rcastanos (05/06/2019)
    public static Id idUserIncidencia
    {
        get
        {   
            if(idUserIncidencia == null)
            {    
                User usuario = [SELECT Id FROM User WHERE Name = 'Eva Calabuig' LIMIT 1];
                idUserIncidencia = usuario.Id;
            }

            return idUserIncidencia;
        }
        set;
    }

    //Propiedad para la obtención de constantes NewSales
    //@rcastanos (05/06/2019)
    public static Map<String, String> constantesNewSales
    {
        get
        {   
            //Si no hemos recuperado todavía los valores lo hacemos y preparamos el mapa
            if(constantesNewSales == null)
            {
                constantesNewSales = new Map<String, String>();

                //Recuperamos todos los metadatos
                List<Constantes_NewSales__mdt> constantesNewSalesMetadatos = [SELECT DeveloperName, Valor__c FROM Constantes_NewSales__mdt];

                //Recorremos todos los metadatos que hemos recuperado para generar el mapa
                for(Constantes_NewSales__mdt registro : constantesNewSalesMetadatos)
                {
                    constantesNewSales.put(registro.DeveloperName, registro.Valor__c);
                }
            }

            return constantesNewSales; 
        }

        set;
    }

    //Propiedad para la obtención de constantes WebClientes
    //@rcastanos (05/06/2019)
    public static Map<String, String> constantesWebClientes
    {
        get
        {   
            //Si no hemos recuperado todavía los valores lo hacemos y preparamos el mapa
            if(constantesWebClientes == null)
            {
                constantesWebClientes = new Map<String, String>();

                //Recuperamos todos los metadatos
                List<Constantes_WebClientes__mdt> constantesWebClientesMetadatos = [SELECT DeveloperName, Valor__c FROM Constantes_WebClientes__mdt];

                //Recorremos todos los metadatos que hemos recuperado para generar el mapa
                for(Constantes_WebClientes__mdt registro : constantesWebClientesMetadatos)
                {
                    constantesWebClientes.put(registro.DeveloperName, registro.Valor__c);
                }
            }

            return constantesWebClientes; 
        }

        set;
    }
	
    public static String calcularHash(Id identificador)
    {
        String hash = EncodingUtil.base64Encode(Crypto.generateDigest('SHA-512', Blob.valueOf(String.valueOf(identificador) + hashID)));
        return hash;
    }

    public static Map<Id, String> calcularHashMasivo(Set<Id> identificadoresList)
    {
        Map<Id, String> idHashMap = new Map<Id, String>();
        String hash;
        for(Id identificador : identificadoresList)
        {
            hash = calcularHash(identificador);
            idHashMap.put(identificador, hash);
        }
        
        return idHashMap;
    }

    public static Set<Id> recuperarRegistrosQueApuntenAPersonas(String objeto, String campo, Set<Id> personasNoEliminables,  Map<Id, Individual> personasMap)
    {
        String recordIds = '(';
        for(Id record : personasMap.keySet())
        {
            recordIds +=  '\''+String.valueOf(record)+'\', ';
        }
        recordIds = recordIds.substringBeforeLast(', '); 
        recordIds += ')';

        for(sObject persona : Database.query('SELECT Id FROM Individual WHERE Id IN (SELECT '+campo+' FROM '+objeto+') AND Id IN '+recordIds) )
        {
            if(!personasNoEliminables.contains(persona.Id))
            {
                personasNoEliminables.add(persona.Id);
            }
        }
        return personasNoEliminables;
    }

    public static String obtenerIP() 
    {
        // True-Client-IP has the value when the request is coming via the caching integration.
        String ip = ApexPages.currentPage().getHeaders().get('True-Client-IP');  

        // X-Salesforce-SIP has the value when no caching integration or via secure URL.
        if(String.isBlank(ip)) 
        {
            ip = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
        } // get IP address when no caching (sandbox, dev, secure urls)
 
        if(String.isBlank(ip)) 
        {
            ip = ApexPages.currentPage().getHeaders().get('X-Forwarded-For');
        }// get IP address from standard header if proxy in use
        //System.debug('IP '+ip);
        return ip; 
    }

    /*
    ===========================================================================================================================================================================
    * -- GENERADOR DE REGISTROS  ----------------------------------------------------------------------------------------------------------------------------------------------
    ===========================================================================================================================================================================
    */
    public static List<Lead> generarCandidatos(Integer numCandidatos, Integer inicio)
    {
        List<Lead> candidatosList = new List<Lead>();
        for(Integer i = inicio ; i < (inicio + numCandidatos) ; i++)
        {
            Lead candidato = new Lead(
                FirstName   = 'TestFirstName'+i,
                LastName    = 'TestLastName'+i,
                Email       = 'test'+i+'@test.com',
                N_mero_Cliente_Anterior__c = 1111+i
                );
            candidatosList.add(candidato);
        }
        return candidatosList;
    }

    public static List<Account> generarCuentas(Integer numCuentas, Integer inicio, Id tipoRegistro)
    {
        List<Account> cuentasList = new List<Account>();
        Account cuenta;
        for(Integer i = inicio ; i < (inicio + numCuentas) ; i++)
        {
            cuenta = new Account();

            cuenta.Name         = 'TestName'+i;
            cuenta.E_mail__c    = 'test'+i+'@test.com';
            
            cuenta.RecordTypeId = tipoRegistro;
    
            cuentasList.add(cuenta);
        }
        return cuentasList;
    }

    /**
     * genera cuentas de test con IBAN
     * 
     * @author pmartin
     * @date 18/002/2020
     */
    public static List<Account> generarCuentasConIbanCorrecto(Integer numCuentas, Integer inicio, Id tipoRegistro)
    {
        List<Account> cuentasList = new List<Account>();
        Account cuenta;
        for(Integer i = inicio ; i < (inicio + numCuentas) ; i++)
        {
            cuenta = new Account();

            cuenta.Name         = 'TestName'+i;
            cuenta.E_mail__c    = 'test'+i+'@test.com';
            /**
             * hay que generar un iban para las cuentas de test
             */
            cuenta.IBAN__c      = 'ES8921004544981234567897';
            
            cuenta.RecordTypeId = tipoRegistro;
    
            cuentasList.add(cuenta);
        }
        return cuentasList;
    }
    
    /**
     * genera cuentas de test con IBAN
     * 
     * @author pmartin
     * @date 18/002/2020
     */
    public static List<Account> generarCuentasConIbanIncorrecto(Integer numCuentas, Integer inicio, Id tipoRegistro)
    {
        List<Account> cuentasList = new List<Account>();
        Account cuenta;
        for(Integer i = inicio ; i < (inicio + numCuentas) ; i++)
        {
            cuenta = new Account();

            cuenta.Name         = 'TestName'+i;
            cuenta.E_mail__c    = 'test'+i+'@test.com';
            /**
             * hay que generar un iban para las cuentas de test
             */
            cuenta.IBAN__c      = 'ES892100454498123456789';
            
            cuenta.RecordTypeId = tipoRegistro;
    
            cuentasList.add(cuenta);
        }
        return cuentasList;
    }
    public static List<Contact> generarContactos(Integer numContactosPorCuenta, Integer inicio, List<Account> cuentasList)
    {
        List<Contact> contactosList = new List<Contact>();
        for(Account cuenta : cuentasList)
        {
            for(Integer i = inicio ; i < (inicio + numContactosPorCuenta) ; i++)
            {
                Contact contacto = new Contact(
                    FirstName   = 'TestFirstName'+i,
                    LastName    = 'TestLastName'+i,
                    Email       = 'test'+i+'@test.com',
                    AccountId   = cuenta.Id
                    // Contacto_principal__c = true
                    );
                contactosList.add(contacto);
                System.debug('+CONTACTO '+contacto);
            }
        }
        return contactosList;
    }
    public static List<Contact> generarContactosPrincipales(Integer numContactosPorCuenta, Integer inicio, List<Account> cuentasList)
    {
        List<Contact> contactosList = new List<Contact>();
        for(Account cuenta : cuentasList)
        {
            for(Integer i = inicio ; i < (inicio + numContactosPorCuenta) ; i++)
            {
                Contact contacto = new Contact(
                    FirstName   = 'TestFirstName'+i,
                    LastName    = 'TestLastName'+i,
                    Email       = 'test'+i+'@test.com',
                    AccountId   = cuenta.Id,
                    Contacto_principal__c = true
                    );
                contactosList.add(contacto);
                System.debug('+CONTACTO '+contacto);
            }
        }
        return contactosList;
    }


    public static List<Individual> generarPersonas(Integer numPersonas, Integer inicio)
    {
        List<Individual> personasList = new List<Individual>();

        for(Integer i = inicio ; i < (inicio + numPersonas) ; i++)
        {
            Individual persona = new Individual(
                FirstName   = 'TestFirstName'+i,
                LastName    = 'TestLastName'+i,
                Email__c    = 'test'+i+'@test.com'
                );
            personasList.add(persona);
        }

        return personasList;
    }

    public static List<User> generarUsuarios(Integer numUsuarios, Integer inicio,Account cuenta)
    {
        List<User> usuariosList = new List<User>();

        for(Integer i = inicio; i < numUsuarios; i++)
        {
            User user = new User(
                alias = 'test12'+1,
                email='test12'+i+'@noemail.com',
                emailencodingkey='UTF-8',
                lastname='Testing'+i,
                languagelocalekey='en_US',
                localesidkey='en_US',
                country='United States',
                IsActive =true,
                ProfileId = '00e57000001oRRD',
                timezonesidkey='America/Los_Angeles',
                username='tester'+i+'@noemail.com'
            );

            usuariosList.add(user);
        }

        return usuariosList;
    }

    public static List<Contract> generarContratos(Integer numContratos, Integer inicio, Id tipoRegistro, Direcci_n_de_entrega__c direccionEntrega, String cuentaId)
    {
        List<Contract> contratosList = new List<Contract>();

        for(Integer i = inicio; i < numContratos; i++)
        {
            Contract contrato = new Contract(
                RecordTypeId = tipoRegistro,
                AccountId = cuentaId,
                StartDate = Date.today(),
                Consumo_previsto_tons__c = 100,
                Campa_a_relacionada__c = null,
                Entrega_de_producto__c = 'Automática',
                Direccion_de_entrega__c = direccionEntrega.Id,
                Status = 'Borrador'
            );

            contratosList.add(contrato);
            
        }

        return contratosList;
    }

    public static List<Solicitud_de_revision__mdt> obtenerMetadatosRevisionInterior()
    {
        List<Solicitud_de_revision__mdt> metadatoSolicitudRevision = [select Id, Asunto__c, Descripcion__c, Persona_asignada__c, Tipo_de_la_tarea__c from Solicitud_de_revision__mdt];
        if(!metadatoSolicitudRevision.isEmpty())
        {
            return metadatoSolicitudRevision;
        }
        else
        {
            return new List<Solicitud_de_revision__mdt>();    
        }
    }
}