force-app/main/default/objects/Account/fields/Cod_forma_pago__c.field-meta.xml
<CustomField>
    <fullName>Cod_forma_pago__c</fullName>
    <label>Cód. forma pago</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12 BONOS</fullName>
            </value>
            <value>
                <fullName>ANTICIPAR</fullName>
            </value>
            <value>
                <fullName>APLAZAM</fullName>
            </value>
            <value>
                <fullName>BANKINTER</fullName>
            </value>
            <value>
                <fullName>CHEQUE</fullName>
            </value>
            <value>
                <fullName>CONF CHEQ</fullName>
            </value>
            <value>
                <fullName>CONF TRANS</fullName>
            </value>
            <value>
                <fullName>CUOTA</fullName>
            </value>
            <value>
                <fullName>DEVOLUCION</fullName>
            </value>
            <value>
                <fullName>DIA 20</fullName>
            </value>
            <value>
                <fullName>DOMI</fullName>
            </value>
            <value>
                <fullName>EFECTIVO</fullName>
            </value>
            <value>
                <fullName>GASTOS</fullName>
            </value>
            <value>
                <fullName>LA CAIXA</fullName>
            </value>
            <value>
                <fullName>PAGARÉ</fullName>
            </value>
            <value>
                <fullName>PAGO CERTI</fullName>
            </value>
            <value>
                <fullName>RECIBO</fullName>
            </value>
            <value>
                <fullName>SANTANDER</fullName>
            </value>
            <value>
                <fullName>TRANSF-DIV</fullName>
            </value>
            <value>
                <fullName>TRANSFER</fullName>
            </value>
            <value>
                <fullName>VISA</fullName>
            </value>
            <value>
                <fullName>PRIMAFACIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente Navision</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Pendiente_de_confirmar__c.field-meta.xml
<CustomField>
    <fullName>Pendiente_de_confirmar__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se marca cuando está actualizado en Salesforce y falta por enviar confirmación a Navision</description>
    <label>Pendiente de confirmar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Cod_forma_pago__c.field-meta.xml
<CustomField>
    <fullName>Cod_forma_pago__c</fullName>
    <label>Cód. forma pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RECIBO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Estado_documento__c.field-meta.xml
<CustomField>
    <fullName>Estado_documento__c</fullName>
    <label>Estado documento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pagado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fecha_registro__c.field-meta.xml
<CustomField>
    <fullName>Fecha_registro__c</fullName>
    <label>Fecha de registro</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fecha_vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vencimiento__c</fullName>
    <label>Fecha de vencimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nº Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Importe_inicial__c.field-meta.xml
<CustomField>
    <fullName>Importe_inicial__c</fullName>
    <label>Importe inicial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Importe_pendiente__c.field-meta.xml
<CustomField>
    <fullName>Importe_pendiente__c</fullName>
    <label>Importe pendiente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Numero_documento__c.field-meta.xml
<CustomField>
    <fullName>Numero_documento__c</fullName>
    <label>Nº de documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_documento__c</fullName>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Efecto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Nav2sfdc_Facturas.cls
global class Nav2sfdc_Facturas implements Schedulable 
{
	global void execute(SchedulableContext sc) 
	{
		/*try
		{
			Set<String> idsClientesNavList = new Set<String>();

			//Lanzamos la consulta
			List<> facturasNavList = NavWSUtil.peticionWSConsultarFacturas();
	     	
	     	System.debug('Facturas Recibidas: '+facturasNavList);

	     	if(facturasNavList != null && facturasNavList.size() > 0)
	     	{
	     		//Recuperamos los ids de los clientes y los metemos a un set para recuperar las cuentas a las que hacen referencia
	     		for (Schema  facturaNav: facturasNavList)
				{
					if(!String.isBlank(clienteNav.CustomerNo) && !String.isBlank(clienteNav.ShiptTo))
					{
						idsClientesNavList.add(clienteNav.CustomerNo);
					}
				}

				//Sacamos las cuentas en un mapa por Id de Navision
				Map<String, Account> cuentasMap = new Map<String, Account>();

				for(Account cuenta: [SELECT Id, Id_Navision__c FROM Account WHERE Id_Navision__c IN: idsClientesNavList])
				{   
					cuentasMap.put(cuenta.Id_Navision__c, cuenta);
				}
				System.debug('Mapa de cuentas '+cuentasMap.size());
				
				Set<Factura__c> facturasList = new Set<Factura__c>();
				Set<String> idsFacturasPendientesConfirmar = new Set<String>();
				//Volvemos a recorrer lo que hemos recuperado de navision para insertar o actualizar los registros
				for (Schema facturaNav: facturasNavList)
				{
					if(!String.isBlank(facturaNav.CustomerNo) && !cuentasMap.isEmpty() && cuentasMap.containsKey(facturaNav.CustomerNo))
					{
						Account cuentaSF = cuentasMap.get(facturaNav.CustomerNo);
						Factura__c facturaSF = new Factura__c();

						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Cod_forma_pago__c 	= facturaNav.;	
						}
						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Estado_documento__c 	= facturaNav.;	
						}
						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Fecha_registro__c 	= facturaNav.;	
						}
						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Fecha_vencimiento__c 	= facturaNav.;	
						}
						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Importe__c 			= facturaNav.;	
						}
						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Importe_inicial__c 	= facturaNav.;	
						}
						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Importe_pendiente__c 	= facturaNav.;	
						}
						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Id_Navision__c 		= facturaNav.;	
						}
						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Numero_documento__c 	= facturaNav.;	
						}
						if(!String.isBlank(facturaNav.))
						{
							facturaSF.Tipo_documento__c 	= facturaNav.;	
						}
						facturasList.add(facturaSF);
					}
				}

				if(facturasList != null && !facturasList.isEmpty())
				{
					Database.UpsertResult[] upsertResult = Database.upsert(facturasList, ,false);
										
					for(Integer i = 0; i < upsertResult.size(); i++)
			        {
			            Database.UpsertResult sr = upsertResult[i]; 
			            if(!sr.isSuccess())
			            {
			                Database.Error err = sr.getErrors()[0];
			                LogUtil.crearLog('', '', 'Factura__c', 'Sync', true);
			            } else
			            {
			            	LogUtil.crearLog('Id Salesforce: ' + facturasList[i].Id + ' Is success: ' + sr.isSuccess() + ', Is Created: ' + sr.isCreated() + ', Is Updated: ' + !sr.isCreated(), '', '', 'Sync', false);

			            	idsFacturasPendientesConfirmar.add(facturasList[i].Id_Navision__c);
			            }
			        }       
				}

	     	}else
	     	{
	     		LogUtil.crearLog('Respuesta vacia, no hay registros para actualizar. '+System.now(), 'Nav2sfdc_Facturas', '', 'Sync', false);
	     	}
		}catch(Exception e)
		{
				
		}
		finally
		{
			LogUtil.guardarLog();
        	confirmarFacturas();
        }*/
	}

    //Indicamos las facturas que faltan por confirmar, posteriormente se lanza el batch encargado de hacer la petición de la confirmación
    /*public static void actualizarConfirmacionFacturas(Set<String> idsFacturas)
    {
    	List<Factura__c> facturasList = [SELECT Pendiente_de_confirmar__c FROM Factura__c WHERE Id_Navision__c IN: idsFacturas];
    	for(Factura__c factura : facturasList)
    	{
    		factura.Pendiente_de_confirmar__c = true;
    	}
    	update facturasList;
    }

	public static void confirmarFacturas()
	{
		Database.executeBatch(new Nav2sfdc_Facturas_Confirmacion(null), 200);
	}*/
}