force-app/main/default/objects/Account/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <description>Código postal facturación</description>
    <label>Código Postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente Navision</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Alava/Araba</fullName>
                <label>Álava/Araba</label>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Bizkaia/Vizcaya</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Caceres</fullName>
                <label>Cáceres</label>
            </value>
            <value>
                <fullName>Cadiz</fullName>
                <label>Cádiz</label>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ceuta</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>Las Palmas</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/Direcci_n_de_entrega__c.object-meta.xml
<CustomObject>
    <description>Ship to address</description>
    <label>Dirección de entrega</label>
    <nameField>
        <displayFormat>STA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones de entrega</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/cuenta__c.field-meta.xml
<CustomField>
    <fullName>cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Direcciones de entrega</relationshipLabel>
    <relationshipName>Direcciones_de_entrega</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Direccion_2__c.field-meta.xml
<CustomField>
    <fullName>Direccion_2__c</fullName>
    <label>Dirección 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <label>Id Navision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Poblacion__c.field-meta.xml
<CustomField>
    <fullName>Poblacion__c</fullName>
    <label>Población</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alava/Araba</fullName>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Cáceres</fullName>
            </value>
            <value>
                <fullName>Cádiz</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ceuta</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Lleida/Lérida</fullName>
            </value>
            <value>
                <fullName>Lugo</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lectura_contador__c/Lectura_contador__c.object-meta.xml
<CustomObject>
    <description>Lecturas relacionadas con la dirección de entrega</description>
    <label>Lectura contador</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Lectura contador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lecturas contador</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lectura_contador__c/fields/Direccion_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Direccion_de_entrega__c</fullName>
    <label>Dirección de entrega</label>
    <referenceTo>Direcci_n_de_entrega__c</referenceTo>
    <relationshipLabel>Lecturas contador</relationshipLabel>
    <relationshipName>Lecturas_contador</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lectura_contador__c/fields/Lectura__c.field-meta.xml
<CustomField>
    <fullName>Lectura__c</fullName>
    <label>Lectura</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Se registran errors generados en código y el historial de sincronización con Navision</description>
    <label>Log</label>
    <nameField>
        <label>Nombre de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <description>Los de excepciones o errores de código</description>
    <label>Error</label>
</RecordType>

force-app/main/default/classes/TEST_LecturaContadorUtil.cls
@isTest
private class TEST_LecturaContadorUtil 
{
	public static Direcci_n_de_entrega__c direccion;	
	//Este metodo comprueba que se ha creado correctamente la lectura de contador. La llamada se probara en SyncNav y NavWSUtil
	//Los semaforos se utilizan para que no salte el trigger de cuenta y direccion de entrega para sincronizar el cliente
	@isTest 
	static void creacionDeLecturasCorrecta() 
	{
		prepararEntorno();

		//Creación/Insercion de lectura de contador (Solo se va a enviar 1 cada vez. No se va a hacer una insercion de varios pedidos de golpe)
		List<Lectura_contador__c> lecturasContadorList = new List<Lectura_contador__c>();
		Lectura_contador__c lecturaContador;
		for(Integer i = 0; i < 1 ; i++)
		{
			lecturaContador = new Lectura_contador__c(
				Direccion_de_entrega__c = direccion.Id,
				Lectura__c 	= 50
				);
			lecturasContadorList.add(lecturaContador);
		}

		Test.setMock(HttpCalloutMock.class, new NTLMHttpCalloutMockImpl(0));
		
		//Al hacer la insercion se envia el pedido de gas directamente a navision
		Test.startTest();
		insert lecturasContadorList;
		Test.stopTest();

		List<Lectura_contador__c> lecturasList = [SELECT Id FROM Lectura_contador__c];

		System.assertEquals(0, lecturasList.size());

		List<Log__c> logList = [SELECT Id FROM Log__c];

		System.assertEquals(0, logList.size());
	}

	//Este metodo comprueba que ha habido algun error de login
	@isTest 
	static void creacionDeLecturasErrorLogin() 
	{
		prepararEntorno();

		//Creación/Insercion de lectura de contador (Solo se va a enviar 1 cada vez. No se va a hacer una insercion de varios pedidos de golpe)
		List<Lectura_contador__c> lecturasContadorList = new List<Lectura_contador__c>();
		Lectura_contador__c lecturaContador;
		for(Integer i = 0; i < 1 ; i++)
		{
			lecturaContador = new Lectura_contador__c(
				Direccion_de_entrega__c = direccion.Id,
				Lectura__c 	= 50
				);
			lecturasContadorList.add(lecturaContador);
		}

		Test.setMock(HttpCalloutMock.class, new NTLMHttpCalloutMockImpl(1));
		
		//Al hacer la insercion se envia el pedido de gas directamente a navision
		Test.startTest();
		insert lecturasContadorList;
		Test.stopTest();

		List<Lectura_contador__c> lecturasList = [SELECT Id FROM Lectura_contador__c];

		System.assertEquals(0, lecturasList.size());

		List<Log__c> logList = [SELECT Id FROM Log__c];

		System.assertEquals(1, logList.size());
	}

	//Este metodo comprueba que ha habido algun error al enviar la lectura
	@isTest 
	static void creacionDeLecturasIncorrecta() 
	{
		prepararEntorno();

		//Creación/Insercion de lectura de contador (Solo se va a enviar 1 cada vez. No se va a hacer una insercion de varios pedidos de golpe)
		List<Lectura_contador__c> lecturasContadorList = new List<Lectura_contador__c>();
		Lectura_contador__c lecturaContador;
		for(Integer i = 0; i < 1 ; i++)
		{
			lecturaContador = new Lectura_contador__c(
				Direccion_de_entrega__c = direccion.Id,
				Lectura__c 	= 50
				);
			lecturasContadorList.add(lecturaContador);
		}

		Test.setMock(HttpCalloutMock.class, new NTLMHttpCalloutMockImpl(2));
		
		//Al hacer la insercion se envia el pedido de gas directamente a navision
		Test.startTest();
		insert lecturasContadorList;
		Test.stopTest();

		List<Lectura_contador__c> lecturasList = [SELECT Id FROM Lectura_contador__c];

		System.assertEquals(0, lecturasList.size());

		List<Log__c> logList = [SELECT Id FROM Log__c];

		System.assertEquals(1, logList.size());
	}


	public static void prepararEntorno()
	{

		RecordType tiposRegistro = Util.objectsRecordTypesMap.get('Account').get('Cliente_existente');
		
		//Creación/Insercion de cuenta
		Account cuenta = new Account();
		cuenta.Name = 'Test';
		cuenta.Id_Navision__c = 'idNav';
		cuenta.RecordTypeID = tiposRegistro.Id;
		
		AccountUtil.semaforoUpdate = false;
		insert cuenta;
		AccountUtil.semaforoUpdate = true;
		
		//Creación/Insercion de direccion de entrega
		direccion = new Direcci_n_de_entrega__c();
			
		direccion.Direccion__c = 'C/Tivoli nº28 4ºB';
		direccion.Direccion_2__c = 'C/Tivoli nº28 5ºB';
		direccion.Codigo_Postal__c = '48007';
		direccion.Poblacion__c = 'Bilbao';
		direccion.Provincia__c = 'Vizcaya';
		direccion.cuenta__c = cuenta.Id;
		direccion.Id_Navision__c = 'idNavisio';
		
		DireccionEnvioUtil.semaforoUpdate = false;
		insert direccion;
		DireccionEnvioUtil.semaforoUpdate = true;
	}
}