force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ExternalId para usar como referencia para actualización desde Sistemas externos</description>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente Navision</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/Direcci_n_de_entrega__c.object-meta.xml
<CustomObject>
    <description>Ship to address</description>
    <label>Dirección de entrega</label>
    <nameField>
        <displayFormat>STA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones de entrega</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ExternalId para referenciar el registro al realizar actualizaciones desde sistemas externos</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Id_Cliente_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Cliente_Navision__c</fullName>
    <formula>cuenta__r.Id_Navision__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Cliente Navision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <label>Id Navision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DireccionEnvioHandler.cls
/**
 * Trigger Handler for the Direcci_n_de_entrega__c SObject. This class implements the ITrigger
 * interface to help ensure the trigger code is bulkified and all in one place.
 */
public class DireccionEnvioHandler implements ITrigger
{
    
    Map<String, Account> mapaClientes = new Map<String, Account>();
    //Map<String, String> mapaRecordTypeIDs = new Map<String, String>();

    // Constructor
    public DireccionEnvioHandler() {}
 
    /**
     * bulkBefore
     *
     * These methods are called prior to execution of a BEFORE or AFTER trigger. Use this to cache
     * any data required into maps prior execution of the trigger.
     */
    public void bulkBefore(list<SObject> newList, map<Id,SObject> oldMap)
    {

    }
    
    public void bulkAfter(list<SObject> newList, map<Id,SObject> oldMap)
    {
    	DireccionEnvioUtil.loadData((List<Direcci_n_de_entrega__c>)newList, mapaClientes /*, mapaRecordTypeIDs*/);
    }
    
    /**
     * These methods ara called for records to be processed during a BEFORE 
     * trigger.
     */
    public void beforeInsert(list<SObject> newList)
    {
        
        /*CAMBIO A PEDIDO DE ALEJANDRO 14/12/2022. Cuando una DirecciondeEnvio contiene el Id_Navision e Id_Cliente_Navision se concatenan los valores en el ExternalId para realizar actuaizacion via API */
		/*for(Direcci_n_de_entrega__c iDireccion : (List<Direcci_n_de_entrega__c>) newList){
            if(String.isNotBlank(iDireccion.Id_Navision__c) && String.isNotBlank(iDireccion.Id_Cliente_Navision__c) ){
                iDireccion.ExternalId__c = iDireccion.Id_Cliente_Navision__c+'-'+iDireccion.Id_Navision__c;
            }
        }
        */
    }
    
    public void beforeUpdate(list<SObject> newList, map<Id,SObject> oldMap)
    {
        /*CAMBIO A PEDIDO DE ALEJANDRO 14/12/2022. Si hay algun cambio, y Id_Navision e Id_Cliente_Navision no son nulos, se actualiza el valor del ExternalId */
        /*for(Direcci_n_de_entrega__c iDireccion : (List<Direcci_n_de_entrega__c>) newList){
            if(String.isNotBlank(iDireccion.Id_Navision__c) && String.isNotBlank(iDireccion.Id_Cliente_Navision__c) ){
                iDireccion.ExternalId__c = iDireccion.Id_Cliente_Navision__c+'-'+iDireccion.Id_Navision__c;
            }else if(String.isBlank(iDireccion.Id_Navision__c) || String.isBlank(iDireccion.Id_Cliente_Navision__c) ){
                iDireccion.ExternalId__c = '';
            }
        }
        */
    }
    
    public void beforeDelete(map<Id,SObject> oldMap)
    {
        
    }
    
    /**
     * These methods ara called for records to be processed during a AFTER 
     * trigger.
     */ 
    public void afterInsert(list<SObject> newList)
    { 
    	//DireccionEnvioUtil.SincronizarClientes((List<Direcci_n_de_entrega__c>)newList);	
    	DireccionEnvioUtil.SincronizarClientes((List<Direcci_n_de_entrega__c>)newList, mapaClientes/*, mapaRecordTypeIDs*/);
        DireccionEnvioUtil.ComprobarContratos(newList);
        /*Se asigna como ExternalId el Id de SF */
        List<Direcci_n_de_entrega__c> updateListDirecciones = new List<Direcci_n_de_entrega__c>();
        for(Direcci_n_de_entrega__c iDireccion : (List<Direcci_n_de_entrega__c>) newList){
            updateListDirecciones.add(new Direcci_n_de_entrega__c(Id=iDireccion.Id, ExternalId__c=iDireccion.Id)); 
        }
        if(updateListDirecciones.size()>0){
            update updateListDirecciones;
        }

        
    }
     
    public void afterUpdate(list<SObject> newList, map<Id,SObject> oldMap)
    {
    	//DireccionEnvioUtil.SincronizarClientes((List<Direcci_n_de_entrega__c>)newList);	
    	DireccionEnvioUtil.SincronizarClientes((List<Direcci_n_de_entrega__c>)newList, mapaClientes/*, mapaRecordTypeIDs*/);
        DireccionEnvioUtil.ComprobarContratos(newList);
    }
     
    public void afterDelete(map<Id,SObject> oldMap)
    {
    	
    }
     
    /**
     * andFinally
     *
     * This method is called once all records have been processed by the trigger. Use this
     * method to accomplish any final operations such as creation or updates of other records.
     */
    public void andFinally()
    {
    	
    }
}