force-app/main/default/objects/Account/fields/Id_Fiscal__c.field-meta.xml
<CustomField>
    <fullName>Id_Fiscal__c</fullName>
    <inlineHelpText>DNI/NIE/CIF</inlineHelpText>
    <label>ID Fiscal</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Llamada entrante</fullName>
            </value>
            <value>
                <fullName>Online Primagas</fullName>
            </value>
            <value>
                <fullName>Prescriptor</fullName>
            </value>
            <value>
                <fullName>Instalador</fullName>
            </value>
            <value>
                <fullName>Prospección directa</fullName>
            </value>
            <value>
                <fullName>Teleprospección</fullName>
            </value>
            <value>
                <fullName>Gasindur</fullName>
            </value>
            <value>
                <fullName>GALP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estimaci_n_consumo_en_kilos__c.field-meta.xml
<CustomField>
    <fullName>Estimaci_n_consumo_en_kilos__c</fullName>
    <label>Estimación consumo en kilos</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fecha_vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia__c</fullName>
    <label>Fecha vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/NIF_CIF__c.field-meta.xml
<CustomField>
    <fullName>NIF_CIF__c</fullName>
    <label>NIF/CIF</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Llamada oficina</fullName>
            </value>
            <value>
                <fullName>Llamada call center</fullName>
            </value>
            <value>
                <fullName>Correo ordinario</fullName>
            </value>
            <value>
                <fullName>Red social</fullName>
            </value>
            <value>
                <fullName>Ferias y eventos</fullName>
            </value>
            <value>
                <fullName>Info@</fullName>
            </value>
            <value>
                <fullName>Aviso va chofer</fullName>
            </value>
            <value>
                <fullName>Avisio va PS</fullName>
            </value>
            <value>
                <fullName>Prescriptores</fullName>
            </value>
            <value>
                <fullName>Asociación gremio</fullName>
            </value>
            <value>
                <fullName>Regalo doble</fullName>
            </value>
            <value>
                <fullName>EUROS X KW</fullName>
            </value>
            <value>
                <fullName>Campaña márketing</fullName>
            </value>
            <value>
                <fullName>Prospección directa</fullName>
            </value>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>Teleprospección</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Origen_tipo_cliente__c.field-meta.xml
<CustomField>
    <fullName>Origen_tipo_cliente__c</fullName>
    <label>Origen tipo cliente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nueva creación</fullName>
            </value>
            <value>
                <fullName>Cambio botellas</fullName>
            </value>
            <value>
                <fullName>Cambio depósito REPSOL</fullName>
            </value>
            <value>
                <fullName>Cambio depósito CEPSA</fullName>
            </value>
            <value>
                <fullName>Cambio depósito BP</fullName>
            </value>
            <value>
                <fullName>Cambio depósito VITOGAS</fullName>
            </value>
            <value>
                <fullName>Cambio depósito Otro</fullName>
            </value>
            <value>
                <fullName>Cambio energía Electricidad</fullName>
            </value>
            <value>
                <fullName>Cambio energía Fuel</fullName>
            </value>
            <value>
                <fullName>Cambio energía Gasóleo</fullName>
            </value>
            <value>
                <fullName>Cambio energía Otro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Provincia_env_o__c.field-meta.xml
<CustomField>
    <fullName>Provincia_env_o__c</fullName>
    <label>Provincia envío</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MELILLA</fullName>
            </value>
            <value>
                <fullName>ÁLAVA</fullName>
            </value>
            <value>
                <fullName>ALBACETE</fullName>
            </value>
            <value>
                <fullName>ALICANTE</fullName>
            </value>
            <value>
                <fullName>ALMERÍA</fullName>
            </value>
            <value>
                <fullName>ÁVILA</fullName>
            </value>
            <value>
                <fullName>BADAJOZ</fullName>
            </value>
            <value>
                <fullName>BALEARES (ILLES)</fullName>
            </value>
            <value>
                <fullName>BARCELONA</fullName>
            </value>
            <value>
                <fullName>BURGOS</fullName>
            </value>
            <value>
                <fullName>CÁCERES</fullName>
            </value>
            <value>
                <fullName>CÁDIZ</fullName>
            </value>
            <value>
                <fullName>CASTELLÓN</fullName>
            </value>
            <value>
                <fullName>CIUDAD REAL</fullName>
            </value>
            <value>
                <fullName>CÓRDOBA</fullName>
            </value>
            <value>
                <fullName>A CORUÑA</fullName>
            </value>
            <value>
                <fullName>CUENCA</fullName>
            </value>
            <value>
                <fullName>GIRONA</fullName>
            </value>
            <value>
                <fullName>GRANADA</fullName>
            </value>
            <value>
                <fullName>GUADALAJARA</fullName>
            </value>
            <value>
                <fullName>GUIPÚZCOA</fullName>
            </value>
            <value>
                <fullName>HUELVA</fullName>
            </value>
            <value>
                <fullName>HUESCA</fullName>
            </value>
            <value>
                <fullName>JAÉN</fullName>
            </value>
            <value>
                <fullName>LEÓN</fullName>
            </value>
            <value>
                <fullName>LLEIDA</fullName>
            </value>
            <value>
                <fullName>LA RIOJA</fullName>
            </value>
            <value>
                <fullName>LUGO</fullName>
            </value>
            <value>
                <fullName>MADRID</fullName>
            </value>
            <value>
                <fullName>MÁLAGA</fullName>
            </value>
            <value>
                <fullName>VIZCAYA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TEST_BatchComprobarPresupuestosCaducados.cls
@isTest
private class TEST_BatchComprobarPresupuestosCaducados
{
	@isTest
	static void TEST_comprobarPresupuestosCaducados_Individual()
	{
		Account cuenta = new Account();
		cuenta.Name = 'Cuenta prueba';
		cuenta.Id_Fiscal__c = '11111111A';
		insert cuenta;

		//Creo un presupuesto que tenga la fecha de vigencia mayor que la actual
		Opportunity oportunidad1 = new Opportunity();
		oportunidad1.Name = 'Oportunidad prueba';
		oportunidad1.AccountId = cuenta.Id;
		oportunidad1.CloseDate = Date.today();
		oportunidad1.StageName = 'Identificada';
		oportunidad1.Estimaci_n_consumo_en_kilos__c = 10;
		insert oportunidad1;

		Quote presupuesto1 = new Quote();
		presupuesto1.Name = 'Presupuesto prueba 1';
		presupuesto1.OpportunityId = oportunidad1.Id;
		presupuesto1.Origen__c = 'web';
		presupuesto1.Origen_tipo_cliente__c = 'Cambio botellas';
		presupuesto1.Provincia_env_o__c = 'VIZCAYA';
		presupuesto1.NIF_CIF__c = '11111111A';
		presupuesto1.Status = 'Preparando';
		presupuesto1.Fecha_vigencia__c = System.today().addDays(1);
		insert presupuesto1;

		//Creo un presupuesto que NO tenga la fecha de vigencia mayor que la actual
		Opportunity oportunidad2 = new Opportunity();
		oportunidad2.Name = 'Oportunidad prueba';
		oportunidad2.AccountId = cuenta.Id;
		oportunidad2.CloseDate = Date.today();
		oportunidad2.StageName = 'Identificada';
		oportunidad2.Estimaci_n_consumo_en_kilos__c = 10;
		insert oportunidad2;

		Quote presupuesto2 = new Quote();
		presupuesto2.Name = 'Presupuesto prueba 2';
		presupuesto2.OpportunityId = oportunidad2.Id;
		presupuesto2.Origen__c = 'web';
		presupuesto2.Origen_tipo_cliente__c = 'Cambio botellas';
		presupuesto2.Provincia_env_o__c = 'VIZCAYA';
		presupuesto2.NIF_CIF__c = '11111111A';
		presupuesto2.Status = 'Preparando';
		presupuesto2.Fecha_vigencia__c = System.today().addDays(-1);
		insert presupuesto2;

		//Ejecuto el batch
        Test.StartTest();
        BatchComprobarPresupuestosCaducados batch = new BatchComprobarPresupuestosCaducados();
		Database.executeBatch(batch);     
        Test.StopTest();  

        //Compruebo que el primer presupuesto sigue en estado "Preparando" y que el segundo se
        //ha pasado a estado "Caducado"
        presupuesto1 = [SELECT Id, Name, Status FROM Quote WHERE Name=:'Presupuesto prueba 1'];
        presupuesto2 = [SELECT Id, Name, Status FROM Quote WHERE Name=:'Presupuesto prueba 2'];
        System.assertEquals(presupuesto1.Status, 'Preparando');
        System.assertEquals(presupuesto2.Status, 'Caducado');
	}	

	@isTest
	static void TEST_comprobarPresupuestosCaducados_Masivo()
	{
		Account cuenta = new Account();
		cuenta.Name = 'Cuenta prueba';
		cuenta.Id_Fiscal__c = '11111111A';
		insert cuenta;

		//Creo presupuestos que NO tenga la fecha de validez mayor que la actual
		List<Opportunity> listaOportunidades = new List<Opportunity>();
		for(Integer i=0; i<200; i++)
		{
			Opportunity oportunidad = new Opportunity();
			oportunidad.Name = 'Oportunidad prueba';
			oportunidad.AccountId = cuenta.Id;
			oportunidad.CloseDate = Date.today();
			oportunidad.StageName = 'Identificada';
			oportunidad.Estimaci_n_consumo_en_kilos__c = 10;
			listaOportunidades.add(oportunidad);
		}	
		insert listaOportunidades;

		List<Quote> listaPresupuestos = new List<Quote>();
		for(Integer i=0; i<200; i++)
		{
			Quote presupuesto = new Quote();
			presupuesto.Name = 'Presupuesto prueba';
			presupuesto.OpportunityId = listaOportunidades[i].Id;
			presupuesto.Origen__c = 'web';
			presupuesto.Origen_tipo_cliente__c = 'Cambio botellas';
			presupuesto.Provincia_env_o__c = 'VIZCAYA';
			presupuesto.NIF_CIF__c = '11111111A';
			presupuesto.Status = 'Preparando';
			presupuesto.Fecha_vigencia__c = System.today().addDays(-1);
			listaPresupuestos.add(presupuesto);
		}
		insert listaPresupuestos;

		//Ejecuto el batch
        Test.StartTest();
        BatchComprobarPresupuestosCaducados batch = new BatchComprobarPresupuestosCaducados();
		Database.executeBatch(batch);     
        Test.StopTest();  

        //Compruebo que se han pasado todos los presupuestos a estado "Caducado"
        listaPresupuestos = [SELECT Id, Name, Status FROM Quote WHERE Name=:'Presupuesto prueba'];
        System.assertEquals(listaPresupuestos.size(),200);
        for(Integer i=0; i<200; i++)
		{
			System.assertEquals(listaPresupuestos[i].Status, 'Caducado');
		}        
	}	
}