force-app/main/default/objects/Account/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <externalId>true</externalId>
    <label>Número cliente Navision</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/DateFirstFilled__c.field-meta.xml
<CustomField>
    <fullName>DateFirstFilled__c</fullName>
    <formula>Direccion_de_entrega__r.Fecha_1er_llenado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha 1er llenado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Direccion_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Direccion_de_entrega__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dirección de entrega</label>
    <referenceTo>Direcci_n_de_entrega__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Duraci_n_del_contrato_a_os__c.field-meta.xml
<CustomField>
    <fullName>Duraci_n_del_contrato_a_os__c</fullName>
    <label>Duración del contrato (años)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Estado_2__c.field-meta.xml
<CustomField>
    <fullName>Estado_2__c</fullName>
    <label>Estado 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cambio titular</fullName>
            </value>
            <value>
                <fullName>Cambio titular-renovación</fullName>
            </value>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>Reactivación</fullName>
            </value>
            <value>
                <fullName>Renovación automática</fullName>
            </value>
            <value>
                <fullName>Renovado</fullName>
            </value>
            <value>
                <fullName>Renovado-ampliación</fullName>
            </value>
            <value>
                <fullName>Renovado-Depósito propio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <label>Id Navision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/Direcci_n_de_entrega__c.object-meta.xml
<CustomObject>
    <description>Ship to address</description>
    <label>Dirección de entrega</label>
    <nameField>
        <displayFormat>STA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones de entrega</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/cuenta__c.field-meta.xml
<CustomField>
    <fullName>cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Direcciones de entrega</relationshipLabel>
    <relationshipName>Direcciones_de_entrega</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Direcci_n_de_entrega__c/fields/Id_Navision__c.field-meta.xml
<CustomField>
    <fullName>Id_Navision__c</fullName>
    <label>Id Navision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DireccionEnvioUtil.cls
public with sharing class DireccionEnvioUtil {
	
	public static Map<String, String> mapaTiposRegistro;

	// Añadimos una variable semáforo para evitar las llamadas en bucle a sincronización de registros con Navision dado que tras
	// la sincronización se actualiza el ID de Navision y la última fecha de sincronización
	public static Boolean semaforoUpdate = true;

	public static void loadData(list<Direcci_n_de_entrega__c> newList, map<String, Account> mapaClientes /*, map<String, String> mapaRecordTypeIDs*/ )
	{
		System.Debug('## before loadData mapaCLientes: ' + mapaClientes);
		if (newList != null)
		{
			List<String> clienteIDs = new List<String>();
			for (Direcci_n_de_entrega__c de:newList)
			{
				clienteIDs.add(de.cuenta__c); 
			}

			List<Account> clientes = new List<Account>([Select Id, Name, Id_Navision__c, Recordtype.DeveloperName from Account where Id in :clienteIDs]);

			for (Account cliente:clientes)
			{
				mapaClientes.put(cliente.Id, cliente);
			}
		}
		System.Debug('## after loadData mapaClientes: ' + mapaClientes);
	}
    

	public static void SincronizarClientes(list<Direcci_n_de_entrega__c> newList, Map<String, Account> mapaClientes)
	{
		System.Debug('## before SincronizarClientes semaforoUpdate: ' + semaforoUpdate);
		if (semaforoUpdate)
		{
			List<Account> listaCuentas = new List<Account>();
			
			for(Id idCuentaTemp : mapaClientes.KeySet())
			{
				listaCuentas.add(mapaClientes.get(idCuentaTemp));
			}
			
			// Recuperamos el tipo de registro "Cliente existente"
			RecordType rts = Util.objectsRecordTypesMap.get('Account').get('Cliente_existente');
			
			if (listaCuentas != null && listaCuentas.size()>0)
			{
				List<String> clientesSync = new List<String>();
				
				for (Account cliente:listaCuentas)
				{
					// Se hace doble validación, se comprueba que sea de tipo de registro Cliente existente y que tenga algún contrato Activado
					if ( cliente.RecordTypeId == rts.Id  && !String.IsEmpty(cliente.Id_Navision__c))
					{
						clientesSync.add(cliente.Id);
					}
				}
				// Enviamos los clientes correspondientes a sincronizar
				System.debug('Clientes a sincronizar -> ' + clientesSync);
				if(clientesSync.size() > 0)
				{
					SyncNav.SincronizarClientesFuture(clientesSync);
				}
			}
		}		 
		System.Debug('## after SincronizarClientes semaforoUpdate: ' + semaforoUpdate);
	}
    
    public static void ComprobarContratos(List<Direcci_n_de_entrega__c> Direcciones){
        List<Contract> ContrRel = [Select id,DateFirstFilled__c,Duraci_n_del_contrato_a_os__c,Estado_2__c,ActivatedDate from Contract Where Direccion_de_entrega__c =: Direcciones];
        ContractUtil.populateContractEndDate(ContrRel);
    }
    
}