force-app/main/default/objects/ApprovalMetric__mdt/ApprovalMetric__mdt.object-meta.xml
<CustomObject>
    <label>Métrica de Aprobación</label>
    <pluralLabel>Métricas de Aprobación</pluralLabel>
</CustomObject>

force-app/main/default/objects/ApprovalMetric__mdt/fields/ControllerField__c.field-meta.xml
<CustomField>
    <fullName>ControllerField__c</fullName>
    <description>Field API Names used to identify which process triggered the approval process.</description>
    <inlineHelpText>Nombre del campo que se usará para identificar el proceso que se ha activado.</inlineHelpText>
    <label>Campo de Control</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApprovalMetric__mdt/fields/QuoteField__c.field-meta.xml
<CustomField>
    <fullName>QuoteField__c</fullName>
    <description>API Name of the Quote Field to be approved.</description>
    <inlineHelpText>Nombre API del campo de Oferta a aprobar.</inlineHelpText>
    <label>Campo de Oferta</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApprovalMetric__mdt/fields/RelativeValueField__c.field-meta.xml
<CustomField>
    <fullName>RelativeValueField__c</fullName>
    <description>Quote field API Name to be compared for relative value stretches.</description>
    <inlineHelpText>Nombre API del campo de Oferta sobre el que se van a realizar las comparaciones.</inlineHelpText>
    <label>Campo de Valor Relativo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalMetric__mdt/fields/SkipApprovalField__c.field-meta.xml
<CustomField>
    <fullName>SkipApprovalField__c</fullName>
    <description>Checkbox field in SBQQ__Quote__c that, if true, skips the approval request generation.</description>
    <inlineHelpText>Campo casilla de Oferta que, en caso de estar seleccionado, se ignorará la creación de solicitudes de aprobación.</inlineHelpText>
    <label>Campo para Ignorar Aprobación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalMetric__mdt/fields/StretchType__c.field-meta.xml
<CustomField>
    <fullName>StretchType__c</fullName>
    <label>Tipo de Tramo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valor Absoluto</fullName>
                <default>true</default>
                <label>Valor Absoluto</label>
            </value>
            <value>
                <fullName>Valor Relativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/ApprovalMetricStretch__mdt.object-meta.xml
<CustomObject>
    <label>Tramo de Métrica de Aprobación</label>
    <pluralLabel>Tramos de Métrica de Aprobación</pluralLabel>
</CustomObject>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/ApprovalMetric__c.field-meta.xml
<CustomField>
    <fullName>ApprovalMetric__c</fullName>
    <label>Métrica de Aprobación</label>
    <referenceTo>ApprovalMetric__mdt</referenceTo>
    <relationshipLabel>Tramos</relationshipLabel>
    <relationshipName>Stretches</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/ApprovalRoleName__c.field-meta.xml
<CustomField>
    <fullName>ApprovalRoleName__c</fullName>
    <description>Approver&apos;s UserRole API Name.</description>
    <inlineHelpText>Nombre API de la función del usuario aprobador</inlineHelpText>
    <label>Función del Aprobador</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <label>Aprobador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
                <default>true</default>
                <label>Comercial</label>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Función específica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/MaxValue__c.field-meta.xml
<CustomField>
    <fullName>MaxValue__c</fullName>
    <label>Valor Máximo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/MinValue__c.field-meta.xml
<CustomField>
    <fullName>MinValue__c</fullName>
    <label>Valor Mínimo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/ApprovalRequest__c.object-meta.xml
<CustomObject>
    <label>Solicitud de aprobación</label>
    <nameField>
        <displayFormat>AR-{0}</displayFormat>
        <label>Solicitud de aprobación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes de aprobación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalRequest__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup a User que corresponde a OwnerId</description>
    <label>Aprobador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Solicitudes_de_aprobaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/GasPriceRange__c.field-meta.xml
<CustomField>
    <fullName>GasPriceRange__c</fullName>
    <label>Margen de Gas</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <label>Inversión</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Posición</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <description>SBQQ__Quote__c</description>
    <label>Oferta</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Solicitudes de aprobación</relationshipLabel>
    <relationshipName>ApprovalRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente otros revisores</fullName>
                <default>true</default>
                <label>Pendiente otros revisores</label>
            </value>
            <value>
                <fullName>Desestimado</fullName>
            </value>
            <value>
                <fullName>En revisión</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GasPriceRange__c/GasPriceRange__c.object-meta.xml
<CustomObject>
    <label>Maestro de Margen de Gas</label>
    <nameField>
        <displayFormat>GPR {00000}</displayFormat>
        <label>Referencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestros de Margen de Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/GasPriceRange__c.field-meta.xml
<CustomField>
    <fullName>GasPriceRange__c</fullName>
    <label>Margen de Gas</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <label>Inversión Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/NonRecoveryInvestment__c.field-meta.xml
<CustomField>
    <fullName>NonRecoveryInvestment__c</fullName>
    <label>Inversión no recuperable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PBA__c.field-meta.xml
<CustomField>
    <fullName>PBA__c</fullName>
    <label>PBA</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/Stretch__c.object-meta.xml
<CustomObject>
    <label>Tramo</label>
    <nameField>
        <label>Nombre del tramo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tramos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stretch__c/fields/PBA__c.field-meta.xml
<CustomField>
    <fullName>PBA__c</fullName>
    <label>PBA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stretch__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Stretches</relationshipLabel>
    <relationshipName>Stretches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ApprovalProcessOrchestrator.cls
public without sharing class ApprovalProcessOrchestrator {

    @InvocableMethod(label='Submit Quotes for Approval' description='Create Approval Request records and locks the Quote for edit.')
    public static void submitQuoteToApproval(List<Id> quoteIds) {
        for (Id quoteId : quoteIds) {
            ApprovalProcessOrchestrator orchestrator = new ApprovalProcessOrchestrator(quoteId);
            orchestrator.submitToApproval();
        }
    }

    private static Map<Id, User> delegatedApprovers {	
        get {	
            if (delegatedApprovers == null) {	
                Map<Id, User> approvers;	
                Map<Id, Id> delegatedApproverIds = new Map<Id, Id>();	
                for (User user : UserRepository.getUsersWithDelegatedApprovers()) {	
                    delegatedApproverIds.put(user.Id, user.DelegatedApproverId);	
                }	
                approvers = new Map<Id, User>(UserRepository.getUsersByIds(delegatedApproverIds.values()));	
                delegatedApprovers = new Map<Id, User>();	
                for (Id userId : delegatedApproverIds.keySet()) {	
                    delegatedApprovers.put(userId, approvers.get(delegatedApproverIds.get(userId)));	
                }	
            }	
            return delegatedApprovers;	
        }	
        set;	
    }

    private SBQQ__Quote__c quote;
    private Map<Id, ApprovalRequest__c> approvalRequests;
    private List<SortableApprovalRequest> sortableRequests;

    public ApprovalProcessOrchestrator(Id quoteId) {
        this.quote = this.getQuoteById(quoteId);
        this.approvalRequests = new Map<Id, ApprovalRequest__c>();
        this.sortableRequests = new List<SortableApprovalRequest>();
    }

    private SBQQ__Quote__c getQuoteById(Id quoteId) {
        return ((List<SBQQ__Quote__c>) Database.query(buildQuoteQuery(quoteId)))[0];
    }

    private String buildQuoteQuery(Id quoteId) {
        String query = 'SELECT Id, OwnerId, Owner.UserRoleId, Owner.UserRole.ParentRoleId';
        Set<String> requestedFields = new Set<String>();
        for (ApprovalMetric__mdt metric : ApprovalMetricRepository.getActiveApprovalMetrics()) {
            if (String.isNotBlank(metric.QuoteField__c) && requestedFields.add(metric.QuoteField__c)) {
                query += ', ' + metric.QuoteField__c;
            }
            if (String.isNotBlank(metric.RelativeValueField__c) && requestedFields.add(metric.RelativeValueField__c)) {
                query += ', ' + metric.RelativeValueField__c;
            }
            if (String.isNotBlank(metric.SkipApprovalField__c) && requestedFields.add(metric.SkipApprovalField__c)) {
                query += ', ' + metric.SkipApprovalField__c;
            }
        }
        query += ' FROM SBQQ__Quote__c WHERE Id = \'' + quoteId + '\'';
        return query;
    }

    public void submitToApproval() {
        generateApprovalRequests();
        if (!this.approvalRequests.isEmpty()) {
            sortApprovalRequests();
            setApprovalRequestsInitialStatus();
            insertApprovalRequests();
            if (hasPendingRequests()) {
                lockQuote();
            } else {
                approveQuote();
            }
        } else {
            approveQuote();
        }
    }

    private void generateApprovalRequests() {
        Decimal quoteMetricValue;
        for (ApprovalMetric__mdt metric : ApprovalMetricRepository.getActiveApprovalMetrics()) {
            if (!quoteHasValidMetrics(metric) || mustBeSkipped(metric)) {
                continue;
            }
            quoteMetricValue = formatQuoteMetricValue(metric);
            for (ApprovalMetricStretch__mdt stretch : metric.Stretches__r) {
                if (stretch.MinValue__c <= quoteMetricValue && quoteMetricValue < stretch.MaxValue__c) {
                    generateApprovalRequest(metric, stretch);
                }
            }
        }
    }

    private Boolean quoteHasValidMetrics(ApprovalMetric__mdt metric) {
        return this.quote.get(metric.QuoteField__c) != null && (metric.StretchType__c != ApprovalMetricConstants.STRETCH_TYPE_RELATIVE 
                || this.quote.get(metric.RelativeValueField__c) != null);
    }

    private Boolean mustBeSkipped(ApprovalMetric__mdt metric) {
        return String.isNotBlank(metric.SkipApprovalField__c) && ((Boolean) this.quote.get(metric.SkipApprovalField__c) == true);
    }

    private Decimal formatQuoteMetricValue(ApprovalMetric__mdt metric) {
        if (metric.StretchType__c == ApprovalMetricConstants.STRETCH_TYPE_ABSOLUTE) {
            return (Decimal) this.quote.get(metric.QuoteField__c);
        } else if (metric.StretchType__c == ApprovalMetricConstants.STRETCH_TYPE_RELATIVE) {
            return (Decimal) this.quote.get(metric.QuoteField__c) / (Decimal) this.quote.get(metric.RelativeValueField__c) * 100;
        }
        return null;
    }

    private void generateApprovalRequest(ApprovalMetric__mdt metric, ApprovalMetricStretch__mdt stretch) {
        User approver = getApprover(stretch);
        if (approver == null) {
            return;
        }
        if (!this.approvalRequests.containsKey(approver.Id)) {
            this.approvalRequests.put(approver.Id, new ApprovalRequest__c(
                Approver__c = approver.Id,
                Quote__c = quote.Id,
                PBA__c = quote.PBA__c,
                GasPriceRange__c = quote.GasPriceRange__c,
                Credit__c = quote.Credit__c,
                Investment__c = quote.Investment__c,
                NonRecoveryInvestment__c = quote.NonRecoveryInvestment__c,
                Position__c = getUserRoleDepth(approver.UserRoleId)
            ));
        }
        if (String.isNotBlank(metric.ControllerField__c)) {
            this.approvalRequests.get(approver.Id).put(metric.ControllerField__c, true);
        }
    }

    private Integer getUserRoleDepth(Id userRoleId) {
        Integer depth = UserRoleService.getUserRoleDepth(userRoleId)?.depth;
        return depth;
    }

    private User getApprover(ApprovalMetricStretch__mdt stretch) {
        User approver;
        if (stretch.Approver__c == ApprovalMetricConstants.APPROVER_TYPE_SELF) {
            approver = new User (	
                Id = this.quote.OwnerId,	
                UserRoleId = this.quote.Owner.UserRoleId	
            );	
        } else if (stretch.Approver__c == ApprovalMetricConstants.APPROVER_TYPE_MANAGER) {
            approver = UserRoleService.getSampleUserByUserRoleId(this.quote.Owner.UserRole.ParentRoleId);
        } else if (stretch.Approver__c == ApprovalMetricConstants.APPROVER_TYPE_USERROLE) {
            if (UserRoleService.userRolesByDeveloperName.containsKey(stretch.ApprovalRoleName__c)) {
                approver = UserRoleService.getSampleUserByUserRoleId(
                    UserRoleService.userRolesByDeveloperName.get(stretch.ApprovalRoleName__c).Id
                );    
            }
        }
        if (approver != null && delegatedApprovers.containsKey(approver.Id)) {	
            approver = delegatedApprovers.get(approver.Id);	
        }	
        return approver;	
    }

    private void sortApprovalRequests() {
        Integer orderedPosition = 1;
        for (ApprovalRequest__c request: this.approvalRequests.values()) {
            sortableRequests.add(new SortableApprovalRequest(request));
        }
        sortableRequests.sort();
        for (SortableApprovalRequest sortableRequest : sortableRequests) {
            sortableRequest.request.Position__c = orderedPosition++;
        }
    }

    private void setApprovalRequestsInitialStatus() {
        for (SortableApprovalRequest sortableRequest: sortableRequests) {
            if (sortableRequest.request.Approver__c ==  UserInfo.getUserId()) {
                sortableRequest.request.Resolution__c = ApprovalRequestConstants.RESOLUTION_APPROVED;
            } else {
                sortableRequest.request.Status__c = ApprovalRequestConstants.STATUS_REVIEWING;
            }
            break;
        }
    }

    private void insertApprovalRequests() {
        insert this.approvalRequests.values();
    }

    private Boolean hasPendingRequests() {
        for (ApprovalRequest__c request : this.approvalRequests.values()) {
            if (request.Resolution__c != ApprovalRequestConstants.RESOLUTION_APPROVED) {
                return true;
            }
        }
        return false;
    }

    private void lockQuote() {
        this.quote.SBQQ__Status__c = CPQ_QuoteConstants.STATUS_PENDING_APPROVAL;
        update this.quote;
        System.Approval.lock(this.quote.Id);
    }

    private void approveQuote() {
        this.quote.SBQQ__Status__c = CPQ_QuoteConstants.STATUS_APPROVED;
        update this.quote;
    }

    public class SortableApprovalRequest implements Comparable {

        private ApprovalRequest__c request;
        
        public SortableApprovalRequest(ApprovalRequest__c request) {
            this.request = request;
        }

        public Integer compareTo(Object compareTo) {
            SortableApprovalRequest requestToCompare = (SortableApprovalRequest) compareTo;
            if (this.request.Approver__c == UserInfo.getUserId()) {
                if (requestToCompare.request.Approver__c == this.request.Approver__c) {
                    return 0;
                }
                return -1;
            }
            if (requestToCompare.request.Approver__c == UserInfo.getUserId()) {
                return 1;
            }
            if (this.request.Position__c == requestToCompare.request.Position__c) {
                return 0;
            }
            if (this.request.Position__c == null || this.request.Position__c > requestToCompare.request.Position__c) {
                return -1;
            } 
            return 1;
        }        
    }
}