force-app/main/default/objects/ApprovalMetric__mdt/ApprovalMetric__mdt.object-meta.xml
<CustomObject>
    <label>Métrica de Aprobación</label>
    <pluralLabel>Métricas de Aprobación</pluralLabel>
</CustomObject>

force-app/main/default/objects/ApprovalMetric__mdt/fields/ControllerField__c.field-meta.xml
<CustomField>
    <fullName>ControllerField__c</fullName>
    <description>Field API Names used to identify which process triggered the approval process.</description>
    <inlineHelpText>Nombre del campo que se usará para identificar el proceso que se ha activado.</inlineHelpText>
    <label>Campo de Control</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApprovalMetric__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApprovalMetric__mdt/fields/QuoteField__c.field-meta.xml
<CustomField>
    <fullName>QuoteField__c</fullName>
    <description>API Name of the Quote Field to be approved.</description>
    <inlineHelpText>Nombre API del campo de Oferta a aprobar.</inlineHelpText>
    <label>Campo de Oferta</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApprovalMetric__mdt/fields/RelativeValueField__c.field-meta.xml
<CustomField>
    <fullName>RelativeValueField__c</fullName>
    <description>Quote field API Name to be compared for relative value stretches.</description>
    <inlineHelpText>Nombre API del campo de Oferta sobre el que se van a realizar las comparaciones.</inlineHelpText>
    <label>Campo de Valor Relativo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalMetric__mdt/fields/SkipApprovalField__c.field-meta.xml
<CustomField>
    <fullName>SkipApprovalField__c</fullName>
    <description>Checkbox field in SBQQ__Quote__c that, if true, skips the approval request generation.</description>
    <inlineHelpText>Campo casilla de Oferta que, en caso de estar seleccionado, se ignorará la creación de solicitudes de aprobación.</inlineHelpText>
    <label>Campo para Ignorar Aprobación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalMetric__mdt/fields/StretchType__c.field-meta.xml
<CustomField>
    <fullName>StretchType__c</fullName>
    <label>Tipo de Tramo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valor Absoluto</fullName>
                <default>true</default>
                <label>Valor Absoluto</label>
            </value>
            <value>
                <fullName>Valor Relativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/ApprovalMetricStretch__mdt.object-meta.xml
<CustomObject>
    <label>Tramo de Métrica de Aprobación</label>
    <pluralLabel>Tramos de Métrica de Aprobación</pluralLabel>
</CustomObject>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/ApprovalMetric__c.field-meta.xml
<CustomField>
    <fullName>ApprovalMetric__c</fullName>
    <label>Métrica de Aprobación</label>
    <referenceTo>ApprovalMetric__mdt</referenceTo>
    <relationshipLabel>Tramos</relationshipLabel>
    <relationshipName>Stretches</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/ApprovalRoleName__c.field-meta.xml
<CustomField>
    <fullName>ApprovalRoleName__c</fullName>
    <description>Approver&apos;s UserRole API Name.</description>
    <inlineHelpText>Nombre API de la función del usuario aprobador</inlineHelpText>
    <label>Función del Aprobador</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <label>Aprobador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
                <default>true</default>
                <label>Comercial</label>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Función específica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/MaxValue__c.field-meta.xml
<CustomField>
    <fullName>MaxValue__c</fullName>
    <label>Valor Máximo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalMetricStretch__mdt/fields/MinValue__c.field-meta.xml
<CustomField>
    <fullName>MinValue__c</fullName>
    <label>Valor Mínimo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApprovalMetricRepository.cls
public without sharing class ApprovalMetricRepository {

    private static List<ApprovalMetric__mdt> activeApprovalMetrics {
        get {
            if (activeApprovalMetrics == null) {
                activeApprovalMetrics = [
                    SELECT
                        IsActive__c,
                        ControllerField__c,
                        QuoteField__c,
                        StretchType__c,
                        RelativeValueField__c,
                        SkipApprovalField__c,
                        (
                            SELECT
                                ApprovalRoleName__c,
                                ApprovalMetric__c,
                                Approver__c,
                                MaxValue__c,
                                MinValue__c
                            FROM
                                Stretches__r
                        )
                    FROM
                        ApprovalMetric__mdt
                    WHERE
                        IsActive__c = true
                ];
            }
            return activeApprovalMetrics;
        }
        set;
    }

    public static List<ApprovalMetric__mdt> getActiveApprovalMetrics() {
        return activeApprovalMetrics;
    }
}