force-app/main/default/objects/GasCost__c/GasCost__c.object-meta.xml
<CustomObject>
    <label>Coste de Gas</label>
    <nameField>
        <displayFormat>GC {000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costes de Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GasCost__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Coste</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GasCost__c/fields/TransportationCost__c.field-meta.xml
<CustomField>
    <fullName>TransportationCost__c</fullName>
    <label>Coste de Transporte</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CPQ_GasCostSelector.cls
public with sharing class CPQ_GasCostSelector {
    
    public static List<GasCost__c> selectByProvinces(Set<String> provinces){
        CPQ_LogUtil.debug('*SELECTOR* [CPQ_GasCostSelector] selectByProvinces');
        
        return [SELECT  Id,
                        County__c,
                        Cost__c,
                        TransportationCost__c
                FROM GasCost__c
                WHERE County__c IN :provinces];
    }
}