force-app/main/default/objects/ApprovalRequest__c/ApprovalRequest__c.object-meta.xml
<CustomObject>
    <label>Solicitud de aprobación</label>
    <nameField>
        <displayFormat>AR-{0}</displayFormat>
        <label>Solicitud de aprobación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes de aprobación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalRequest__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup a User que corresponde a OwnerId</description>
    <label>Aprobador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Solicitudes_de_aprobaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/GasPriceRange__c.field-meta.xml
<CustomField>
    <fullName>GasPriceRange__c</fullName>
    <label>Margen de Gas</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <label>Inversión</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Posición</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <description>SBQQ__Quote__c</description>
    <label>Oferta</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Solicitudes de aprobación</relationshipLabel>
    <relationshipName>ApprovalRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GasPriceRange__c/GasPriceRange__c.object-meta.xml
<CustomObject>
    <label>Maestro de Margen de Gas</label>
    <nameField>
        <displayFormat>GPR {00000}</displayFormat>
        <label>Referencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maestros de Margen de Gas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/GasPriceRange__c.field-meta.xml
<CustomField>
    <fullName>GasPriceRange__c</fullName>
    <label>Margen de Gas</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <label>Inversión Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/NonRecoveryInvestment__c.field-meta.xml
<CustomField>
    <fullName>NonRecoveryInvestment__c</fullName>
    <label>Inversión no recuperable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PBA__c.field-meta.xml
<CustomField>
    <fullName>PBA__c</fullName>
    <label>PBA</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApprovalProcessSkipManager.cls
public with sharing class ApprovalProcessSkipManager {

    private static final Integer DEFAULT_POSITION = 1;

    @InvocableMethod(label='Skip Approval Process' description='Automatically approves the quote and deletes pending approval requests if any')
    public static void skipApprovalProcess(List<Id> quoteIds) {
        for (Id quoteId : quoteIds) {
            System.Approval.unlock(quoteId);
            delete ApprovalRequestRepository.getPendingResolutionRequests(new Set<Id> {quoteId});
            SBQQ__Quote__c quote = CPQ_QuoteRepository.getQuoteById(quoteId);
            insert new ApprovalRequest__c(
                Approver__c = UserInfo.getUserId(),
                Quote__c = quote.Id,
                PBA__c = quote.PBA__c,
                GasPriceRange__c = quote.GasPriceRange__c,
                Credit__c = quote.Credit__c,
                Investment__c = quote.Investment__c,
                NonRecoveryInvestment__c = quote.NonRecoveryInvestment__c,
                Position__c = DEFAULT_POSITION,
                Resolution__c = ApprovalRequestConstants.RESOLUTION_APPROVED
            );
        }
    }
}