force-app/main/default/objects/ApprovalRequest__c/ApprovalRequest__c.object-meta.xml
<CustomObject>
    <label>Solicitud de aprobación</label>
    <nameField>
        <displayFormat>AR-{0}</displayFormat>
        <label>Solicitud de aprobación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes de aprobación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalRequest__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <description>SBQQ__Quote__c</description>
    <label>Oferta</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Solicitudes de aprobación</relationshipLabel>
    <relationshipName>ApprovalRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/HasStretches__c.field-meta.xml
<CustomField>
    <fullName>HasStretches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tiene tramos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ApprovalProcessSkipManagerTest.cls
@isTest
public class ApprovalProcessSkipManagerTest {
    
    @isTest
    public static void testApprovalProcessSkipManagerTest() {
        List<Integer> positions = new List<Integer> {3, 2, 1, null};
        Account account = ApprovalTestDataFactory.createAccount(null);
        insert account;
        Opportunity opportunity = ApprovalTestDataFactory.createOpportunity(account.Id, null);
        insert opportunity;
        SBQQ__Quote__c quote = ApprovalTestDataFactory.createQuote(opportunity.Id, new Map<String, Object> {
            'HasStretches__c' => true
        });
        insert quote;
        Test.startTest();
        ApprovalProcessSkipManager.skipApprovalProcess(new List<Id>{quote.Id});
        Test.stopTest();
        List<ApprovalRequest__c> requests = [SELECT Id, Quote__r.SBQQ__Status__c, Resolution__c FROM ApprovalRequest__c];
        System.assertEquals(1, requests.size());
        System.assertEquals(CPQ_QuoteConstants.STATUS_APPROVED, requests[0].Quote__r.SBQQ__Status__c);
        System.assertEquals(ApprovalRequestConstants.RESOLUTION_APPROVED, requests[0].Resolution__c);

    }
}