force-app/main/default/objects/ApprovalRequest__c/ApprovalRequest__c.object-meta.xml
<CustomObject>
    <label>Solicitud de aprobación</label>
    <nameField>
        <displayFormat>AR-{0}</displayFormat>
        <label>Solicitud de aprobación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes de aprobación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente otros revisores</fullName>
                <default>true</default>
                <label>Pendiente otros revisores</label>
            </value>
            <value>
                <fullName>Desestimado</fullName>
            </value>
            <value>
                <fullName>En revisión</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/TimestampCompleted__c.field-meta.xml
<CustomField>
    <fullName>TimestampCompleted__c</fullName>
    <label>Fecha Completado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/TimestampReviewing__c.field-meta.xml
<CustomField>
    <fullName>TimestampReviewing__c</fullName>
    <label>Fecha en revisión</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ApprovalRequestService.cls
public class ApprovalRequestService {

    private static final Map<String, String> TIMESTAMPS = new Map<String, String> {
        ApprovalRequestConstants.STATUS_REVIEWING => 'TimestampReviewing__c',
        ApprovalRequestConstants.STATUS_COMPLETED => 'TimestampCompleted__c'
    };

    public static void setTimestamps(ApprovalRequest__c request) {
        if (TIMESTAMPS.containsKey(request.Status__c)) {
            request.put(TIMESTAMPS.get(request.Status__c), System.now());
        }
    }

    public static void setTimestamps(ApprovalRequest__c newRequest, ApprovalRequest__c oldRequest) {
        if (newRequest.Status__c != oldRequest.Status__c) {
            setTimestamps(newRequest);
        }
    }

    public static void unlockQuoteForEdition(Id quoteId) {
        System.Approval.unlock(quoteId);
        update new SBQQ__Quote__c(
            Id = quoteId,
            SBQQ__Status__c = CPQ_QuoteConstants.STATUS_DRAFT
        );
        delete ApprovalRequestRepository.getPendingResolutionRequests(new Set<Id> {quoteId});
    }
}