force-app/main/default/objects/ApprovalRequest__c/ApprovalRequest__c.object-meta.xml
<CustomObject>
    <label>Solicitud de aprobación</label>
    <nameField>
        <displayFormat>AR-{0}</displayFormat>
        <label>Solicitud de aprobación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes de aprobación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalRequest__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Posición</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <description>SBQQ__Quote__c</description>
    <label>Oferta</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Solicitudes de aprobación</relationshipLabel>
    <relationshipName>ApprovalRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente otros revisores</fullName>
                <default>true</default>
                <label>Pendiente otros revisores</label>
            </value>
            <value>
                <fullName>Desestimado</fullName>
            </value>
            <value>
                <fullName>En revisión</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalRequestRepository.cls
public without sharing class ApprovalRequestRepository {

    public static final String RESOLUTION_PENDING = 'Pending';
    public static final String RESOLUTION_APPROVED = 'Approved';
    public static final String RESOLUTION_REJECTED = 'Rejected';

    public static List<SBQQ__Quote__c> getQuotesWithStatusPendingRequests(Set<Id> quoteIds) {
        return [
            SELECT
                Id,
                SBQQ__Status__c,
                (
                    SELECT
                        Id,
                        Resolution__c,
                        Status__c,
                        Position__c
                    FROM
                        ApprovalRequests__r
                    WHERE
                        Status__c = :ApprovalRequestConstants.STATUS_PENDING
                    ORDER BY
                        Position__c ASC NULLS FIRST
                )
            FROM
                SBQQ__Quote__c
            WHERE
                Id IN :quoteIds
        ];
    }

    public static List<ApprovalRequest__c> getPendingResolutionRequests(Set<Id> quoteIds) {
        return [
            SELECT
                Id
            FROM
                ApprovalRequest__c
            WHERE
                Quote__c IN :quoteIds
            AND
                Resolution__c = :ApprovalRequestConstants.RESOLUTION_PENDING
        ];
    }
}