force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Se registran errors generados en código y el historial de sincronización con Navision</description>
    <label>Log</label>
    <nameField>
        <label>Nombre de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Enviado_a_Navision__c.field-meta.xml
<CustomField>
    <fullName>Enviado_a_Navision__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se marcará cuando se haya enviado el log a Navision para no enviar nunca el mismo log dos veces.</description>
    <label>Enviado a Navision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Id_NewSales__c.field-meta.xml
<CustomField>
    <fullName>Id_NewSales__c</fullName>
    <description>Identificadores enviados desde NewSales</description>
    <label>Id_NewSales</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Objeto__c.field-meta.xml
<CustomField>
    <fullName>Objeto__c</fullName>
    <label>Objeto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Elemento de servicio</fullName>
            </value>
            <value>
                <fullName>Tarifa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <description>Los de excepciones o errores de código</description>
    <label>Error</label>
</RecordType>

force-app/main/default/classes/LogUtil.cls
/** 
* Clase Constantes
**
* @Funcionalidad: Clase encargada de guardar los Logs que se hayan ido creando.
**
* @Autor: Rubén Goitia García (12/03/2014)
**
**/

public class LogUtil 
{
	public static List<Log__c> errores;

	public static Map<String, String> mapaTiposRegistro;
	
	public static void crearLog(String descripcion, String metodo, String objeto, String tipoError, Boolean isError)	
	{
		if (errores == null)
		{
			errores = new List<Log__c>();
		}
        
		if (mapaTiposRegistro == null)
		{
			mapaTiposRegistro = new Map<String, String>();
			List<RecordType> rts = new List<RecordType>([Select Id, Name, DeveloperName from Recordtype where SobjectType = 'Log__c']);
			for (RecordType rt:rts)
			{
				mapaTiposRegistro.put(rt.DeveloperName, rt.Id);
			}
		}	
        
        descripcion = descripcion.abbreviate(130000);
        
		Log__c error = new Log__c(Error__c = isError, Descripcion__c = descripcion, Metodo__c = metodo, Objeto__c = objeto, RecordTypeId = mapaTiposRegistro.get(tipoError), Enviado_a_Navision__c = false);
		//////
		if(Test.isRunningTest())
        {
        	error.CreatedDate = System.today().addDays(-60);
        }
		////// 
		errores.add(error);
	}
    
    public static void crearLog(String descripcion, String metodo, String objeto, String tipoError, Boolean isError, String identificador)	
	{
		if (errores == null)
		{
			errores = new List<Log__c>();
		}
        
		if (mapaTiposRegistro == null)
		{
			mapaTiposRegistro = new Map<String, String>();
			List<RecordType> rts = new List<RecordType>([Select Id, Name, DeveloperName from Recordtype where SobjectType = 'Log__c']);
			for (RecordType rt:rts)
			{
				mapaTiposRegistro.put(rt.DeveloperName, rt.Id);
			}
		}	
        
        descripcion = descripcion.abbreviate(130000);
        
		Log__c error = new Log__c(Error__c = isError, Descripcion__c = descripcion, Metodo__c = metodo, Objeto__c = objeto, RecordTypeId = mapaTiposRegistro.get(tipoError), Enviado_a_Navision__c = false, Id_NewSales__c = identificador);
		//////
		if(Test.isRunningTest())
        {
        	error.CreatedDate = System.today().addDays(-60);
        }
		//////
		errores.add(error);
	}
	
	public static void guardarLog()
	{
		system.debug('Logs de errores a insertar: ' + errores);
		if (errores != null)
		{
			insert errores;
			errores = new List<Log__c>();
		}
	}

	
}