force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Se registran errors generados en código y el historial de sincronización con Navision</description>
    <label>Log</label>
    <nameField>
        <label>Nombre de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Objeto__c.field-meta.xml
<CustomField>
    <fullName>Objeto__c</fullName>
    <label>Objeto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Elemento de servicio</fullName>
            </value>
            <value>
                <fullName>Tarifa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <description>Los de excepciones o errores de código</description>
    <label>Error</label>
</RecordType>

force-app/main/default/classes/TEST_BatchBorrarLogs.cls
@isTest
private class TEST_BatchBorrarLogs
{
	@isTest
	static void testBorrarLogs()
	{
		LogUtil.crearLog('Prueba1', 'Metodo1', 'Objeto1', 'Error', true);
		LogUtil.crearLog('Prueba2', 'Metodo2', 'Objeto2', 'Error', false);
		LogUtil.guardarLog();	

		List<Log__c> logs = [SELECT Id, Descripcion__c, Metodo__c, Objeto__c, Error__c, CreatedDate FROM Log__c];
		System.debug('Logs antes: ' + logs);
		System.assertEquals(logs.size(),2);
		// TO DO: fix, is throwing an exception when deploying
		/*

		Test.startTest();
		SchedulableContext SC;
		String CRON_EXP = '0 0 1 8 9 ? 2022';
		BatchBorrarLogs j = new BatchBorrarLogs();  
		String jobId = System.schedule('testJob', CRON_EXP,j);
		j.execute(SC);
		Test.stopTest();

		logs = [SELECT Id, Descripcion__c, Metodo__c, Objeto__c, Error__c, CreatedDate FROM Log__c];
		System.debug('Logs después: ' + logs);
		System.assertEquals(0,logs.size());
		*/
	}
}