force-app/main/default/objects/Lead/fields/C_digo_Postal__c.field-meta.xml
<CustomField>
    <fullName>C_digo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_State__c.field-meta.xml
<CustomField>
    <fullName>Contact_State__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alava/Araba</fullName>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Cáceres</fullName>
            </value>
            <value>
                <fullName>Cádiz</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ceuta</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Lleida/Lérida</fullName>
            </value>
            <value>
                <fullName>Lugo</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Fecha_Actividad_Asignacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Actividad_Asignacion__c</fullName>
    <description>Fecha de la primera actividad completada una vez que el candidato a sido asignado a un Comercial</description>
    <label>Fecha Actividad Asignación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Fecha_Asignado_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Asignado_Comercial__c</fullName>
    <label>Fecha Asignado Comercial</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/N_mero_cliente_anterior__c.field-meta.xml
<CustomField>
    <fullName>N_mero_cliente_anterior__c</fullName>
    <description>Número cliente anterior</description>
    <label>Número cliente anterior</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/testTriggerTask.cls
/**
Test para testear el trigger de tareas
Ponemos SeeAllData para que se pueda acceder a las etiquetas personalizadas
 */
@isTest(SeeAllData = true)
private class testTriggerTask {

    static testMethod void myUnitTest() {
    	Id prop = [Select Id from User where IsActive = true and ProfileId = :system.label.PerfilComercial LIMIT 1].get(0).id;
        Lead candidato = new Lead();
        candidato.lastName = 'test';
        candidato.OwnerId = prop;
        candidato.State = 'Prueba';
        candidato.C_digo_Postal__c = '28004';
        candidato.LeadSource = 'web';
        candidato.Contact_State__c = 'Prueba';
        candidato.Fecha_Asignado_Comercial__c = system.now();
        candidato.N_mero_Cliente_Anterior__c = 1111;
        insert candidato;
        
        Lead candidato2 = new Lead();
        candidato2.lastName = 'test';
        candidato2.OwnerId = prop;
        candidato2.State = 'Prueba';
        candidato2.C_digo_Postal__c = '28004';
        candidato2.LeadSource = 'web';
        candidato2.Contact_State__c = 'Prueba';
        candidato2.Fecha_Actividad_Asignacion__c = system.today()+5;
        candidato2.Fecha_Asignado_Comercial__c = system.now();
        candidato2.N_mero_Cliente_Anterior__c = 1112;
        insert candidato2;
        
        
        list<Task> lTareas = new list<Task> ();
        Task tarea = new Task ();
        tarea.subject = 'Llamada';
        tarea.Status = 'Completada';
        tarea.WhoId = candidato.Id;
        tarea.ActivityDate = system.today()+3;
        tarea.Fecha_fin_tarea__c = system.today()+3;
        tarea.OwnerId = prop;
        lTareas.add(tarea);
        
        Task tarea2 = new Task ();
        tarea2.subject = 'Llamada';
        tarea2.Status = 'Completada';
        tarea2.WhoId = candidato2.Id;
        tarea2.ActivityDate = system.today()+4;
        tarea2.Fecha_fin_tarea__c = system.today()+4;
        tarea2.OwnerId = prop;
        lTareas.add(tarea2);
        
        Task tarea3 = new Task ();
        tarea3.subject = 'Llamada';
        tarea3.Status = 'Completada';
        tarea3.WhoId = candidato2.Id;
        tarea3.ActivityDate = system.today()+3;
        tarea3.Fecha_fin_tarea__c = system.today()+3;
        tarea3.OwnerId = prop;
        lTareas.add(tarea3);
         
        test.startTest();
        	insert lTareas;
        test.stopTest();
    }
}