force-app/main/default/objects/Lead/fields/C_digo_Postal__c.field-meta.xml
<CustomField>
    <fullName>C_digo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_State__c.field-meta.xml
<CustomField>
    <fullName>Contact_State__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alava/Araba</fullName>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Avila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Cáceres</fullName>
            </value>
            <value>
                <fullName>Cádiz</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ceuta</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>A Coruña/La Coruña</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Girona/Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Gipuzkoa/Guipuzcoa</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Lleida/Lérida</fullName>
            </value>
            <value>
                <fullName>Lugo</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Fecha_Actividad_Asignacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Actividad_Asignacion__c</fullName>
    <description>Fecha de la primera actividad completada una vez que el candidato a sido asignado a un Comercial</description>
    <label>Fecha Actividad Asignación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Fecha_Asignado_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Asignado_Comercial__c</fullName>
    <label>Fecha Asignado Comercial</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/N_mero_cliente_anterior__c.field-meta.xml
<CustomField>
    <fullName>N_mero_cliente_anterior__c</fullName>
    <description>Número cliente anterior</description>
    <label>Número cliente anterior</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/testTriggerEvent.cls
/**
Test para testear el trigger de eventos
Ponemos SeeAllData para que se pueda acceder a las etiquetas personalizadas
 */
@isTest(SeeAllData = true)
private class testTriggerEvent {

    static testMethod void myUnitTest() {
        Id prop = [Select Id from User where IsActive = true and ProfileId = :system.label.PerfilComercial LIMIT 1].get(0).id;
        Lead candidato = new Lead();
        candidato.lastName = 'test';
        candidato.OwnerId = prop;
        candidato.State = 'Prueba';
        candidato.C_digo_Postal__c = '28004';
        candidato.LeadSource = 'web';
        candidato.Contact_State__c = 'Prueba';
        candidato.Fecha_Asignado_Comercial__c = system.now();
        candidato.N_mero_Cliente_Anterior__c = 1111;
        insert candidato;
        
        Lead candidato2 = new Lead();
        candidato2.lastName = 'test';
        candidato2.OwnerId = prop;
        candidato2.State = 'Prueba';
        candidato2.C_digo_Postal__c = '28004';
        candidato2.LeadSource = 'web';
        candidato2.Contact_State__c = 'Prueba';
        candidato2.Fecha_Actividad_Asignacion__c = system.today()+5;
        candidato2.N_mero_Cliente_Anterior__c = 1112;
        insert candidato2;
        
        list<Event> lEventos = new list<Event> ();
        Event evento = new Event();
        evento.Subject = 'Reunión';
        evento.WhoId = candidato.Id;
        evento.StartDateTime = system.now()+1;
        evento.EndDateTime = system.now()+1;
        evento.OwnerId = prop;
        lEventos.add(evento);
        
        Event evento2 = new Event();
        evento2.Subject = 'Reunión';
        evento2.WhoId = candidato2.Id;
        evento2.StartDateTime = system.now()+2;
        evento2.EndDateTime = system.now()+2;
        evento2.OwnerId = prop;
        lEventos.add(evento2);
        
        Event evento3 = new Event();
        evento3.Subject = 'Reunión';
        evento3.WhoId = candidato2.Id;
        evento3.StartDateTime = system.now()+1;
        evento3.EndDateTime = system.now()+1;
        evento3.OwnerId = prop;
        lEventos.add(evento3);
         
        test.startTest();
        	insert lEventos;
        	update lEventos;
        test.stopTest();
    }
}